# Italian Trends Covid-19

In this Notebook, we analyze the spreading of the new coronavirus in Italy.

## Libraries and Functions

First we import the required libraries and define the bokeh plot functions:

In [1]:
import numpy as np

import pandas as pd

from math import pi

from bokeh.plotting import figure, output_file, show, output_notebook, gridplot
from bokeh.models import DatetimeTickFormatter, BasicTickFormatter, NumeralTickFormatter
from bokeh.models import HoverTool
from bokeh.layouts import row

output_notebook()

Loading BokehJS ...

In [2]:
def datetime(x):
    return np.array(x, dtype=np.datetime64)

---------------------

### ----- Plot function 1 line -----

In [3]:
def bokeh_plot_1_line(x, y, title, file_name, x_label, y_label, legend, x_label_hover, y_label_hover, color, y_minmax):
    
    output_file(file_name)
    
    p = figure(title=title, x_axis_type='datetime', x_axis_label=x_label, y_axis_label=y_label, width=600, height=450, y_range=y_minmax)
    
    p.line(x.squeeze(), y, color=color, line_width=4, legend_label=legend)
    p.circle(x.squeeze(), y, fill_color="white", line_color=color, size=6)
    
    p.xaxis.formatter = DatetimeTickFormatter(
#         hours=["%d %B %Y"],
#         days=["%Y %m %d"],
        days=["%d %B"],
#         months=["%d %B %Y"],
#         years=["%d %B %Y"],
    )
    p.xaxis.major_label_orientation = pi/4
  
    p.yaxis.formatter = BasicTickFormatter(use_scientific = False)
#     p.left[0].formatter.use_scientific = False
    p.yaxis.formatter = NumeralTickFormatter(format = '0,0')
    
    p.axis.minor_tick_in = -5
    p.axis.minor_tick_out = -3
    
    p.legend.location = "top_left"
    
    p.add_tools(HoverTool(
    tooltips=[
        ( x_label_hover,   '@x{%d %B}'    ),
        ( y_label_hover, '@y{0.}'      ),
    ],

    formatters={
           '@x'  : 'datetime', # use 'datetime' formatter for 'date' field
#            '@y'  : 'printf',   # use 'printf' formatter for 'adj close' field
                                  # use default 'numeral' formatter for other fields
    },

    # display a tooltip whenever the cursor is vertically in line with a glyph
    mode='vline'
    ))

    return p
#     show(p)

### ----- Plot function 2 lines -----

In [4]:
def bokeh_plot_2_lines(x, y, yy, title, file_name, x_label, y_label, legend_1, legend_2, x_label_hover, y_label_hover, color_1, color_2, y_minmax):
    
    output_file(file_name)
    
    p = figure(title=title, x_axis_type='datetime', x_axis_label=x_label, y_axis_label=y_label, width=600, height=450, y_range=y_minmax)
    
    p.line(x, y, color=color_1, line_width=4, legend_label=legend_1)
    p.circle(x, y, fill_color="white", line_color=color_1, size=6)
    
    p.line(x, yy, color=color_2, line_width=4, legend_label=legend_2)
    p.circle(x, yy, fill_color="white", line_color=color_2, size=6)
    
    p.xaxis.formatter=DatetimeTickFormatter(
#         hours=["%d %B %Y"],
#         days=["%Y %m %d"],
    days=["%d %B"],
#         months=["%d %B %Y"],
#         years=["%d %B %Y"],
    )
    p.xaxis.major_label_orientation = pi/4
  
    p.yaxis.formatter = BasicTickFormatter(use_scientific=False)
#     p.left[0].formatter.use_scientific = False
    p.yaxis.formatter = NumeralTickFormatter(format = '0,0')
    
    p.axis.minor_tick_in = -5
    p.axis.minor_tick_out = -3
    
    p.legend.location = "top_left"
    
    p.add_tools(HoverTool(
    tooltips=[
        ( x_label_hover,   '@x{%d %B}' ),
        ( y_label_hover, '@y{0.}' ),
#         ( 'label yy', '@yy' ),
    ],

    formatters={
           '@x'  : 'datetime', # use 'datetime' formatter for 'date' field
#            '@y'  : 'printf',   # use 'printf' formatter for 'adj close' field
                                  # use default 'numeral' formatter for other fields
    },

    # display a tooltip whenever the cursor is vertically in line with a glyph
    mode='vline'
    ))
    
    return p  
#     show(p)

### ----- Plot function N lines -----

In [5]:
def bokeh_plot_N_lines(x, y_list, title, dim, x_label, y_label, legend_list, x_label_hover, y_label_hover, color_list, legend_location, y_minmax):
    
#     output_file(file_name)
    
    p = figure(title=title, x_axis_type='datetime', x_axis_label=x_label, y_axis_label=y_label, width=dim[0], height=dim[1], y_range=y_minmax)
    
    for iii in range(0,len(y_list)):
        p.line(x, y_list[iii], color=color_list[iii], line_width=4, legend_label=legend_list[iii])
        p.circle(x, y_list[iii], fill_color="white", line_color=color_list[iii], size=5)
        
    
    p.xaxis.formatter=DatetimeTickFormatter(
#         hours=["%d %B %Y"],
#         days=["%Y %m %d"],
    days=["%d %B"],
#         months=["%d %B %Y"],
#         years=["%d %B %Y"],
    )
    p.xaxis.major_label_orientation = pi/4
  
    p.yaxis.formatter = BasicTickFormatter(use_scientific=False)
#     p.left[0].formatter.use_scientific = False
#     p.yaxis.formatter = NumeralTickFormatter(format = '0,0')
    p.yaxis.formatter.use_scientific = False
    
    p.axis.minor_tick_in = -5
    p.axis.minor_tick_out = -3
    
    p.legend.location = legend_location
    
    p.add_tools(HoverTool(
    tooltips=[
        ( x_label_hover,   '@x{%d %B}' ),
        ( y_label_hover, '@y{0[.]000}' ),
#         ( 'label yy', '@yy' ),
    ],

    formatters={
           '@x'  : 'datetime', # use 'datetime' formatter for 'date' field
#            '@y'  : 'printf',   # use 'printf' formatter for 'adj close' field
#            '@y'  : 'numeral',   # use 'printf' formatter for 'adj close' field
                                  # use default 'numeral' formatter for other fields
    },

    # display a tooltip whenever the cursor is vertically in line with a glyph
    mode='vline'
    ))
    
    return p  
#     show(p)

-----------------

## Data Sources

We importe the CSV files directly from the official GitHub source of the Protezione Civile:

In [6]:
data_links = {'nazionale':'https://raw.githubusercontent.com/pcm-dpc/COVID-19/master/dati-andamento-nazionale/dpc-covid19-ita-andamento-nazionale.csv',\
              'regioni':'https://raw.githubusercontent.com/pcm-dpc/COVID-19/master/dati-regioni/dpc-covid19-ita-regioni.csv',\
              'province':'https://raw.githubusercontent.com/pcm-dpc/COVID-19/master/dati-province/dpc-covid19-ita-province.csv'}

-----------------

## National Trends

In [7]:
path_nazionale = data_links['nazionale']
print('The path to the Raw CSV file for the national data is : \n', path_nazionale)
df_nazionale = pd.read_csv(path_nazionale)
df_nazionale.head()

The path to the Raw CSV file for the national data is : 
 https://raw.githubusercontent.com/pcm-dpc/COVID-19/master/dati-andamento-nazionale/dpc-covid19-ita-andamento-nazionale.csv


data stato  ricoverati_con_sintomi  terapia_intensiva  \
0  2020-02-24T18:00:00   ITA                     101                 26   
1  2020-02-25T18:00:00   ITA                     114                 35   
2  2020-02-26T18:00:00   ITA                     128                 36   
3  2020-02-27T18:00:00   ITA                     248                 56   
4  2020-02-28T18:00:00   ITA                     345                 64   

   totale_ospedalizzati  isolamento_domiciliare  totale_positivi  \
0                   127                      94              221   
1                   150                     162              311   
2                   164                     221              385   
3                   304                     284              588   
4                   409                     412              821   

   variazione_totale_positivi  nuovi_positivi  dimessi_guariti  deceduti  \
0                           0             221                1         7   
1                          90              93                1        10   
2                          74              78                3        12   
3                         203             250               45        17   
4                         233             238               46        21   

   totale_casi  tamponi  casi_testati note_it note_en  
0          229     4324           NaN     NaN     NaN  
1          322     8623           NaN     NaN     NaN  
2          400     9587           NaN     NaN     NaN  
3          650    12014           NaN     NaN     NaN  
4          888    15695           NaN     NaN     NaN

In [8]:
df_nazionale.shape

(120, 16)

------------

### Date Formatting

In [9]:
time_date = df_nazionale['data']
time_date.head()

0    2020-02-24T18:00:00
1    2020-02-25T18:00:00
2    2020-02-26T18:00:00
3    2020-02-27T18:00:00
4    2020-02-28T18:00:00
Name: data, dtype: object

In [10]:
time_date_new = pd.to_datetime(time_date).dt.date
time_date_new.head()

0    2020-02-24
1    2020-02-25
2    2020-02-26
3    2020-02-27
4    2020-02-28
Name: data, dtype: object

In [11]:
time_date_new = datetime(time_date_new)
time_date_new

array(['2020-02-24', '2020-02-25', '2020-02-26', '2020-02-27',
       '2020-02-28', '2020-02-29', '2020-03-01', '2020-03-02',
       '2020-03-03', '2020-03-04', '2020-03-05', '2020-03-06',
       '2020-03-07', '2020-03-08', '2020-03-09', '2020-03-10',
       '2020-03-11', '2020-03-12', '2020-03-13', '2020-03-14',
       '2020-03-15', '2020-03-16', '2020-03-17', '2020-03-18',
       '2020-03-19', '2020-03-20', '2020-03-21', '2020-03-22',
       '2020-03-23', '2020-03-24', '2020-03-25', '2020-03-26',
       '2020-03-27', '2020-03-28', '2020-03-29', '2020-03-30',
       '2020-03-31', '2020-04-01', '2020-04-02', '2020-04-03',
       '2020-04-04', '2020-04-05', '2020-04-06', '2020-04-07',
       '2020-04-08', '2020-04-09', '2020-04-10', '2020-04-11',
       '2020-04-12', '2020-04-13', '2020-04-14', '2020-04-15',
       '2020-04-16', '2020-04-17', '2020-04-18', '2020-04-19',
       '2020-04-20', '2020-04-21', '2020-04-22', '2020-04-23',
       '2020-04-24', '2020-04-25', '2020-04-26', '2020-

-----------

In [12]:
time_date_new_extended = pd.date_range(start=time_date_new[0], periods=2*time_date.shape[0])
time_date_new_extended

DatetimeIndex(['2020-02-24', '2020-02-25', '2020-02-26', '2020-02-27',
               '2020-02-28', '2020-02-29', '2020-03-01', '2020-03-02',
               '2020-03-03', '2020-03-04',
               ...
               '2020-10-11', '2020-10-12', '2020-10-13', '2020-10-14',
               '2020-10-15', '2020-10-16', '2020-10-17', '2020-10-18',
               '2020-10-19', '2020-10-20'],
              dtype='datetime64[ns]', length=240, freq='D')

In [13]:
time_date_new_extended[0:4]

DatetimeIndex(['2020-02-24', '2020-02-25', '2020-02-26', '2020-02-27'], dtype='datetime64[ns]', freq='D')

------------------

### Total Cases

In [14]:
total_cases_italy = df_nazionale['totale_casi']
total_cases_italy.head()

0    229
1    322
2    400
3    650
4    888
Name: totale_casi, dtype: int64

### Total Positive

In [15]:
total_positive_italy = df_nazionale['totale_positivi']
total_positive_italy.head()

0    221
1    311
2    385
3    588
4    821
Name: totale_positivi, dtype: int64

-------------------------

In [16]:
p_total_cases_Italy = bokeh_plot_1_line(x=time_date_new, y=total_cases_italy, 
                  title='Total Cases: Italy', 
                  file_name="total_cases_Italy.html", 
                  x_label='Date', 
                  y_label='Total Cases', legend='total cases',
                  x_label_hover='date', y_label_hover='total cases',
                  color='blue', y_minmax=None)

show(p_total_cases_Italy)

In [17]:
p_total_cases_positive_Italy = bokeh_plot_2_lines(x=time_date_new, y=total_cases_italy, yy=total_positive_italy, 
                  title='Total Cases vs Total Positive: Italy', 
                  file_name="total_cases_positive_Italy.html", 
                  x_label='Date', y_label='Total Cases & Total Positive', 
                  legend_1='total cases', legend_2='total positive',
                  x_label_hover='date' , y_label_hover='total cases OR positive' , 
                  color_1='blue', color_2='firebrick', y_minmax=None)

show(p_total_cases_positive_Italy)

In [18]:
p_total_cases_positive_2_Italy = bokeh_plot_N_lines(x=time_date_new, y_list=[total_cases_italy,total_positive_italy], 
                  title='Total Cases & Total Positive: Italy', 
                  dim=[600, 450], 
                  x_label='Date', 
                  y_label='Total Cases & Total Positive', legend_list=['total cases','total positive'],
                  x_label_hover='date', y_label_hover='total cases OR total positive',
                  color_list=['blue','red'],legend_location="top_left", y_minmax=None)

output_file("total_cases_positive_2_Italy.html")

show(p_total_cases_positive_2_Italy)

------------------

### Deaths

In [19]:
deceduti_italy = df_nazionale['deceduti']
deceduti_italy.head()

0     7
1    10
2    12
3    17
4    21
Name: deceduti, dtype: int64

------------------

### Recovered

In [20]:
guariti_italy = df_nazionale['dimessi_guariti']
guariti_italy.head()

0     1
1     1
2     3
3    45
4    46
Name: dimessi_guariti, dtype: int64

In [21]:
p_deaths_recovered_Italy = bokeh_plot_2_lines(x=time_date_new, y=deceduti_italy, yy=guariti_italy, 
                  title='Deaths vs Recovered: Italy', 
                  file_name="deaths_recovered_Italy.html", 
                  x_label='Date', y_label='Deaths & Recovered', 
                  legend_1='deaths', legend_2='recovered',
                  x_label_hover='date' , y_label_hover='deaths OR recovered' , 
                  color_1='darkviolet', color_2='green', y_minmax=None)

show(p_deaths_recovered_Italy)

------------------

### New Deaths

In [22]:
len(deceduti_italy)
    

120

In [23]:
nuovi_deceduti = [0]
i = 0
while (i < len(deceduti_italy)-1):
#     print(deceduti_italy.iloc[i + 1] - deceduti_italy.iloc[i])
    temp = deceduti_italy.iloc[i + 1] - deceduti_italy.iloc[i]
    nuovi_deceduti.append(temp)
    i = i + 1

In [24]:
p_new_deaths_Italy = bokeh_plot_1_line(x=time_date_new, y=nuovi_deceduti, 
                  title='New Deaths: Italy', 
                  file_name="new_deaths_Italy.html", 
                  x_label='Date', 
                  y_label='New Deaths', legend='new deaths',
                  x_label_hover='date', y_label_hover='new deaths',
                  color='darkviolet', y_minmax=None)

show(p_new_deaths_Italy)

In [25]:
nuovi_deceduti_df = pd.DataFrame(nuovi_deceduti)

SMA_new_deaths = nuovi_deceduti_df[:].rolling(window=7).mean()
SMA_new_deaths_2 = nuovi_deceduti_df[:].rolling(window=10).mean()

In [26]:
SMA_new_deaths.head()

0
0 NaN
1 NaN
2 NaN
3 NaN
4 NaN

In [27]:
p_new_deaths_SMA_Italy = bokeh_plot_2_lines(x=time_date_new, y=nuovi_deceduti, yy=SMA_new_deaths[0], 
                  title='New Deaths: Italy', 
                  file_name="new_deaths_SMA_Italy.html", 
                  x_label='Date', y_label='New Deaths', 
                  legend_1='new deaths', legend_2='SMA 7 days',
                  x_label_hover='date' , y_label_hover='new deaths OR SMA 7' , 
                  color_1='darkviolet', color_2='lightblue', y_minmax=None)

show(p_new_deaths_SMA_Italy)

------------------

### New Positive

In [28]:
nuovi_positivi_italy = df_nazionale['nuovi_positivi']
nuovi_positivi_italy.head()

0    221
1     93
2     78
3    250
4    238
Name: nuovi_positivi, dtype: int64

In [29]:
p_new_positive_Italy = bokeh_plot_1_line(x=time_date_new, y=nuovi_positivi_italy, 
                  title='New Positive: Italy', 
                  file_name="new_positive_Italy.html", 
                  x_label='Date', 
                  y_label='New Positive', legend='new positive',
                  x_label_hover='date', y_label_hover='new positive',
                  color='blue', y_minmax=None)

show(p_new_positive_Italy)

In [30]:
new_positive_df = pd.DataFrame(nuovi_positivi_italy)

SMA_new_positive = new_positive_df[:].rolling(window=7).mean()
SMA_new_positive_2 = new_positive_df[:].rolling(window=10).mean()

In [31]:
SMA_new_positive.head()

nuovi_positivi
0             NaN
1             NaN
2             NaN
3             NaN
4             NaN

In [32]:
p_new_positive_SMA_Italy = bokeh_plot_2_lines(x=time_date_new, y=nuovi_positivi_italy, yy=SMA_new_positive['nuovi_positivi'], 
                  title='New Positive: Italy', 
                  file_name="new_positive_SMA_Italy.html", 
                  x_label='Date', y_label='New Positive', 
                  legend_1='new positive', legend_2='SMA 7 days',
                  x_label_hover='date' , y_label_hover='new_positive OR SMA 7' , 
                  color_1='blue', color_2='lightcoral', y_minmax=None)

show(p_new_positive_SMA_Italy)

------------------------

In [33]:
# show(row(p_new_positive_Italy,p_new_deaths_Italy))

In [34]:
p_new_deaths_positive_Italy = bokeh_plot_2_lines(x=time_date_new, y=nuovi_deceduti, yy=nuovi_positivi_italy, 
                  title='New Deaths vs New Positive: Italy', 
                  file_name="new_deaths_positive_Italy.html", 
                  x_label='Date', y_label='New Deaths & New Positive', 
                  legend_1='new deaths', legend_2='new positive',
                  x_label_hover='date' , y_label_hover='new deaths OR new positive' , 
                  color_1='darkviolet', color_2='blue', y_minmax=None)

show(p_new_deaths_positive_Italy)

---------------------

### Total Hospitalized

In [35]:
total_hospital_italy = df_nazionale['totale_ospedalizzati']
total_hospital_italy.head()

0    127
1    150
2    164
3    304
4    409
Name: totale_ospedalizzati, dtype: int64

---------------------

### Intensive Care

In [36]:
intensive_care_italy = df_nazionale['terapia_intensiva']
intensive_care_italy.head()

0    26
1    35
2    36
3    56
4    64
Name: terapia_intensiva, dtype: int64

In [37]:
p_total_hospitalized_Italy = bokeh_plot_1_line(x=time_date_new, y=total_hospital_italy, 
                  title='Total Hospitalized: Italy', 
                  file_name="total_hospitalized_Italy.html", 
                  x_label='Date', 
                  y_label='Total Hospitalized', legend='total hospitalized',
                  x_label_hover='date', y_label_hover='total hospitalized',
                  color='orange', y_minmax=None)
# output_file("total_cases_Italy.html")
show(p_total_hospitalized_Italy)

In [38]:
p_intensive_care_Italy = bokeh_plot_1_line(x=time_date_new, y=intensive_care_italy, 
                  title='Intensive Care: Italy', 
                  file_name="intensive_care_Italy.html", 
                  x_label='Date', 
                  y_label='Intensive Care', legend='intensive care',
                  x_label_hover='date', y_label_hover='intensive care',
                  color='GoldenRod', y_minmax=None)
# output_file("total_cases_Italy.html")
show(p_intensive_care_Italy)

In [39]:
p_hospitalized_intensivecare_Italy = bokeh_plot_2_lines(x=time_date_new, y=total_hospital_italy, yy=intensive_care_italy, 
                  title='Total Hospitalized vs Intensive Care: Italy', 
                  file_name="hospitalized_intensivecare_Italy.html", 
                  x_label='Date', y_label='Total Hospitalized & Intensive Care', 
                  legend_1='total hospitalized', legend_2='intensive care',
                  x_label_hover='date' , y_label_hover='hospitalized OR intensive care' , 
                  color_1='orange', color_2='GoldenRod', y_minmax=None)

show(p_hospitalized_intensivecare_Italy)

----------

-------------------------
# Fitting

In [40]:
from scipy.optimize import curve_fit
from scipy.special import gamma

def model_exp(x,a,b):
    return a * np.exp(b * x)

def model_population(x,K,r,P_0):
    den = 1 + ((K - P_0) / P_0) * np.exp(- r * x)
    return K / den

def model_Gamma_distribution(x,alpha,beta,Kmax):
    return Kmax * np.abs(beta)**(np.abs(alpha) + 1) * x**(np.abs(alpha)) * np.exp(- np.abs(beta) * x) / gamma((np.abs(alpha) + 1))

------------------

### ----- Exponential Fitting -----

In [41]:
fit_range = 28   # best fit when fit_range = 28 namely March 22
xdata = np.linspace(0, fit_range, fit_range)
init_guess = [5000, 0.001]
fit = curve_fit(model_exp, xdata, total_cases_italy.loc[0:(fit_range-1)], p0=init_guess)
ans, cov = fit
fit_a, fit_b = ans
fit_a, fit_b

(1268.6044974646502, 0.13890844390214907)

In [42]:
cov

array([[ 9.92195154e+03, -3.07812476e-01],
       [-3.07812476e-01,  9.74343219e-06]])

In [43]:
np.sqrt(np.diag(cov))

array([9.96089933e+01, 3.12144713e-03])

In [44]:
ydata = model_exp(xdata,fit_a,fit_b)
ydata

array([ 1268.60449746,  1465.16912064,  1692.1905577 ,  1954.38795648,
        2257.21167574,  2606.95658312,  3010.89290796,  3477.41736932,
        4016.22772053,  4638.52433861,  5357.24304922,  6187.32402664,
        7146.02235868,  8253.26673226,  9532.07369566, 11009.02610895,
       12714.82572808, 14684.9314095 , 16960.29620175, 19588.21864602,
       22623.32598204, 26128.70969733, 30177.23702472, 34853.06565057,
       40253.3931204 , 46490.47730694, 53693.96994092, 62013.61171197])

In [45]:
pfit_total_cases_Italy = bokeh_plot_2_lines(x=time_date_new[0:(fit_range)], y=total_cases_italy.loc[0:(fit_range-1)], yy=ydata[0:fit_range], 
                  title='Exponential Fitting Total Cases: Italy', 
                  file_name="fit_total_cases_Italy.html", 
                  x_label='Date', y_label='Total Cases', 
                  legend_1='total cases', legend_2='exponential fitting',
                  x_label_hover='date' , y_label_hover='total cases OR fitting' , 
                  color_1='blue', color_2='red', y_minmax=None)

show(pfit_total_cases_Italy)

In [46]:
- cov[0,1] / (np.sqrt(np.diag(cov)[0] * np.diag(cov)[1])) # Correlation coefficient for parameters 'a' and 'b'

0.9899919975413152

In [47]:
residuals = total_cases_italy.loc[0:(fit_range-1)] - ydata  #  Calculation of R^2
ss_res = np.sum(residuals**2)
ss_tot = np.sum((total_cases_italy.loc[0:(fit_range-1)] - np.mean(total_cases_italy.loc[0:(fit_range-1)]))**2)
r_squared = 1 - (ss_res / ss_tot)
r_squared

0.9942027803878379

---------------

In [48]:
fit_range = 49   # best fit when fit_range = 28 namely March 22
xdata = np.linspace(0, fit_range, fit_range)
init_guess = [5000, 0.001]
fit = curve_fit(model_exp, xdata, total_cases_italy.loc[0:(fit_range-1)], p0=init_guess)
ans, cov = fit
fit_a, fit_b = ans
fit_a, fit_b

(10273.505399700898, 0.058660707522345125)

In [49]:
cov

array([[ 1.70490033e+06, -3.88568817e+00],
       [-3.88568817e+00,  9.19880384e-06]])

In [50]:
np.sqrt(np.diag(cov))

array([1.30571832e+03, 3.03295299e-03])

In [51]:
ydata = model_exp(xdata,fit_a,fit_b)
ydata

array([ 10273.5053997 ,  10907.50512106,  11580.63030457,  12295.29546516,
        13054.06412256,  13859.65799674,  14714.96677074,  15623.05845605,
        16587.19039764,  17610.82095811,  18697.62192291,  19851.49167117,
        21076.56915918,  22377.24876699,  23758.19606113,  25224.3645301 ,
        26781.01335261,  28433.72626244,  30188.43157735,  32051.42346413,
        34029.38451587,  36129.40972262,  38359.03192126,  40726.24881594,
        43239.55166602,  45907.95574442,  48741.03267559,  51748.94476916,
        54942.48147235,  58333.09807195,  61932.95678471,  65754.97038346,
        69812.84851553,  74121.14687954,  78695.31943703,  83551.77384615,
        88707.93031628,  94182.28409475,  99994.47180965, 106165.34190689,
       112717.02943402, 119673.03543912, 127058.3112696 , 134899.34807324,
       143224.27182249, 152062.94420302, 161447.06972815, 171410.30946374,
       181988.4017711 ])

In [52]:
- cov[0,1] / (np.sqrt(np.diag(cov)[0] * np.diag(cov)[1])) # Correlation coefficient for parameters 'a' and 'b'

0.9811892216342538

In [53]:
residuals = total_cases_italy.loc[0:(fit_range-1)] - ydata  #  Calculation of R^2
ss_res = np.sum(residuals**2)
ss_tot = np.sum((total_cases_italy.loc[0:(fit_range-1)] - np.mean(total_cases_italy.loc[0:(fit_range-1)]))**2)
r_squared = 1 - (ss_res / ss_tot)
r_squared

0.940258800232746

In [54]:
pfit_total_cases_Italy = bokeh_plot_2_lines(x=time_date_new[0:(fit_range)], y=total_cases_italy.loc[0:(fit_range-1)], yy=ydata[0:fit_range], 
                  title='Exponential Fitting Total Cases: Italy', 
                  file_name="fit_total_cases_Italy.html", 
                  x_label='Date', y_label='Total Cases', 
                  legend_1='total cases', legend_2='exponential fitting',
                  x_label_hover='date' , y_label_hover='total cases OR fitting' , 
                  color_1='blue', color_2='red', y_minmax=None)

show(pfit_total_cases_Italy)

------------------------

------------------------

In [55]:
R_2_cases = []
Correlation_A_B = []
iii = 7

while(iii <= len(total_cases_italy)):
    fit_range = iii   # best fit when fit_range = 28 namely March 22
    xdata = np.linspace(0, fit_range, fit_range)
    init_guess = [5000, 0.001]
    fit = curve_fit(model_exp, xdata, total_cases_italy.loc[0:(fit_range-1)], p0=init_guess)
    ans, cov = fit
    fit_a, fit_b = ans
    fit_a, fit_b
    ydata = model_exp(xdata,fit_a,fit_b)
    residuals = total_cases_italy.loc[0:(fit_range-1)] - ydata  #  Calculation of R^2
    ss_res = np.sum(residuals**2)
    ss_tot = np.sum((total_cases_italy.loc[0:(fit_range-1)] - np.mean(total_cases_italy.loc[0:(fit_range-1)]))**2)
    r_squared = 1 - (ss_res / ss_tot)
    R_2_cases.append(r_squared)
    correlation_ab = - cov[0,1] / (np.sqrt(np.diag(cov)[0] * np.diag(cov)[1]))
    Correlation_A_B.append(correlation_ab)
    iii = iii + 1

In [56]:
p_total_cases_exp_val_Italy = bokeh_plot_N_lines(x=time_date_new + 6, y_list=[R_2_cases, Correlation_A_B], 
                  title='Total Cases Exponential Validity: Italy', 
                  dim=[600, 450], 
                  x_label='Date', 
                  y_label='R_squared', legend_list=['R_squared', 'Corr_A_B'],
                  x_label_hover='date', y_label_hover='R_squared/Corr_A_B',
                  color_list=['blue', 'lightblue'],legend_location="top_right", y_minmax=None)

output_file("total_cases_exponential_validity_Italy.html")

show(p_total_cases_exp_val_Italy)

--------------------

In [57]:
R_2_deaths = []
Correlation_A_B = []
iii = 7

while(iii <= len(deceduti_italy)):
    fit_range = iii   # best fit when fit_range = 28 namely March 22
    xdata = np.linspace(0, fit_range, fit_range)
    init_guess = [5000, 0.001]
    fit = curve_fit(model_exp, xdata, deceduti_italy.loc[0:(fit_range-1)], p0=init_guess)
    ans, cov = fit
    fit_a, fit_b = ans
    fit_a, fit_b
    ydata = model_exp(xdata,fit_a,fit_b)
    residuals = deceduti_italy.loc[0:(fit_range-1)] - ydata  #  Calculation of R^2
    ss_res = np.sum(residuals**2)
    ss_tot = np.sum((deceduti_italy.loc[0:(fit_range-1)] - np.mean(deceduti_italy.loc[0:(fit_range-1)]))**2)
    r_squared = 1 - (ss_res / ss_tot)
    R_2_deaths.append(r_squared)
    correlation_ab = - cov[0,1] / (np.sqrt(np.diag(cov)[0] * np.diag(cov)[1]))
    Correlation_A_B.append(correlation_ab)
    iii = iii + 1

In [58]:
p_total_deaths_exp_val_Italy = bokeh_plot_N_lines(x=time_date_new + 6, y_list=[R_2_deaths, Correlation_A_B], 
                  title='Total Deaths Exponential Validity: Italy', 
                  dim=[600, 450], 
                  x_label='Date', 
                  y_label='R_squared', legend_list=['R_squared', 'Corr_A_B'],
                  x_label_hover='date', y_label_hover='R_squared/Corr_A_B',
                  color_list=['darkviolet', 'violet'],legend_location="top_right", y_minmax=None)

output_file("total_deaths_exponential_validity_Italy.html")

show(p_total_deaths_exp_val_Italy)

-----------------

In [59]:
p_total_cases_deaths_exp_val_Italy = bokeh_plot_N_lines(x=time_date_new + 6, y_list=[R_2_cases, R_2_deaths], 
                  title='Total Cases/Deaths Exponential Validity: Italy', 
                  dim=[600, 450], 
                  x_label='Date', 
                  y_label='R_squared', legend_list=['R_squared_cases', 'R_squared_deaths'],
                  x_label_hover='date', y_label_hover='R_squared_cases/deaths',
                  color_list=['blue', 'darkviolet'],legend_location="top_right", y_minmax=None)

output_file("total_cases_deaths_exponential_validity_Italy.html")

show(p_total_cases_deaths_exp_val_Italy)

--------------------

In [60]:
R_2_guariti = []
Correlation_A_B = []
iii = 7

while(iii <= len(guariti_italy)):
    fit_range = iii   # best fit when fit_range = 28 namely March 22
    xdata = np.linspace(0, fit_range, fit_range)
    init_guess = [5000, 0.001]
    fit = curve_fit(model_exp, xdata, guariti_italy.loc[0:(fit_range-1)], p0=init_guess)
    ans, cov = fit
    fit_a, fit_b = ans
    fit_a, fit_b
    ydata = model_exp(xdata,fit_a,fit_b)
    residuals = guariti_italy.loc[0:(fit_range-1)] - ydata  #  Calculation of R^2
    ss_res = np.sum(residuals**2)
    ss_tot = np.sum((guariti_italy.loc[0:(fit_range-1)] - np.mean(guariti_italy.loc[0:(fit_range-1)]))**2)
    r_squared = 1 - (ss_res / ss_tot)
    R_2_guariti.append(r_squared)
    correlation_ab = - cov[0,1] / (np.sqrt(np.diag(cov)[0] * np.diag(cov)[1]))
    Correlation_A_B.append(correlation_ab)
    iii = iii + 1

In [61]:
p_guariti_exp_val_Italy = bokeh_plot_N_lines(x=time_date_new + 6, y_list=[R_2_guariti, Correlation_A_B], 
                  title='Guariti Exponential Validity: Italy', 
                  dim=[600, 450], 
                  x_label='Date', 
                  y_label='R_squared', legend_list=['R_squared', 'Corr_A_B'],
                  x_label_hover='date', y_label_hover='R_squared/Corr_A_B',
                  color_list=['green', 'lightgreen'],legend_location="bottom_right", y_minmax=None)

output_file("guariti_exponential_validity_Italy.html")

show(p_guariti_exp_val_Italy)

----------------------

In [62]:
p_total_cases_deaths_guariti_exp_val_Italy = bokeh_plot_N_lines(x=time_date_new + 6, y_list=[R_2_cases, R_2_deaths, R_2_guariti], 
                  title='Total Cases/Deaths/Guariti Exponential Validity: Italy', 
                  dim=[600, 450], 
                  x_label='Date', 
                  y_label='R_squared', legend_list=['R_squared_cases', 'R_squared_deaths', 'R_squared_guariti'],
                  x_label_hover='date', y_label_hover='R_squared_cases/deaths/guariti',
                  color_list=['blue', 'darkviolet', 'green'],legend_location="bottom_right", y_minmax=None)

output_file("total_cases_deaths_guariti_exponential_validity_Italy.html")

show(p_total_cases_deaths_guariti_exp_val_Italy)

--------------------------

----------------------

--------------------------

### -----  Logistic Fitting -----

In [63]:
fit_range_1 = len(total_cases_italy)
xdata_1 = np.linspace(0, fit_range_1, fit_range_1)
init_guess = [500000, 0.10, 100]
fit = curve_fit(model_population, xdata_1, total_cases_italy.loc[0:(fit_range_1-1)], p0 = init_guess)
ans, cov = fit
fit_K, fit_r, fit_P_0 = ans
fit_K, fit_r, fit_P_0

(232189.33865794973, 0.08851519308180396, 6370.021398753944)

In [64]:
cov

array([[ 1.07925679e+06, -9.65258370e-01,  1.84867110e+05],
       [-9.65258370e-01,  3.45326167e-06, -8.13647982e-01],
       [ 1.84867110e+05, -8.13647982e-01,  2.09896233e+05]])

In [65]:
np.sqrt(np.diag(cov))

array([1.03887285e+03, 1.85829537e-03, 4.58144336e+02])

In [66]:
ydata_1 = model_population(xdata_1, fit_K, fit_r, fit_P_0)
ydata_1

array([  6370.02139875,   6946.95700661,   7574.39325169,   8256.42113397,
         8997.40146573,   9801.97094787,  10675.04585495,  11621.82273319,
        12647.77543859,  13758.64776374,  14960.44082716,  16259.39433004,
        17661.96072914,  19174.77133668,  20804.59334695,  22558.27681312,
        24442.69066789,  26464.64700764,  28630.81305365,  30947.61047617,
        33421.10212579,  36056.86666904,  38859.86217081,  41834.28030182,
        44983.39356027,  48309.398661  ,  51813.26002794,  55494.55808257,
        59351.3476949 ,  63380.03269185,  67575.26263185,  71929.85808693,
        76434.77036694,  81079.08093259,  85850.04465788,  90733.17963264,
        95712.40439267, 100770.22141641, 105887.94355302, 111045.95789404,
       116224.01962645, 121401.56676488, 126558.04548844, 131673.23520347,
       136727.5624694 , 141702.39355881, 146580.29662126, 151345.26608051,
       155982.90388198, 160480.55436466, 164827.39170268, 169014.46090084,
       173034.67511669, 1

In [67]:
pfit_1_total_cases_Italy = bokeh_plot_2_lines(x=time_date_new[0:(fit_range_1)], y=total_cases_italy.loc[0:(fit_range_1-1)], yy=ydata_1[0:fit_range_1], 
                  title='Logistic Fitting Total Cases: Italy', 
                  file_name="fit_1_total_cases_Italy.html", 
                  x_label='Date', y_label='Total Cases', 
                  legend_1='total cases', legend_2='logistic fitting',
                  x_label_hover='date' , y_label_hover='total cases OR fitting' , 
                  color_1='blue', color_2='red', y_minmax=None)

show(pfit_1_total_cases_Italy)

In [68]:
- cov[0,1] / (np.sqrt(np.diag(cov)[0] * np.diag(cov)[1])) # Correlation coefficient for parameters 'K' and 'r'

0.4999958921289637

In [69]:
cov[0,2] / (np.sqrt(np.diag(cov)[0] * np.diag(cov)[2])) # Correlation coefficient for parameters 'K' and 'P_0'

0.3884140528822232

In [70]:
- cov[1,2] / (np.sqrt(np.diag(cov)[1] * np.diag(cov)[2])) # Correlation coefficient for parameters 'r' and 'P_0'

0.9556953770060476

In [71]:
residuals_1 = total_cases_italy.loc[0:(fit_range_1-1)] - ydata_1  #  Calculation of R^2
ss_res_1 = np.sum(residuals_1**2)
ss_tot_1 = np.sum((total_cases_italy.loc[0:(fit_range_1-1)] - np.mean(total_cases_italy.loc[0:(fit_range_1-1)]))**2)
r_squared_1 = 1 - (ss_res_1 / ss_tot_1)
r_squared_1

0.9946483454728706

----------------------

In [72]:
fit_range_2 = len(total_cases_italy) - 15
fit_range_3 = len(total_cases_italy)
xdata_2 = np.linspace(fit_range_2, fit_range_3, fit_range_3 - fit_range_2)
# init_guess = [250000,0.25,1]
init_guess = [500000,0.001,0]
fit = curve_fit(model_population, xdata_2, total_cases_italy.loc[fit_range_2:(fit_range_3-1)], p0=init_guess, maxfev=20000)

/Users/Angelo/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:8: RuntimeWarning: divide by zero encountered in double_scalars
  


In [73]:
ans, cov = fit

In [74]:
fit_K, fit_r, fit_P_0 = ans
fit_K, fit_r, fit_P_0

(242547.56092989797, 0.044560598840147424, 55559.15948577285)

In [75]:
cov

array([[ 2.26698079e+06, -1.82448636e+01,  6.97924058e+07],
       [-1.82448636e+01,  1.48109353e-04, -5.67733800e+02],
       [ 6.97924058e+07, -5.67733800e+02,  2.17734992e+09]])

In [76]:
np.sqrt(np.diag(cov))

array([1.50564962e+03, 1.21700186e-02, 4.66620823e+04])

In [77]:
ydata_2 = fit_K / ( 1 + ((fit_K - fit_P_0) / fit_P_0) * np.exp(- fit_r * xdata_2))
ydata_2

array([235194.2755793 , 235527.17546933, 235845.43369599, 236149.65610014,
       236440.42685145, 236718.30891337, 236983.84452926, 237237.55572594,
       237479.94483055, 237711.49499774, 237932.67074384, 238143.91848553,
       238345.66708036, 238538.32836716, 238722.29770417])

In [78]:
pfit_2_total_cases_Italy = bokeh_plot_2_lines(x=time_date_new[fit_range_2:fit_range_3], y=total_cases_italy.loc[(fit_range_2):(fit_range_3-1)], yy=ydata_2, 
                  title='Logistic Fitting Total Cases: Italy', 
                  file_name="fit_2_total_cases_Italy.html", 
                  x_label='Date', y_label='Total Cases', 
                  legend_1='total cases', legend_2='logistic fitting',
                  x_label_hover='date' , y_label_hover='total cases OR logistic' , 
                  color_1='blue', color_2='red', y_minmax=None)

show(pfit_2_total_cases_Italy)

In [79]:
- cov[0,1] / (np.sqrt(np.diag(cov)[0] * np.diag(cov)[1])) # Correlation coefficient for parameters 'K' and 'r'

0.9956930099270167

In [80]:
cov[0,2] / (np.sqrt(np.diag(cov)[0] * np.diag(cov)[2])) # Correlation coefficient for parameters 'K' and 'P_0'

0.9933908005588908

In [81]:
- cov[1,2] / (np.sqrt(np.diag(cov)[1] * np.diag(cov)[2])) # Correlation coefficient for parameters 'r' and 'P_0'

0.9997453514710559

In [82]:
residuals_2 = total_cases_italy.loc[(fit_range_2):(fit_range_3-1)] - ydata_2  #  Calculation of R^2
ss_res_2 = np.sum(residuals_2**2)
ss_tot_2 = np.sum((total_cases_italy.loc[(fit_range_2):(fit_range_3-1)] - np.mean(total_cases_italy.loc[(fit_range_2):(fit_range_3-1)]))**2)
r_squared_2 = 1 - (ss_res_2 / ss_tot_2)
r_squared_2

0.9927190741107296

---------------

In [83]:
max_population = []
max_population_up = []
max_population_down = []

# iii = len(total_cases_italy)
iii = 15

while (iii <= len(total_cases_italy)):
    fit_range_2 = iii - 15
    fit_range_3 = iii
    xdata_2 = np.linspace(fit_range_2, fit_range_3, fit_range_3 - fit_range_2)
    init_guess = [500000,0.001,0]
    fit = curve_fit(model_population, xdata_2, total_cases_italy.loc[fit_range_2:(fit_range_3-1)], p0=init_guess, maxfev=10000)
    ans, cov = fit
    fit_K, fit_r, fit_P_0 = ans
    max_population.append(fit_K)
    max_population_up.append(fit_K + np.sqrt(np.diag(cov))[0])
    max_population_down.append(fit_K - np.sqrt(np.diag(cov))[0])
    iii = iii + 1

/Users/Angelo/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:8: RuntimeWarning: divide by zero encountered in double_scalars
  


In [84]:
len(max_population)

106

In [126]:
p_new_positive_MAX_Italy = bokeh_plot_1_line(x=time_date_new + 14, y=max_population, 
                  title='Total Cases MAX: Italy', 
                  file_name="total_cases_MAX_Italy.html", 
                  x_label='Date', 
                  y_label='Total Cases MAX', legend='total cases max',
                  x_label_hover='date', y_label_hover='total cases max',
                  color='blue', y_minmax=(0,300000))

show(p_new_positive_MAX_Italy)

In [127]:
p_new_positive_MAX_2_Italy = bokeh_plot_N_lines(x=time_date_new + 14, y_list=[max_population,max_population_up,max_population_down], 
                  title='Total Cases MAX: Italy', 
                  dim=[600, 450], 
                  x_label='Date', 
                  y_label='Total Cases MAX', legend_list=['total cases max','total cases max UP','total cases max DOWN'],
                  x_label_hover='date', y_label_hover='total cases max/UP/DOWN',
                  color_list=['blue','lightcoral','lightblue'],legend_location="top_left", y_minmax=(0,300000))

output_file("total_cases_MAX_2_Italy.html")

show(p_new_positive_MAX_2_Italy)

---------------

---------------

---------------

In [87]:
fit_range_3 = len(deceduti_italy) - 15
fit_range_4 = len(deceduti_italy)
xdata_3 = np.linspace(fit_range_3, fit_range_4, fit_range_4 - fit_range_3)
init_guess = [80000,0.001,0.001]
fit = curve_fit(model_population, xdata_3, deceduti_italy.loc[fit_range_3:(fit_range_4-1)], p0=init_guess)

/Users/Angelo/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:8: RuntimeWarning: overflow encountered in exp
  


In [88]:
ans, cov = fit
fit_K, fit_r, fit_P_0 = ans
fit_K, fit_r, fit_P_0

(35283.93612344877, 0.0510736152090655, 3826.7301954419004)

In [89]:
cov

array([[ 2.52548435e+04, -1.35623688e+00,  4.25482010e+05],
       [-1.35623688e+00,  7.36700387e-05, -2.31649456e+01],
       [ 4.25482010e+05, -2.31649456e+01,  7.28753071e+06]])

In [90]:
np.sqrt(np.diag(cov))

array([1.58917726e+02, 8.58312523e-03, 2.69954269e+03])

In [91]:
ydata_3 = fit_K / ( 1 + ((fit_K - fit_P_0) / fit_P_0) * np.exp(- fit_r * xdata_3))
ydata_3

array([33974.6242901 , 34041.89269045, 34105.82489051, 34166.57429742,
       34224.28848236, 34279.10927531, 34331.17287357, 34380.60996179,
       34427.54584152, 34472.10056857, 34514.38909647, 34554.52142475,
       34592.60275048, 34628.73362228, 34663.01009543])

In [92]:
pfit_total_deaths_Italy = bokeh_plot_2_lines(x=time_date_new[fit_range_3:fit_range_4], y=deceduti_italy.loc[(fit_range_3):(fit_range_4-1)], yy=ydata_3, 
                  title='Logistic Fitting Total Deaths: Italy', 
                  file_name="fit_total_deaths_Italy.html", 
                  x_label='Date', y_label='Total Deaths', 
                  legend_1='total deaths', legend_2='logistic fitting',
                  x_label_hover='date' , y_label_hover='total deaths OR logistic' , 
                  color_1='darkviolet', color_2='violet', y_minmax=None)

show(pfit_total_deaths_Italy)

In [93]:
- cov[0,1] / (np.sqrt(np.diag(cov)[0] * np.diag(cov)[1])) # Correlation coefficient for parameters 'K' and 'r'

0.9943007315157968

In [94]:
cov[0,2] / (np.sqrt(np.diag(cov)[0] * np.diag(cov)[2])) # Correlation coefficient for parameters 'K' and 'P_0'

0.9917875726056393

In [95]:
- cov[1,2] / (np.sqrt(np.diag(cov)[1] * np.diag(cov)[2])) # Correlation coefficient for parameters 'r' and 'P_0'

0.9997597243949787

In [96]:
residuals_3 = deceduti_italy.loc[(fit_range_3):(fit_range_4-1)] - ydata_3  #  Calculation of R^2
ss_res_3 = np.sum(residuals_3**2)
ss_tot_3 = np.sum((deceduti_italy.loc[(fit_range_3):(fit_range_4-1)] - np.mean(deceduti_italy.loc[(fit_range_3):(fit_range_4-1)]))**2)
r_squared_3 = 1 - (ss_res_3 / ss_tot_3)
r_squared_3

0.9963921049172241

---------------

In [97]:
max_deaths = []
max_deaths_up = []
max_deaths_down = []

# iii = len(deceduti_italy)
iii = 15

while (iii <= len(deceduti_italy)):
    fit_range_3 = iii - 15
    fit_range_4 = iii
    xdata_3 = np.linspace(fit_range_3, fit_range_4, fit_range_4 - fit_range_3)
    init_guess = [80000,0.001,0.001]
    fit = curve_fit(model_population, xdata_3, deceduti_italy.loc[fit_range_3:(fit_range_4-1)], p0=init_guess)
    ans, cov = fit
    fit_K, fit_r, fit_P_0 = ans
    max_deaths.append(fit_K)
    max_deaths_up.append(fit_K + np.sqrt(np.diag(cov))[0])
    max_deaths_down.append(fit_K - np.sqrt(np.diag(cov))[0])
    iii = iii + 1

/Users/Angelo/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:8: RuntimeWarning: overflow encountered in exp
  


In [98]:
len(max_deaths)

106

In [99]:
p_total_deaths_MAX_Italy = bokeh_plot_1_line(x=time_date_new + 14, y=max_deaths, 
                  title='Total Deaths MAX: Italy', 
                  file_name="total_deaths_MAX_Italy.html", 
                  x_label='Date', 
                  y_label='Total Deaths MAX', legend='total deaths max',
                  x_label_hover='date', y_label_hover='total deaths max',
                  color='darkviolet', y_minmax=None)

show(p_total_deaths_MAX_Italy)

In [100]:
p_total_deaths_MAX_2_Italy = bokeh_plot_N_lines(x=time_date_new + 14, y_list=[max_deaths,max_deaths_up,max_deaths_down], 
                  title='Total Deaths MAX: Italy', 
                  dim=[600, 450], 
                  x_label='Date', 
                  y_label='Total Deaths MAX', legend_list=['total deaths max','total deaths max UP','total deaths max DOWN'],
                  x_label_hover='date', y_label_hover='total deaths max/UP/DOWN',
                  color_list=['darkviolet','lightcoral','lightblue'],legend_location="bottom_right", y_minmax=None)

output_file("total_deaths_MAX_2_Italy.html")

show(p_total_deaths_MAX_2_Italy)

------------------

------------------

------------------

### ----- Gamma Distribution Fitting -----

In [101]:
fit_range_5 = len(nuovi_positivi_italy)   
xdata_4 = np.linspace(1, fit_range_5, fit_range_5)
# init_guess = [1,0.15,20000]
# init_guess = [6,1,500000]
fit = curve_fit(model_Gamma_distribution, xdata_4, nuovi_positivi_italy.loc[0:(fit_range_5-1)])
ans, cov = fit
fit_alpha, fit_beta, fit_Kmax = ans
fit_alpha, fit_beta, fit_Kmax

/Users/Angelo/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:12: RuntimeWarning: overflow encountered in multiply
  if sys.path[0] == '':
/Users/Angelo/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:12: RuntimeWarning: invalid value encountered in multiply
  if sys.path[0] == '':


(3.6351419395548885, -0.10723714791575695, 234561.72784310268)

In [102]:
cov

array([[ 3.30544520e-02, -8.57496723e-04, -4.41071745e+02],
       [-8.57496723e-04,  2.36407001e-05,  1.29690525e+01],
       [-4.41071745e+02,  1.29690525e+01,  2.13509780e+07]])

In [103]:
np.sqrt(np.diag(cov))

array([1.81808834e-01, 4.86217031e-03, 4.62071185e+03])

In [104]:
ydata_4 = model_Gamma_distribution(xdata_4,fit_alpha,fit_beta,fit_Kmax)
ydata_4

array([4.79802669e-01, 5.35521511e+00, 2.10049252e+01, 5.36931248e+01,
       1.08549501e+02, 1.89186611e+02, 2.97631559e+02, 4.34425626e+02,
       5.98810785e+02, 7.88954732e+02, 1.00218493e+03, 1.23521384e+03,
       1.48434495e+03, 1.74565425e+03, 2.01514499e+03, 2.28887558e+03,
       2.56306201e+03, 2.83415672e+03, 3.09890652e+03, 3.35439214e+03,
       3.59805203e+03, 3.82769314e+03, 4.04149077e+03, 4.23797991e+03,
       4.41603977e+03, 4.57487340e+03, 4.71398361e+03, 4.83314661e+03,
       4.93238433e+03, 5.01193623e+03, 5.07223133e+03, 5.11386103e+03,
       5.13755303e+03, 5.14414673e+03, 5.13457038e+03, 5.10981992e+03,
       5.07093985e+03, 5.01900593e+03, 4.95510978e+03, 4.88034542e+03,
       4.79579746e+03, 4.70253101e+03, 4.60158324e+03, 4.49395626e+03,
       4.38061145e+03, 4.26246492e+03, 4.14038415e+03, 4.01518553e+03,
       3.88763282e+03, 3.75843634e+03, 3.62825282e+03, 3.49768586e+03,
       3.36728678e+03, 3.23755599e+03, 3.10894455e+03, 2.98185614e+03,
      

In [105]:
pfit_new_positive_Italy = bokeh_plot_2_lines(x=time_date_new, y=nuovi_positivi_italy.loc[0:(fit_range_5-1)], yy=ydata_4[0:fit_range_5], 
                  title='Gamma Distribution Fitting New Positive: Italy', 
                  file_name="fit_new_positive_Italy.html", 
                  x_label='Date', y_label='New Positive', 
                  legend_1='total cases', legend_2='Gamma fitting',
                  x_label_hover='date' , y_label_hover='new positive OR fitting' , 
                  color_1='blue', color_2='red', y_minmax=None)

show(pfit_new_positive_Italy)

In [106]:
- cov[0,1] / (np.sqrt(np.diag(cov)[0] * np.diag(cov)[1])) # Correlation coefficient for parameters 'alpha' and 'beta'

0.9700348136993037

In [107]:
cov[0,2] / (np.sqrt(np.diag(cov)[0] * np.diag(cov)[2])) # Correlation coefficient for parameters 'alpha' and 'Kmax'

-0.5250315114268537

In [108]:
- cov[1,2] / (np.sqrt(np.diag(cov)[1] * np.diag(cov)[2])) # Correlation coefficient for parameters 'beta' and 'Kmax'

-0.5772569803535004

In [109]:
residuals_4 = nuovi_positivi_italy.loc[0:(fit_range_5-1)] - ydata_4  #  Calculation of R^2
ss_res_4 = np.sum(residuals_4**2)
ss_tot_4 = np.sum((nuovi_positivi_italy.loc[0:(fit_range_5-1)] - np.mean(nuovi_positivi_italy.loc[0:(fit_range_5-1)]))**2)
r_squared_4 = 1 - (ss_res_4 / ss_tot_4)
r_squared_4

0.936845626961644

----------------

In [110]:
fit_range_6 = time_date_new_extended.shape[0]
xdata_5 = np.linspace(1, fit_range_6, fit_range_6)
ydata_5 = model_Gamma_distribution(xdata_5,fit_alpha,fit_beta,fit_Kmax)
ydata_5

array([4.79802669e-01, 5.35521511e+00, 2.10049252e+01, 5.36931248e+01,
       1.08549501e+02, 1.89186611e+02, 2.97631559e+02, 4.34425626e+02,
       5.98810785e+02, 7.88954732e+02, 1.00218493e+03, 1.23521384e+03,
       1.48434495e+03, 1.74565425e+03, 2.01514499e+03, 2.28887558e+03,
       2.56306201e+03, 2.83415672e+03, 3.09890652e+03, 3.35439214e+03,
       3.59805203e+03, 3.82769314e+03, 4.04149077e+03, 4.23797991e+03,
       4.41603977e+03, 4.57487340e+03, 4.71398361e+03, 4.83314661e+03,
       4.93238433e+03, 5.01193623e+03, 5.07223133e+03, 5.11386103e+03,
       5.13755303e+03, 5.14414673e+03, 5.13457038e+03, 5.10981992e+03,
       5.07093985e+03, 5.01900593e+03, 4.95510978e+03, 4.88034542e+03,
       4.79579746e+03, 4.70253101e+03, 4.60158324e+03, 4.49395626e+03,
       4.38061145e+03, 4.26246492e+03, 4.14038415e+03, 4.01518553e+03,
       3.88763282e+03, 3.75843634e+03, 3.62825282e+03, 3.49768586e+03,
       3.36728678e+03, 3.23755599e+03, 3.10894455e+03, 2.98185614e+03,
      

In [111]:
pfit_2_new_positive_Italy = bokeh_plot_2_lines(x=time_date_new_extended, y=nuovi_positivi_italy.loc[0:(fit_range_5-1)], yy=ydata_5[0:fit_range_6], 
                  title='Gamma Distribution Fitting New Positive Extended: Italy', 
                  file_name="fit_2_new_positive_Italy.html", 
                  x_label='Date', y_label='New Positive', 
                  legend_1='total cases', legend_2='Gamma fitting',
                  x_label_hover='date' , y_label_hover='new positive OR fitting' , 
                  color_1='blue', color_2='red', y_minmax=None)

show(pfit_2_new_positive_Italy)

In [112]:
pfit_3_new_positive_Italy = bokeh_plot_N_lines(x=time_date_new_extended, y_list=[nuovi_positivi_italy.loc[0:(fit_range_5-1)],ydata_5[0:fit_range_6],SMA_new_positive['nuovi_positivi']], 
                  title='Gamma Distribution Fitting New Positive Extended: Italy', 
                  dim=[600, 450],
                  x_label='Date', 
                  y_label='New Positive', legend_list=['new positive','Gamma fitting','SMA 7 days'],
                  x_label_hover='date', y_label_hover='new positive/fitting/SMA 7',
                  color_list=['blue','red','lightblue'],legend_location="top_right", y_minmax=None)

output_file("fit_3_new_positive_Italy.html")

show(pfit_3_new_positive_Italy)

-----------------

------------

In [113]:
fit_range_7 = len(nuovi_deceduti)   
xdata_8 = np.linspace(1, fit_range_7, fit_range_7)
# init_guess = [1,0.15,20000]
fit = curve_fit(model_Gamma_distribution, xdata_8, nuovi_deceduti[0:(fit_range_7)])
ans, cov = fit
fit_alpha, fit_beta, fit_Kmax = ans
fit_alpha, fit_beta, fit_Kmax

/Users/Angelo/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:12: RuntimeWarning: overflow encountered in double_scalars
  if sys.path[0] == '':
/Users/Angelo/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:12: RuntimeWarning: overflow encountered in power
  if sys.path[0] == '':
/Users/Angelo/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:12: RuntimeWarning: invalid value encountered in multiply
  if sys.path[0] == '':
/Users/Angelo/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:12: RuntimeWarning: invalid value encountered in true_divide
  if sys.path[0] == '':


(4.310638889324073, -0.11251485834283081, 34021.91909652614)

In [114]:
cov

array([[ 5.29882125e-02, -1.23999770e-03, -8.90014524e+01],
       [-1.23999770e-03,  3.05713792e-05,  2.31782652e+00],
       [-8.90014524e+01,  2.31782652e+00,  5.26341021e+05]])

In [115]:
np.sqrt(np.diag(cov))

array([2.30191686e-01, 5.52913910e-03, 7.25493640e+02])

In [116]:
ydata_8 = model_Gamma_distribution(xdata_8,fit_alpha,fit_beta,fit_Kmax)
ydata_8

array([7.18253252e-03, 1.27363394e-01, 6.53500422e-01, 2.01812038e+00,
       4.71874551e+00, 9.25302493e+00, 1.60695082e+01, 2.55340876e+01,
       3.79101773e+01, 5.33501017e+01, 7.18951489e+01, 9.34819678e+01,
       1.17953315e+02, 1.45071505e+02, 1.74533248e+02, 2.05984857e+02,
       2.39037071e+02, 2.73278951e+02, 3.08290488e+02, 3.43653710e+02,
       3.78962181e+02, 4.13828875e+02, 4.47892470e+02, 4.80822151e+02,
       5.12321046e+02, 5.42128438e+02, 5.70020891e+02, 5.95812449e+02,
       6.19354052e+02, 6.40532315e+02, 6.59267783e+02, 6.75512806e+02,
       6.89249114e+02, 7.00485209e+02, 7.09253633e+02, 7.15608204e+02,
       7.19621256e+02, 7.21380953e+02, 7.20988689e+02, 7.18556629e+02,
       7.14205400e+02, 7.08061944e+02, 7.00257553e+02, 6.90926087e+02,
       6.80202373e+02, 6.68220783e+02, 6.55113995e+02, 6.41011915e+02,
       6.26040764e+02, 6.10322316e+02, 5.93973272e+02, 5.77104766e+02,
       5.59821986e+02, 5.42223907e+02, 5.24403109e+02, 5.06445691e+02,
      

In [117]:
pfit_new_deaths_Italy = bokeh_plot_2_lines(x=time_date_new, y=nuovi_deceduti[0:(fit_range_7)], yy=ydata_8[0:fit_range_7], 
                  title='Gamma Distribution Fitting New Deaths: Italy', 
                  file_name="fit_new_deaths_Italy.html", 
                  x_label='Date', y_label='New Deaths', 
                  legend_1='new deaths', legend_2='Gamma fitting',
                  x_label_hover='date' , y_label_hover='new deaths OR fitting' , 
                  color_1='darkviolet', color_2='red', y_minmax=None)

show(pfit_new_deaths_Italy)

In [118]:
- cov[0,1] / (np.sqrt(np.diag(cov)[0] * np.diag(cov)[1])) # Correlation coefficient for parameters 'alpha' and 'beta'

0.9742574370467488

In [119]:
cov[0,2] / (np.sqrt(np.diag(cov)[0] * np.diag(cov)[2])) # Correlation coefficient for parameters 'alpha' and 'Kmax'

-0.5329345173783216

In [120]:
- cov[1,2] / (np.sqrt(np.diag(cov)[1] * np.diag(cov)[2])) # Correlation coefficient for parameters 'beta' and 'Kmax'

-0.5778163180353003

In [121]:
residuals_8 = nuovi_deceduti[0:(fit_range_7)] - ydata_8  #  Calculation of R^2
ss_res_8 = np.sum(residuals_8**2)
ss_tot_8 = np.sum((nuovi_deceduti[0:(fit_range_7)] - np.mean(nuovi_deceduti[0:(fit_range_7)]))**2)
r_squared_8 = 1 - (ss_res_8 / ss_tot_8)
r_squared_8

0.9237566987599579

-----------

In [122]:
fit_range_8 = time_date_new_extended.shape[0]
xdata_9 = np.linspace(1, fit_range_8, fit_range_8)
ydata_9 = model_Gamma_distribution(xdata_9,fit_alpha,fit_beta,fit_Kmax)
ydata_9

array([7.18253252e-03, 1.27363394e-01, 6.53500422e-01, 2.01812038e+00,
       4.71874551e+00, 9.25302493e+00, 1.60695082e+01, 2.55340876e+01,
       3.79101773e+01, 5.33501017e+01, 7.18951489e+01, 9.34819678e+01,
       1.17953315e+02, 1.45071505e+02, 1.74533248e+02, 2.05984857e+02,
       2.39037071e+02, 2.73278951e+02, 3.08290488e+02, 3.43653710e+02,
       3.78962181e+02, 4.13828875e+02, 4.47892470e+02, 4.80822151e+02,
       5.12321046e+02, 5.42128438e+02, 5.70020891e+02, 5.95812449e+02,
       6.19354052e+02, 6.40532315e+02, 6.59267783e+02, 6.75512806e+02,
       6.89249114e+02, 7.00485209e+02, 7.09253633e+02, 7.15608204e+02,
       7.19621256e+02, 7.21380953e+02, 7.20988689e+02, 7.18556629e+02,
       7.14205400e+02, 7.08061944e+02, 7.00257553e+02, 6.90926087e+02,
       6.80202373e+02, 6.68220783e+02, 6.55113995e+02, 6.41011915e+02,
       6.26040764e+02, 6.10322316e+02, 5.93973272e+02, 5.77104766e+02,
       5.59821986e+02, 5.42223907e+02, 5.24403109e+02, 5.06445691e+02,
      

In [123]:
pfit_2_new_deaths_Italy = bokeh_plot_2_lines(x=time_date_new_extended, y=nuovi_deceduti[0:(fit_range_7)], yy=ydata_9[0:fit_range_8], 
                  title='Gamma Distribution Fitting New Deaths Extended: Italy', 
                  file_name="fit_2_new_deaths_Italy.html", 
                  x_label='Date', y_label='New Deaths', 
                  legend_1='new deaths', legend_2='Gamma fitting',
                  x_label_hover='date' , y_label_hover='new deaths OR fitting' , 
                  color_1='darkviolet', color_2='red', y_minmax=None)

show(pfit_2_new_deaths_Italy)

-----------------
-----------------
-----------------

In [136]:
s1_grid = bokeh_plot_N_lines(x=time_date_new, y_list=[total_cases_italy,total_positive_italy], 
                  title='Total Cases & Total Positive: Italy', 
                  dim=[470, 350], 
                  x_label='Date', 
                  y_label='Total Cases & Total Positive', legend_list=['total cases','total positive'],
                  x_label_hover='date', y_label_hover='total cases OR total positive',
                  color_list=['blue','red'],legend_location="top_left", y_minmax=None)

s2_grid = bokeh_plot_N_lines(x=time_date_new, y_list=[deceduti_italy,guariti_italy], 
                  title='Deaths & Recovered: Italy', 
                  dim=[470, 350], 
                  x_label='Date', 
                  y_label='Deaths & Recovered', legend_list=['deaths','recovered'],
                  x_label_hover='date', y_label_hover='deaths OR recovered',
                  color_list=['darkviolet','green'],legend_location="top_left", y_minmax=None)


s3_grid = bokeh_plot_N_lines(x=time_date_new + 6, y_list=[R_2_cases, R_2_deaths, R_2_guariti], 
                  title='Total Cases/Deaths/Guariti - Exponential Validity: Italy', 
                  dim=[470, 350], 
                  x_label='Date', 
                  y_label='R_squared', legend_list=['R_squared_cases', 'R_squared_deaths', 'R_squared_guariti'],
                  x_label_hover='date', y_label_hover='R_squared_cases/deaths/guariti',
                  color_list=['blue', 'darkviolet', 'green'], legend_location="bottom_left", y_minmax=None)

s4_grid = bokeh_plot_N_lines(x=time_date_new + 14, y_list=[max_population_up,max_population_down,max_population], 
                  title='Max Total Cases - Logistic Fitting: Italy', 
                  dim=[470, 350], 
                  x_label='Date', 
                  y_label='Total Cases MAX', legend_list=['total cases max UP','total cases max DOWN','total cases max'],
                  x_label_hover='date', y_label_hover='total cases max/UP/DOWN',
                  color_list=['lightcoral','lightblue','blue'],legend_location="bottom_right", y_minmax=(0,300000))

s5_grid = bokeh_plot_N_lines(x=time_date_new + 14, y_list=[max_deaths_up,max_deaths_down,max_deaths], 
                  title='Max Total Deaths - Logistic Fitting: Italy', 
                  dim=[470, 350], 
                  x_label='Date', 
                  y_label='Total Deaths MAX', legend_list=['total deaths max UP','total deaths max DOWN','total deaths max'],
                  x_label_hover='date', y_label_hover='total deaths max/UP/DOWN',
                  color_list=['lightcoral','lightblue','darkviolet'],legend_location="bottom_right", y_minmax=(0,45000))

s6_grid = bokeh_plot_N_lines(x=time_date_new_extended, y_list=[nuovi_positivi_italy.loc[0:(fit_range_5-1)],ydata_5[0:fit_range_6]], 
                  title='New Positive - Gamma Distribution Fitting: Italy', 
                  dim=[470, 350],
                  x_label='Date', 
                  y_label='New Positive', legend_list=['new positive','Gamma fitting'],
                  x_label_hover='date', y_label_hover='new positive/fitting',
                  color_list=['blue','lightcoral'],legend_location="top_right", y_minmax=None)

s7_grid = bokeh_plot_N_lines(x=time_date_new_extended, y_list=[nuovi_deceduti[0:(fit_range_7)],ydata_9[0:fit_range_8]], 
                  title='New Deaths - Gamma Distribution Fitting: Italy', 
                  dim=[470, 350],
                  x_label='Date', 
                  y_label='New Deaths', legend_list=['new deaths','Gamma fitting'],
                  x_label_hover='date', y_label_hover='new deaths/fitting',
                  color_list=['darkviolet','lightcoral'],legend_location="top_right", y_minmax=None)

In [137]:
p_grid = gridplot([[s1_grid, s2_grid, s3_grid], [s4_grid, s5_grid], [s6_grid, s7_grid]])

output_file("grid_1.html")

show(p_grid)