<h1 align=center><font size = 7>Italian Trends Covid-19</font></h1>

------------

<font size = 5> **Author**: Angelo Di Marco

------------

In this Notebook, we analyze the spreading of the new coronavirus in Italy.

## Libraries and Functions

First we import the required libraries and define the bokeh plot functions:

In [1]:
import numpy as np

import pandas as pd

from math import pi

from bokeh.plotting import figure, output_file, show, output_notebook, gridplot
from bokeh.models import DatetimeTickFormatter, BasicTickFormatter, NumeralTickFormatter
from bokeh.models import HoverTool
from bokeh.layouts import row

output_notebook()

Loading BokehJS ...

In [2]:
def datetime(x):
    return np.array(x, dtype=np.datetime64)

---------------------

### ----- Plot function 1 line -----

In [3]:
def bokeh_plot_1_line(x, y, title, file_name, x_label, y_label, legend, x_label_hover, y_label_hover, color, y_minmax):
    
    output_file(file_name)
    
    p = figure(title=title, x_axis_type='datetime', x_axis_label=x_label, y_axis_label=y_label, width=600, height=450, y_range=y_minmax)
    
    p.line(x.squeeze(), y, color=color, line_width=4, legend_label=legend)
    p.circle(x.squeeze(), y, fill_color="white", line_color=color, size=6)
    
    p.xaxis.formatter = DatetimeTickFormatter(
#         hours=["%d %B %Y"],
#         days=["%Y %m %d"],
        days=["%d %B"],
#         months=["%d %B %Y"],
#         years=["%d %B %Y"],
    )
    p.xaxis.major_label_orientation = pi/4
  
    p.yaxis.formatter = BasicTickFormatter(use_scientific = False)
#     p.left[0].formatter.use_scientific = False
    p.yaxis.formatter = NumeralTickFormatter(format = '0,0')
    
    p.axis.minor_tick_in = -5
    p.axis.minor_tick_out = -3
    
    p.legend.location = "top_left"
    
    p.add_tools(HoverTool(
    tooltips=[
        ( x_label_hover,   '@x{%d %B}'    ),
        ( y_label_hover, '@y{0.}'      ),
    ],

    formatters={
           '@x'  : 'datetime', # use 'datetime' formatter for 'date' field
#            '@y'  : 'printf',   # use 'printf' formatter for 'adj close' field
                                  # use default 'numeral' formatter for other fields
    },

    # display a tooltip whenever the cursor is vertically in line with a glyph
    mode='vline'
    ))

    return p
#     show(p)

### ----- Plot function 2 lines -----

In [4]:
def bokeh_plot_2_lines(x, y, yy, title, file_name, x_label, y_label, legend_1, legend_2, x_label_hover, y_label_hover, color_1, color_2, y_minmax):
    
    output_file(file_name)
    
    p = figure(title=title, x_axis_type='datetime', x_axis_label=x_label, y_axis_label=y_label, width=600, height=450, y_range=y_minmax)
    
    p.line(x, y, color=color_1, line_width=4, legend_label=legend_1)
    p.circle(x, y, fill_color="white", line_color=color_1, size=6)
    
    p.line(x, yy, color=color_2, line_width=4, legend_label=legend_2)
    p.circle(x, yy, fill_color="white", line_color=color_2, size=6)
    
    p.xaxis.formatter=DatetimeTickFormatter(
#         hours=["%d %B %Y"],
#         days=["%Y %m %d"],
    days=["%d %B"],
#         months=["%d %B %Y"],
#         years=["%d %B %Y"],
    )
    p.xaxis.major_label_orientation = pi/4
  
    p.yaxis.formatter = BasicTickFormatter(use_scientific=False)
#     p.left[0].formatter.use_scientific = False
    p.yaxis.formatter = NumeralTickFormatter(format = '0,0')
    
    p.axis.minor_tick_in = -5
    p.axis.minor_tick_out = -3
    
    p.legend.location = "top_left"
    
    p.add_tools(HoverTool(
    tooltips=[
        ( x_label_hover,   '@x{%d %B}' ),
        ( y_label_hover, '@y{0.}' ),
#         ( 'label yy', '@yy' ),
    ],

    formatters={
           '@x'  : 'datetime', # use 'datetime' formatter for 'date' field
#            '@y'  : 'printf',   # use 'printf' formatter for 'adj close' field
                                  # use default 'numeral' formatter for other fields
    },

    # display a tooltip whenever the cursor is vertically in line with a glyph
    mode='vline'
    ))
    
    return p  
#     show(p)

### ----- Plot function N lines -----

In [5]:
def bokeh_plot_N_lines(x, y_list, title, dim, x_label, y_label, legend_list, x_label_hover, y_label_hover, color_list, legend_location, y_minmax):
    
#     output_file(file_name)
    
    p = figure(title=title, x_axis_type='datetime', x_axis_label=x_label, y_axis_label=y_label, width=dim[0], height=dim[1], y_range=y_minmax)
    
    for iii in range(0,len(y_list)):
        p.line(x, y_list[iii], color=color_list[iii], line_width=4, legend_label=legend_list[iii])
        p.circle(x, y_list[iii], fill_color="white", line_color=color_list[iii], size=5)
        
    
    p.xaxis.formatter=DatetimeTickFormatter(
#         hours=["%d %B %Y"],
#         days=["%Y %m %d"],
    days=["%d %B"],
#         months=["%d %B %Y"],
#         years=["%d %B %Y"],
    )
    p.xaxis.major_label_orientation = pi/4
  
    p.yaxis.formatter = BasicTickFormatter(use_scientific=False)
#     p.left[0].formatter.use_scientific = False
#     p.yaxis.formatter = NumeralTickFormatter(format = '0,0')
    p.yaxis.formatter.use_scientific = False
    
    p.axis.minor_tick_in = -5
    p.axis.minor_tick_out = -3
    
    p.legend.location = legend_location
    
    p.add_tools(HoverTool(
    tooltips=[
        ( x_label_hover,   '@x{%d %B}' ),
        ( y_label_hover, '@y{0[.]000}' ),
#         ( 'label yy', '@yy' ),
    ],

    formatters={
           '@x'  : 'datetime', # use 'datetime' formatter for 'date' field
#            '@y'  : 'printf',   # use 'printf' formatter for 'adj close' field
#            '@y'  : 'numeral',   # use 'printf' formatter for 'adj close' field
                                  # use default 'numeral' formatter for other fields
    },

    # display a tooltip whenever the cursor is vertically in line with a glyph
    mode='vline'
    ))
    
    return p  
#     show(p)

-----------------

## Data Sources

We importe the CSV files directly from the official GitHub source of the Protezione Civile:

In [6]:
data_links = {'nazionale':'https://raw.githubusercontent.com/pcm-dpc/COVID-19/master/dati-andamento-nazionale/dpc-covid19-ita-andamento-nazionale.csv',\
              'regioni':'https://raw.githubusercontent.com/pcm-dpc/COVID-19/master/dati-regioni/dpc-covid19-ita-regioni.csv',\
              'province':'https://raw.githubusercontent.com/pcm-dpc/COVID-19/master/dati-province/dpc-covid19-ita-province.csv'}

-----------------

## National Trends

In [7]:
path_nazionale = data_links['nazionale']
print('The path to the Raw CSV file for the national data is : \n', path_nazionale)
df_nazionale = pd.read_csv(path_nazionale)
df_nazionale.head()

The path to the Raw CSV file for the national data is : 
 https://raw.githubusercontent.com/pcm-dpc/COVID-19/master/dati-andamento-nazionale/dpc-covid19-ita-andamento-nazionale.csv


data stato  ricoverati_con_sintomi  terapia_intensiva  \
0  2020-02-24T18:00:00   ITA                     101                 26   
1  2020-02-25T18:00:00   ITA                     114                 35   
2  2020-02-26T18:00:00   ITA                     128                 36   
3  2020-02-27T18:00:00   ITA                     248                 56   
4  2020-02-28T18:00:00   ITA                     345                 64   

   totale_ospedalizzati  isolamento_domiciliare  totale_positivi  \
0                   127                      94              221   
1                   150                     162              311   
2                   164                     221              385   
3                   304                     284              588   
4                   409                     412              821   

   variazione_totale_positivi  nuovi_positivi  dimessi_guariti  deceduti  \
0                           0             221                1         7   
1                          90              93                1        10   
2                          74              78                3        12   
3                         203             250               45        17   
4                         233             238               46        21   

   casi_da_sospetto_diagnostico  casi_da_screening  totale_casi  tamponi  \
0                           NaN                NaN          229     4324   
1                           NaN                NaN          322     8623   
2                           NaN                NaN          400     9587   
3                           NaN                NaN          650    12014   
4                           NaN                NaN          888    15695   

   casi_testati note  
0           NaN  NaN  
1           NaN  NaN  
2           NaN  NaN  
3           NaN  NaN  
4           NaN  NaN

In [8]:
df_nazionale.shape

(130, 17)

------------

### Date Formatting

In [9]:
time_date = df_nazionale['data']
time_date.head()

0    2020-02-24T18:00:00
1    2020-02-25T18:00:00
2    2020-02-26T18:00:00
3    2020-02-27T18:00:00
4    2020-02-28T18:00:00
Name: data, dtype: object

In [10]:
time_date_new = pd.to_datetime(time_date).dt.date
time_date_new.head()

0    2020-02-24
1    2020-02-25
2    2020-02-26
3    2020-02-27
4    2020-02-28
Name: data, dtype: object

In [11]:
time_date_new = datetime(time_date_new)
time_date_new

array(['2020-02-24', '2020-02-25', '2020-02-26', '2020-02-27',
       '2020-02-28', '2020-02-29', '2020-03-01', '2020-03-02',
       '2020-03-03', '2020-03-04', '2020-03-05', '2020-03-06',
       '2020-03-07', '2020-03-08', '2020-03-09', '2020-03-10',
       '2020-03-11', '2020-03-12', '2020-03-13', '2020-03-14',
       '2020-03-15', '2020-03-16', '2020-03-17', '2020-03-18',
       '2020-03-19', '2020-03-20', '2020-03-21', '2020-03-22',
       '2020-03-23', '2020-03-24', '2020-03-25', '2020-03-26',
       '2020-03-27', '2020-03-28', '2020-03-29', '2020-03-30',
       '2020-03-31', '2020-04-01', '2020-04-02', '2020-04-03',
       '2020-04-04', '2020-04-05', '2020-04-06', '2020-04-07',
       '2020-04-08', '2020-04-09', '2020-04-10', '2020-04-11',
       '2020-04-12', '2020-04-13', '2020-04-14', '2020-04-15',
       '2020-04-16', '2020-04-17', '2020-04-18', '2020-04-19',
       '2020-04-20', '2020-04-21', '2020-04-22', '2020-04-23',
       '2020-04-24', '2020-04-25', '2020-04-26', '2020-

-----------

In [12]:
time_date_new_extended = pd.date_range(start=time_date_new[0], periods=2*time_date.shape[0])
time_date_new_extended

DatetimeIndex(['2020-02-24', '2020-02-25', '2020-02-26', '2020-02-27',
               '2020-02-28', '2020-02-29', '2020-03-01', '2020-03-02',
               '2020-03-03', '2020-03-04',
               ...
               '2020-10-31', '2020-11-01', '2020-11-02', '2020-11-03',
               '2020-11-04', '2020-11-05', '2020-11-06', '2020-11-07',
               '2020-11-08', '2020-11-09'],
              dtype='datetime64[ns]', length=260, freq='D')

In [13]:
time_date_new_extended[0:4]

DatetimeIndex(['2020-02-24', '2020-02-25', '2020-02-26', '2020-02-27'], dtype='datetime64[ns]', freq='D')

------------------

### Total Cases

In [14]:
total_cases_italy = df_nazionale['totale_casi']
total_cases_italy.head()

0    229
1    322
2    400
3    650
4    888
Name: totale_casi, dtype: int64

### Total Positive

In [15]:
total_positive_italy = df_nazionale['totale_positivi']
total_positive_italy.head()

0    221
1    311
2    385
3    588
4    821
Name: totale_positivi, dtype: int64

-------------------------

In [16]:
p_total_cases_Italy = bokeh_plot_1_line(x=time_date_new, y=total_cases_italy, 
                  title='Total Cases: Italy', 
                  file_name="total_cases_Italy.html", 
                  x_label='Date', 
                  y_label='Total Cases', legend='total cases',
                  x_label_hover='date', y_label_hover='total cases',
                  color='blue', y_minmax=None)

show(p_total_cases_Italy)

In [17]:
p_total_cases_positive_Italy = bokeh_plot_2_lines(x=time_date_new, y=total_cases_italy, yy=total_positive_italy, 
                  title='Total Cases vs Total Positive: Italy', 
                  file_name="total_cases_positive_Italy.html", 
                  x_label='Date', y_label='Total Cases & Total Positive', 
                  legend_1='total cases', legend_2='total positive',
                  x_label_hover='date' , y_label_hover='total cases OR positive' , 
                  color_1='blue', color_2='firebrick', y_minmax=None)

show(p_total_cases_positive_Italy)

In [18]:
p_total_cases_positive_2_Italy = bokeh_plot_N_lines(x=time_date_new, y_list=[total_cases_italy,total_positive_italy], 
                  title='Total Cases & Total Positive: Italy', 
                  dim=[600, 450], 
                  x_label='Date', 
                  y_label='Total Cases & Total Positive', legend_list=['total cases','total positive'],
                  x_label_hover='date', y_label_hover='total cases OR total positive',
                  color_list=['blue','red'],legend_location="top_left", y_minmax=None)

output_file("total_cases_positive_2_Italy.html")

show(p_total_cases_positive_2_Italy)

------------------

### Deaths

In [19]:
deceduti_italy = df_nazionale['deceduti']
deceduti_italy.head()

0     7
1    10
2    12
3    17
4    21
Name: deceduti, dtype: int64

------------------

### Recovered

In [20]:
guariti_italy = df_nazionale['dimessi_guariti']
guariti_italy.head()

0     1
1     1
2     3
3    45
4    46
Name: dimessi_guariti, dtype: int64

In [21]:
p_deaths_recovered_Italy = bokeh_plot_2_lines(x=time_date_new, y=deceduti_italy, yy=guariti_italy, 
                  title='Deaths vs Recovered: Italy', 
                  file_name="deaths_recovered_Italy.html", 
                  x_label='Date', y_label='Deaths & Recovered', 
                  legend_1='deaths', legend_2='recovered',
                  x_label_hover='date' , y_label_hover='deaths OR recovered' , 
                  color_1='darkviolet', color_2='green', y_minmax=None)

show(p_deaths_recovered_Italy)

------------------

### New Deaths

In [22]:
len(deceduti_italy)
    

130

In [23]:
nuovi_deceduti = [0]
i = 0
while (i < len(deceduti_italy)-1):
#     print(deceduti_italy.iloc[i + 1] - deceduti_italy.iloc[i])
    temp = deceduti_italy.iloc[i + 1] - deceduti_italy.iloc[i]
    nuovi_deceduti.append(temp)
    i = i + 1

In [24]:
p_new_deaths_Italy = bokeh_plot_1_line(x=time_date_new, y=nuovi_deceduti, 
                  title='New Deaths: Italy', 
                  file_name="new_deaths_Italy.html", 
                  x_label='Date', 
                  y_label='New Deaths', legend='new deaths',
                  x_label_hover='date', y_label_hover='new deaths',
                  color='darkviolet', y_minmax=None)

show(p_new_deaths_Italy)

In [25]:
nuovi_deceduti_df = pd.DataFrame(nuovi_deceduti)

SMA_new_deaths = nuovi_deceduti_df[:].rolling(window=7).mean()
SMA_new_deaths_2 = nuovi_deceduti_df[:].rolling(window=10).mean()

In [26]:
SMA_new_deaths.head()

0
0 NaN
1 NaN
2 NaN
3 NaN
4 NaN

In [27]:
p_new_deaths_SMA_Italy = bokeh_plot_2_lines(x=time_date_new, y=nuovi_deceduti, yy=SMA_new_deaths[0], 
                  title='New Deaths: Italy', 
                  file_name="new_deaths_SMA_Italy.html", 
                  x_label='Date', y_label='New Deaths', 
                  legend_1='new deaths', legend_2='SMA 7 days',
                  x_label_hover='date' , y_label_hover='new deaths OR SMA 7' , 
                  color_1='darkviolet', color_2='lightblue', y_minmax=None)

show(p_new_deaths_SMA_Italy)

------------------

### New Positive

In [28]:
nuovi_positivi_italy = df_nazionale['nuovi_positivi']
nuovi_positivi_italy.head()

0    221
1     93
2     78
3    250
4    238
Name: nuovi_positivi, dtype: int64

In [29]:
p_new_positive_Italy = bokeh_plot_1_line(x=time_date_new, y=nuovi_positivi_italy, 
                  title='New Positive: Italy', 
                  file_name="new_positive_Italy.html", 
                  x_label='Date', 
                  y_label='New Positive', legend='new positive',
                  x_label_hover='date', y_label_hover='new positive',
                  color='blue', y_minmax=None)

show(p_new_positive_Italy)

In [30]:
new_positive_df = pd.DataFrame(nuovi_positivi_italy)

SMA_new_positive = new_positive_df[:].rolling(window=7).mean()
SMA_new_positive_2 = new_positive_df[:].rolling(window=10).mean()

In [31]:
SMA_new_positive.head()

nuovi_positivi
0             NaN
1             NaN
2             NaN
3             NaN
4             NaN

In [32]:
p_new_positive_SMA_Italy = bokeh_plot_2_lines(x=time_date_new, y=nuovi_positivi_italy, yy=SMA_new_positive['nuovi_positivi'], 
                  title='New Positive: Italy', 
                  file_name="new_positive_SMA_Italy.html", 
                  x_label='Date', y_label='New Positive', 
                  legend_1='new positive', legend_2='SMA 7 days',
                  x_label_hover='date' , y_label_hover='new_positive OR SMA 7' , 
                  color_1='blue', color_2='lightcoral', y_minmax=None)

show(p_new_positive_SMA_Italy)

------------------------

In [33]:
# show(row(p_new_positive_Italy,p_new_deaths_Italy))

In [34]:
p_new_deaths_positive_Italy = bokeh_plot_2_lines(x=time_date_new, y=nuovi_deceduti, yy=nuovi_positivi_italy, 
                  title='New Deaths vs New Positive: Italy', 
                  file_name="new_deaths_positive_Italy.html", 
                  x_label='Date', y_label='New Deaths & New Positive', 
                  legend_1='new deaths', legend_2='new positive',
                  x_label_hover='date' , y_label_hover='new deaths OR new positive' , 
                  color_1='darkviolet', color_2='blue', y_minmax=None)

show(p_new_deaths_positive_Italy)

---------------------

### Total Hospitalized

In [35]:
total_hospital_italy = df_nazionale['totale_ospedalizzati']
total_hospital_italy.head()

0    127
1    150
2    164
3    304
4    409
Name: totale_ospedalizzati, dtype: int64

---------------------

### Intensive Care

In [36]:
intensive_care_italy = df_nazionale['terapia_intensiva']
intensive_care_italy.head()

0    26
1    35
2    36
3    56
4    64
Name: terapia_intensiva, dtype: int64

In [37]:
p_total_hospitalized_Italy = bokeh_plot_1_line(x=time_date_new, y=total_hospital_italy, 
                  title='Total Hospitalized: Italy', 
                  file_name="total_hospitalized_Italy.html", 
                  x_label='Date', 
                  y_label='Total Hospitalized', legend='total hospitalized',
                  x_label_hover='date', y_label_hover='total hospitalized',
                  color='orange', y_minmax=None)
# output_file("total_cases_Italy.html")
show(p_total_hospitalized_Italy)

In [38]:
p_intensive_care_Italy = bokeh_plot_1_line(x=time_date_new, y=intensive_care_italy, 
                  title='Intensive Care: Italy', 
                  file_name="intensive_care_Italy.html", 
                  x_label='Date', 
                  y_label='Intensive Care', legend='intensive care',
                  x_label_hover='date', y_label_hover='intensive care',
                  color='GoldenRod', y_minmax=None)
# output_file("total_cases_Italy.html")
show(p_intensive_care_Italy)

In [39]:
p_hospitalized_intensivecare_Italy = bokeh_plot_2_lines(x=time_date_new, y=total_hospital_italy, yy=intensive_care_italy, 
                  title='Total Hospitalized vs Intensive Care: Italy', 
                  file_name="hospitalized_intensivecare_Italy.html", 
                  x_label='Date', y_label='Total Hospitalized & Intensive Care', 
                  legend_1='total hospitalized', legend_2='intensive care',
                  x_label_hover='date' , y_label_hover='hospitalized OR intensive care' , 
                  color_1='orange', color_2='GoldenRod', y_minmax=None)

show(p_hospitalized_intensivecare_Italy)

----------

-------------------------
# Fitting

In [40]:
from scipy.optimize import curve_fit
from scipy.special import gamma

def model_exp(x,a,b):
    return a * np.exp(b * x)

def model_population(x,K,r,P_0):
    den = 1 + ((K - P_0) / P_0) * np.exp(- r * x)
    return K / den

def model_Gamma_distribution(x,alpha,beta,Kmax):
    return Kmax * np.abs(beta)**(np.abs(alpha) + 1) * x**(np.abs(alpha)) * np.exp(- np.abs(beta) * x) / gamma((np.abs(alpha) + 1))

------------------

### ----- Exponential Fitting -----

In [41]:
fit_range = 28   # best fit when fit_range = 28 namely March 22
xdata = np.linspace(0, fit_range, fit_range)
init_guess = [5000, 0.001]
fit = curve_fit(model_exp, xdata, total_cases_italy.loc[0:(fit_range-1)], p0=init_guess)
ans, cov = fit
fit_a, fit_b = ans
fit_a, fit_b

(1268.6044974646502, 0.13890844390214907)

In [42]:
cov

array([[ 9.92195154e+03, -3.07812476e-01],
       [-3.07812476e-01,  9.74343219e-06]])

In [43]:
np.sqrt(np.diag(cov))

array([9.96089933e+01, 3.12144713e-03])

In [44]:
ydata = model_exp(xdata,fit_a,fit_b)
ydata

array([ 1268.60449746,  1465.16912064,  1692.1905577 ,  1954.38795648,
        2257.21167574,  2606.95658312,  3010.89290796,  3477.41736932,
        4016.22772053,  4638.52433861,  5357.24304922,  6187.32402664,
        7146.02235868,  8253.26673226,  9532.07369566, 11009.02610895,
       12714.82572808, 14684.9314095 , 16960.29620175, 19588.21864602,
       22623.32598204, 26128.70969733, 30177.23702472, 34853.06565057,
       40253.3931204 , 46490.47730694, 53693.96994092, 62013.61171197])

In [45]:
pfit_total_cases_Italy = bokeh_plot_2_lines(x=time_date_new[0:(fit_range)], y=total_cases_italy.loc[0:(fit_range-1)], yy=ydata[0:fit_range], 
                  title='Exponential Fitting Total Cases: Italy', 
                  file_name="fit_total_cases_Italy.html", 
                  x_label='Date', y_label='Total Cases', 
                  legend_1='total cases', legend_2='exponential fitting',
                  x_label_hover='date' , y_label_hover='total cases OR fitting' , 
                  color_1='blue', color_2='red', y_minmax=None)

show(pfit_total_cases_Italy)

In [46]:
- cov[0,1] / (np.sqrt(np.diag(cov)[0] * np.diag(cov)[1])) # Correlation coefficient for parameters 'a' and 'b'

0.9899919975413152

In [47]:
residuals = total_cases_italy.loc[0:(fit_range-1)] - ydata  #  Calculation of R^2
ss_res = np.sum(residuals**2)
ss_tot = np.sum((total_cases_italy.loc[0:(fit_range-1)] - np.mean(total_cases_italy.loc[0:(fit_range-1)]))**2)
r_squared = 1 - (ss_res / ss_tot)
r_squared

0.9942027803878379

---------------

In [48]:
fit_range = 49   # best fit when fit_range = 28 namely March 22
xdata = np.linspace(0, fit_range, fit_range)
init_guess = [5000, 0.001]
fit = curve_fit(model_exp, xdata, total_cases_italy.loc[0:(fit_range-1)], p0=init_guess)
ans, cov = fit
fit_a, fit_b = ans
fit_a, fit_b

(10273.505399700898, 0.058660707522345125)

In [49]:
cov

array([[ 1.70490033e+06, -3.88568817e+00],
       [-3.88568817e+00,  9.19880384e-06]])

In [50]:
np.sqrt(np.diag(cov))

array([1.30571832e+03, 3.03295299e-03])

In [51]:
ydata = model_exp(xdata,fit_a,fit_b)
ydata

array([ 10273.5053997 ,  10907.50512106,  11580.63030457,  12295.29546516,
        13054.06412256,  13859.65799674,  14714.96677074,  15623.05845605,
        16587.19039764,  17610.82095811,  18697.62192291,  19851.49167117,
        21076.56915918,  22377.24876699,  23758.19606113,  25224.3645301 ,
        26781.01335261,  28433.72626244,  30188.43157735,  32051.42346413,
        34029.38451587,  36129.40972262,  38359.03192126,  40726.24881594,
        43239.55166602,  45907.95574442,  48741.03267559,  51748.94476916,
        54942.48147235,  58333.09807195,  61932.95678471,  65754.97038346,
        69812.84851553,  74121.14687954,  78695.31943703,  83551.77384615,
        88707.93031628,  94182.28409475,  99994.47180965, 106165.34190689,
       112717.02943402, 119673.03543912, 127058.3112696 , 134899.34807324,
       143224.27182249, 152062.94420302, 161447.06972815, 171410.30946374,
       181988.4017711 ])

In [52]:
- cov[0,1] / (np.sqrt(np.diag(cov)[0] * np.diag(cov)[1])) # Correlation coefficient for parameters 'a' and 'b'

0.9811892216342538

In [53]:
residuals = total_cases_italy.loc[0:(fit_range-1)] - ydata  #  Calculation of R^2
ss_res = np.sum(residuals**2)
ss_tot = np.sum((total_cases_italy.loc[0:(fit_range-1)] - np.mean(total_cases_italy.loc[0:(fit_range-1)]))**2)
r_squared = 1 - (ss_res / ss_tot)
r_squared

0.940258800232746

In [54]:
pfit_total_cases_Italy = bokeh_plot_2_lines(x=time_date_new[0:(fit_range)], y=total_cases_italy.loc[0:(fit_range-1)], yy=ydata[0:fit_range], 
                  title='Exponential Fitting Total Cases: Italy', 
                  file_name="fit_total_cases_Italy.html", 
                  x_label='Date', y_label='Total Cases', 
                  legend_1='total cases', legend_2='exponential fitting',
                  x_label_hover='date' , y_label_hover='total cases OR fitting' , 
                  color_1='blue', color_2='red', y_minmax=None)

show(pfit_total_cases_Italy)

------------------------

------------------------

In [55]:
R_2_cases = []
Correlation_A_B = []
iii = 7

while(iii <= len(total_cases_italy)):
    fit_range = iii   # best fit when fit_range = 28 namely March 22
    xdata = np.linspace(0, fit_range, fit_range)
    init_guess = [5000, 0.001]
    fit = curve_fit(model_exp, xdata, total_cases_italy.loc[0:(fit_range-1)], p0=init_guess)
    ans, cov = fit
    fit_a, fit_b = ans
    fit_a, fit_b
    ydata = model_exp(xdata,fit_a,fit_b)
    residuals = total_cases_italy.loc[0:(fit_range-1)] - ydata  #  Calculation of R^2
    ss_res = np.sum(residuals**2)
    ss_tot = np.sum((total_cases_italy.loc[0:(fit_range-1)] - np.mean(total_cases_italy.loc[0:(fit_range-1)]))**2)
    r_squared = 1 - (ss_res / ss_tot)
    R_2_cases.append(r_squared)
    correlation_ab = - cov[0,1] / (np.sqrt(np.diag(cov)[0] * np.diag(cov)[1]))
    Correlation_A_B.append(correlation_ab)
    iii = iii + 1

In [56]:
p_total_cases_exp_val_Italy = bokeh_plot_N_lines(x=time_date_new + 6, y_list=[R_2_cases, Correlation_A_B], 
                  title='Total Cases Exponential Validity: Italy', 
                  dim=[600, 450], 
                  x_label='Date', 
                  y_label='R_squared', legend_list=['R_squared', 'Corr_A_B'],
                  x_label_hover='date', y_label_hover='R_squared/Corr_A_B',
                  color_list=['blue', 'lightblue'],legend_location="top_right", y_minmax=None)

output_file("total_cases_exponential_validity_Italy.html")

show(p_total_cases_exp_val_Italy)

--------------------

In [57]:
R_2_deaths = []
Correlation_A_B = []
iii = 7

while(iii <= len(deceduti_italy)):
    fit_range = iii   # best fit when fit_range = 28 namely March 22
    xdata = np.linspace(0, fit_range, fit_range)
    init_guess = [5000, 0.001]
    fit = curve_fit(model_exp, xdata, deceduti_italy.loc[0:(fit_range-1)], p0=init_guess)
    ans, cov = fit
    fit_a, fit_b = ans
    fit_a, fit_b
    ydata = model_exp(xdata,fit_a,fit_b)
    residuals = deceduti_italy.loc[0:(fit_range-1)] - ydata  #  Calculation of R^2
    ss_res = np.sum(residuals**2)
    ss_tot = np.sum((deceduti_italy.loc[0:(fit_range-1)] - np.mean(deceduti_italy.loc[0:(fit_range-1)]))**2)
    r_squared = 1 - (ss_res / ss_tot)
    R_2_deaths.append(r_squared)
    correlation_ab = - cov[0,1] / (np.sqrt(np.diag(cov)[0] * np.diag(cov)[1]))
    Correlation_A_B.append(correlation_ab)
    iii = iii + 1

In [58]:
p_total_deaths_exp_val_Italy = bokeh_plot_N_lines(x=time_date_new + 6, y_list=[R_2_deaths, Correlation_A_B], 
                  title='Total Deaths Exponential Validity: Italy', 
                  dim=[600, 450], 
                  x_label='Date', 
                  y_label='R_squared', legend_list=['R_squared', 'Corr_A_B'],
                  x_label_hover='date', y_label_hover='R_squared/Corr_A_B',
                  color_list=['darkviolet', 'violet'],legend_location="top_right", y_minmax=None)

output_file("total_deaths_exponential_validity_Italy.html")

show(p_total_deaths_exp_val_Italy)

-----------------

In [59]:
p_total_cases_deaths_exp_val_Italy = bokeh_plot_N_lines(x=time_date_new + 6, y_list=[R_2_cases, R_2_deaths], 
                  title='Total Cases/Deaths Exponential Validity: Italy', 
                  dim=[600, 450], 
                  x_label='Date', 
                  y_label='R_squared', legend_list=['R_squared_cases', 'R_squared_deaths'],
                  x_label_hover='date', y_label_hover='R_squared_cases/deaths',
                  color_list=['blue', 'darkviolet'],legend_location="top_right", y_minmax=None)

output_file("total_cases_deaths_exponential_validity_Italy.html")

show(p_total_cases_deaths_exp_val_Italy)

--------------------

In [60]:
R_2_guariti = []
Correlation_A_B = []
iii = 7

while(iii <= len(guariti_italy)):
    fit_range = iii   # best fit when fit_range = 28 namely March 22
    xdata = np.linspace(0, fit_range, fit_range)
    init_guess = [5000, 0.001]
    fit = curve_fit(model_exp, xdata, guariti_italy.loc[0:(fit_range-1)], p0=init_guess)
    ans, cov = fit
    fit_a, fit_b = ans
    fit_a, fit_b
    ydata = model_exp(xdata,fit_a,fit_b)
    residuals = guariti_italy.loc[0:(fit_range-1)] - ydata  #  Calculation of R^2
    ss_res = np.sum(residuals**2)
    ss_tot = np.sum((guariti_italy.loc[0:(fit_range-1)] - np.mean(guariti_italy.loc[0:(fit_range-1)]))**2)
    r_squared = 1 - (ss_res / ss_tot)
    R_2_guariti.append(r_squared)
    correlation_ab = - cov[0,1] / (np.sqrt(np.diag(cov)[0] * np.diag(cov)[1]))
    Correlation_A_B.append(correlation_ab)
    iii = iii + 1

In [61]:
p_guariti_exp_val_Italy = bokeh_plot_N_lines(x=time_date_new + 6, y_list=[R_2_guariti, Correlation_A_B], 
                  title='Guariti Exponential Validity: Italy', 
                  dim=[600, 450], 
                  x_label='Date', 
                  y_label='R_squared', legend_list=['R_squared', 'Corr_A_B'],
                  x_label_hover='date', y_label_hover='R_squared/Corr_A_B',
                  color_list=['green', 'lightgreen'],legend_location="bottom_right", y_minmax=None)

output_file("guariti_exponential_validity_Italy.html")

show(p_guariti_exp_val_Italy)

----------------------

In [62]:
p_total_cases_deaths_guariti_exp_val_Italy = bokeh_plot_N_lines(x=time_date_new + 6, y_list=[R_2_cases, R_2_deaths, R_2_guariti], 
                  title='Total Cases/Deaths/Guariti Exponential Validity: Italy', 
                  dim=[600, 450], 
                  x_label='Date', 
                  y_label='R_squared', legend_list=['R_squared_cases', 'R_squared_deaths', 'R_squared_guariti'],
                  x_label_hover='date', y_label_hover='R_squared_cases/deaths/guariti',
                  color_list=['blue', 'darkviolet', 'green'],legend_location="bottom_right", y_minmax=None)

output_file("total_cases_deaths_guariti_exponential_validity_Italy.html")

show(p_total_cases_deaths_guariti_exp_val_Italy)

--------------------------

----------------------

--------------------------

### -----  Logistic Fitting -----

In [63]:
fit_range_1 = len(total_cases_italy)
xdata_1 = np.linspace(0, fit_range_1, fit_range_1)
init_guess = [500000, 0.10, 100]
fit = curve_fit(model_population, xdata_1, total_cases_italy.loc[0:(fit_range_1-1)], p0 = init_guess)
ans, cov = fit
fit_K, fit_r, fit_P_0 = ans
fit_K, fit_r, fit_P_0

(233937.82198732585, 0.08697262405331835, 6673.776772437863)

In [64]:
cov

array([[ 8.95930302e+05, -7.87439584e-01,  1.58639156e+05],
       [-7.87439584e-01,  3.15829238e-06, -7.89676772e-01],
       [ 1.58639156e+05, -7.89676772e-01,  2.16739172e+05]])

In [65]:
np.sqrt(np.diag(cov))

array([9.46535948e+02, 1.77715851e-03, 4.65552545e+02])

In [66]:
ydata_1 = model_population(xdata_1, fit_K, fit_r, fit_P_0)
ydata_1

array([  6673.77677244,   7266.12353121,   7909.21570687,   8607.06386975,
         9363.9339286 ,  10184.35189323,  11073.10627324,  12035.24755808,
        13076.08415591,  14201.1741012 ,  15416.31177701,  16727.50884089,
        18140.96849865,  19663.05224304,  21300.23817202,  23059.07003118,
        24946.09619635,  26967.79793404,  29130.50645881,  31440.30855665,
        33902.94086875,  36523.67333564,  39307.18278706,  42257.41822458,
        45377.45996805,  48669.37550523,  52134.07556585,  55771.17459893,
        59578.86041857,  63553.77824395,  67690.93463778,  71983.62688622,
        76423.40311437,  81000.05785755,  85701.66689442,  90514.66390228,
        95423.9599577 , 100413.10514502, 105464.48965069, 110559.57983151,
       115679.18298168, 120803.73301981, 125913.58818962, 130989.33120965,
       136012.06217231, 140963.67489149, 145827.10829909, 150586.56581833,
       155227.69729035, 159737.73987351, 164105.61623804, 168321.99021555,
       172379.28172299, 1

In [67]:
pfit_1_total_cases_Italy = bokeh_plot_2_lines(x=time_date_new[0:(fit_range_1)], y=total_cases_italy.loc[0:(fit_range_1-1)], yy=ydata_1[0:fit_range_1], 
                  title='Logistic Fitting Total Cases: Italy', 
                  file_name="fit_1_total_cases_Italy.html", 
                  x_label='Date', y_label='Total Cases', 
                  legend_1='total cases', legend_2='logistic fitting',
                  x_label_hover='date' , y_label_hover='total cases OR fitting' , 
                  color_1='blue', color_2='red', y_minmax=None)

show(pfit_1_total_cases_Italy)

In [68]:
- cov[0,1] / (np.sqrt(np.diag(cov)[0] * np.diag(cov)[1])) # Correlation coefficient for parameters 'K' and 'r'

0.46811651594324616

In [69]:
cov[0,2] / (np.sqrt(np.diag(cov)[0] * np.diag(cov)[2])) # Correlation coefficient for parameters 'K' and 'P_0'

0.3600017166960959

In [70]:
- cov[1,2] / (np.sqrt(np.diag(cov)[1] * np.diag(cov)[2])) # Correlation coefficient for parameters 'r' and 'P_0'

0.9544528793987404

In [71]:
residuals_1 = total_cases_italy.loc[0:(fit_range_1-1)] - ydata_1  #  Calculation of R^2
ss_res_1 = np.sum(residuals_1**2)
ss_tot_1 = np.sum((total_cases_italy.loc[0:(fit_range_1-1)] - np.mean(total_cases_italy.loc[0:(fit_range_1-1)]))**2)
r_squared_1 = 1 - (ss_res_1 / ss_tot_1)
r_squared_1

0.9945162029516561

----------------------

In [72]:
fit_range_2 = len(total_cases_italy) - 15
fit_range_3 = len(total_cases_italy)
xdata_2 = np.linspace(fit_range_2, fit_range_3, fit_range_3 - fit_range_2)
# init_guess = [250000,0.25,1]
init_guess = [500000,0.001,0]
fit = curve_fit(model_population, xdata_2, total_cases_italy.loc[fit_range_2:(fit_range_3-1)], p0=init_guess, maxfev=20000)

/Users/Angelo/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:8: RuntimeWarning: divide by zero encountered in double_scalars
  


In [73]:
ans, cov = fit

In [74]:
fit_K, fit_r, fit_P_0 = ans
fit_K, fit_r, fit_P_0

(249621.3242224138, 0.021808124499130534, 155311.32106615425)

In [75]:
cov

array([[ 1.00992388e+08, -2.09133799e+02,  9.74202918e+08],
       [-2.09133799e+02,  4.33948863e-04, -2.02362828e+03],
       [ 9.74202918e+08, -2.02362828e+03,  9.44220481e+09]])

In [76]:
np.sqrt(np.diag(cov))

array([1.00494969e+04, 2.08314393e-02, 9.71710081e+04])

In [77]:
ydata_2 = fit_K / ( 1 + ((fit_K - fit_P_0) / fit_P_0) * np.exp(- fit_r * xdata_2))
ydata_2

array([237859.02444126, 238118.15621248, 238371.84912649, 238620.20554172,
       238863.32640795, 239101.31126187, 239334.25822405, 239562.26399714,
       239785.42386546, 240003.83169567, 240217.57993863, 240426.75963229,
       240631.46040562, 240831.77048351, 241027.77669254])

In [78]:
pfit_2_total_cases_Italy = bokeh_plot_2_lines(x=time_date_new[fit_range_2:fit_range_3], y=total_cases_italy.loc[(fit_range_2):(fit_range_3-1)], yy=ydata_2, 
                  title='Logistic Fitting Total Cases: Italy', 
                  file_name="fit_2_total_cases_Italy.html", 
                  x_label='Date', y_label='Total Cases', 
                  legend_1='total cases', legend_2='logistic fitting',
                  x_label_hover='date' , y_label_hover='total cases OR logistic' , 
                  color_1='blue', color_2='red', y_minmax=None)

show(pfit_2_total_cases_Italy)

In [79]:
- cov[0,1] / (np.sqrt(np.diag(cov)[0] * np.diag(cov)[1])) # Correlation coefficient for parameters 'K' and 'r'

0.9989888214532469

In [80]:
cov[0,2] / (np.sqrt(np.diag(cov)[0] * np.diag(cov)[2])) # Correlation coefficient for parameters 'K' and 'P_0'

0.9976274679777932

In [81]:
- cov[1,2] / (np.sqrt(np.diag(cov)[1] * np.diag(cov)[2])) # Correlation coefficient for parameters 'r' and 'P_0'

0.9997116520646981

In [82]:
residuals_2 = total_cases_italy.loc[(fit_range_2):(fit_range_3-1)] - ydata_2  #  Calculation of R^2
ss_res_2 = np.sum(residuals_2**2)
ss_tot_2 = np.sum((total_cases_italy.loc[(fit_range_2):(fit_range_3-1)] - np.mean(total_cases_italy.loc[(fit_range_2):(fit_range_3-1)]))**2)
r_squared_2 = 1 - (ss_res_2 / ss_tot_2)
r_squared_2

0.9785775455075724

---------------

In [83]:
max_population = []
max_population_up = []
max_population_down = []

# iii = len(total_cases_italy)
iii = 15

while (iii <= len(total_cases_italy)):
    fit_range_2 = iii - 15
    fit_range_3 = iii
    xdata_2 = np.linspace(fit_range_2, fit_range_3, fit_range_3 - fit_range_2)
    init_guess = [500000,0.001,0]
    fit = curve_fit(model_population, xdata_2, total_cases_italy.loc[fit_range_2:(fit_range_3-1)], p0=init_guess, maxfev=10000)
    ans, cov = fit
    fit_K, fit_r, fit_P_0 = ans
    max_population.append(fit_K)
    max_population_up.append(fit_K + np.sqrt(np.diag(cov))[0])
    max_population_down.append(fit_K - np.sqrt(np.diag(cov))[0])
    iii = iii + 1

/Users/Angelo/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:8: RuntimeWarning: divide by zero encountered in double_scalars
  


In [84]:
len(max_population)

116

In [85]:
p_new_positive_MAX_Italy = bokeh_plot_1_line(x=time_date_new + 14, y=max_population, 
                  title='Total Cases MAX: Italy', 
                  file_name="total_cases_MAX_Italy.html", 
                  x_label='Date', 
                  y_label='Total Cases MAX', legend='total cases max',
                  x_label_hover='date', y_label_hover='total cases max',
                  color='blue', y_minmax=(0,300000))

show(p_new_positive_MAX_Italy)

In [86]:
p_new_positive_MAX_2_Italy = bokeh_plot_N_lines(x=time_date_new + 14, y_list=[max_population,max_population_up,max_population_down], 
                  title='Total Cases MAX: Italy', 
                  dim=[600, 450], 
                  x_label='Date', 
                  y_label='Total Cases MAX', legend_list=['total cases max','total cases max UP','total cases max DOWN'],
                  x_label_hover='date', y_label_hover='total cases max/UP/DOWN',
                  color_list=['blue','lightcoral','lightblue'],legend_location="top_left", y_minmax=(0,300000))

output_file("total_cases_MAX_2_Italy.html")

show(p_new_positive_MAX_2_Italy)

---------------

---------------

---------------

In [87]:
fit_range_3 = len(deceduti_italy) - 15
fit_range_4 = len(deceduti_italy)
xdata_3 = np.linspace(fit_range_3, fit_range_4, fit_range_4 - fit_range_3)
init_guess = [80000,0.001,0.001]
fit = curve_fit(model_population, xdata_3, deceduti_italy.loc[fit_range_3:(fit_range_4-1)], p0=init_guess)

/Users/Angelo/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:8: RuntimeWarning: overflow encountered in exp
  


In [88]:
ans, cov = fit
fit_K, fit_r, fit_P_0 = ans
fit_K, fit_r, fit_P_0

(35020.5157354272, 0.05148273603316009, 5665.116444469503)

In [89]:
cov

array([[ 4.12466273e+04, -6.24302039e+00,  3.02362441e+06],
       [-6.24302039e+00,  9.56000565e-04, -4.63976116e+02],
       [ 3.02362441e+06, -4.63976116e+02,  2.25269602e+08]])

In [90]:
np.sqrt(np.diag(cov))

array([2.03092657e+02, 3.09192588e-02, 1.50089841e+04])

In [91]:
ydata_3 = fit_K / ( 1 + ((fit_K - fit_P_0) / fit_P_0) * np.exp(- fit_r * xdata_3))
ydata_3

array([34540.16689917, 34565.6106117 , 34589.72339936, 34612.57314443,
       34634.2244466 , 34654.73876293, 34674.17454389, 34692.58736533,
       34710.03005621, 34726.55282221, 34742.20336502, 34757.02699739,
       34771.06675391, 34784.36349768, 34796.95602274])

In [92]:
pfit_total_deaths_Italy = bokeh_plot_2_lines(x=time_date_new[fit_range_3:fit_range_4], y=deceduti_italy.loc[(fit_range_3):(fit_range_4-1)], yy=ydata_3, 
                  title='Logistic Fitting Total Deaths: Italy', 
                  file_name="fit_total_deaths_Italy.html", 
                  x_label='Date', y_label='Total Deaths', 
                  legend_1='total deaths', legend_2='logistic fitting',
                  x_label_hover='date' , y_label_hover='total deaths OR logistic' , 
                  color_1='darkviolet', color_2='violet', y_minmax=None)

show(pfit_total_deaths_Italy)

In [93]:
- cov[0,1] / (np.sqrt(np.diag(cov)[0] * np.diag(cov)[1])) # Correlation coefficient for parameters 'K' and 'r'

0.9941947326848659

In [94]:
cov[0,2] / (np.sqrt(np.diag(cov)[0] * np.diag(cov)[2])) # Correlation coefficient for parameters 'K' and 'P_0'

0.9919329704728629

In [95]:
- cov[1,2] / (np.sqrt(np.diag(cov)[1] * np.diag(cov)[2])) # Correlation coefficient for parameters 'r' and 'P_0'

0.9998048844220018

In [96]:
residuals_3 = deceduti_italy.loc[(fit_range_3):(fit_range_4-1)] - ydata_3  #  Calculation of R^2
ss_res_3 = np.sum(residuals_3**2)
ss_tot_3 = np.sum((deceduti_italy.loc[(fit_range_3):(fit_range_4-1)] - np.mean(deceduti_italy.loc[(fit_range_3):(fit_range_4-1)]))**2)
r_squared_3 = 1 - (ss_res_3 / ss_tot_3)
r_squared_3

0.9551613596636036

---------------

In [97]:
max_deaths = []
max_deaths_up = []
max_deaths_down = []

# iii = len(deceduti_italy)
iii = 15

while (iii <= len(deceduti_italy)):
    fit_range_3 = iii - 15
    fit_range_4 = iii
    xdata_3 = np.linspace(fit_range_3, fit_range_4, fit_range_4 - fit_range_3)
    init_guess = [80000,0.001,0.001]
    fit = curve_fit(model_population, xdata_3, deceduti_italy.loc[fit_range_3:(fit_range_4-1)], p0=init_guess)
    ans, cov = fit
    fit_K, fit_r, fit_P_0 = ans
    max_deaths.append(fit_K)
    max_deaths_up.append(fit_K + np.sqrt(np.diag(cov))[0])
    max_deaths_down.append(fit_K - np.sqrt(np.diag(cov))[0])
    iii = iii + 1

/Users/Angelo/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:8: RuntimeWarning: overflow encountered in exp
  


In [98]:
len(max_deaths)

116

In [99]:
p_total_deaths_MAX_Italy = bokeh_plot_1_line(x=time_date_new + 14, y=max_deaths, 
                  title='Total Deaths MAX: Italy', 
                  file_name="total_deaths_MAX_Italy.html", 
                  x_label='Date', 
                  y_label='Total Deaths MAX', legend='total deaths max',
                  x_label_hover='date', y_label_hover='total deaths max',
                  color='darkviolet', y_minmax=None)

show(p_total_deaths_MAX_Italy)

In [100]:
p_total_deaths_MAX_2_Italy = bokeh_plot_N_lines(x=time_date_new + 14, y_list=[max_deaths,max_deaths_up,max_deaths_down], 
                  title='Total Deaths MAX: Italy', 
                  dim=[600, 450], 
                  x_label='Date', 
                  y_label='Total Deaths MAX', legend_list=['total deaths max','total deaths max UP','total deaths max DOWN'],
                  x_label_hover='date', y_label_hover='total deaths max/UP/DOWN',
                  color_list=['darkviolet','lightcoral','lightblue'],legend_location="bottom_right", y_minmax=None)

output_file("total_deaths_MAX_2_Italy.html")

show(p_total_deaths_MAX_2_Italy)

------------------

------------------

------------------

### ----- Gamma Distribution Fitting -----

In [101]:
fit_range_5 = len(nuovi_positivi_italy)   
xdata_4 = np.linspace(1, fit_range_5, fit_range_5)
# init_guess = [1,0.15,20000]
# init_guess = [6,1,500000]
fit = curve_fit(model_Gamma_distribution, xdata_4, nuovi_positivi_italy.loc[0:(fit_range_5-1)])
ans, cov = fit
fit_alpha, fit_beta, fit_Kmax = ans
fit_alpha, fit_beta, fit_Kmax

/Users/Angelo/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:12: RuntimeWarning: overflow encountered in multiply
  if sys.path[0] == '':
/Users/Angelo/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:12: RuntimeWarning: invalid value encountered in multiply
  if sys.path[0] == '':


(3.626629348789327, -0.1069794858515846, 234730.15435421)

In [102]:
cov

array([[ 3.05885895e-02, -7.93055409e-04, -4.08937266e+02],
       [-7.93055409e-04,  2.18560660e-05,  1.20230645e+01],
       [-4.08937266e+02,  1.20230645e+01,  1.98866857e+07]])

In [103]:
np.sqrt(np.diag(cov))

array([1.74895939e-01, 4.67504716e-03, 4.45944903e+03])

In [104]:
ydata_4 = model_Gamma_distribution(xdata_4,fit_alpha,fit_beta,fit_Kmax)
ydata_4

array([4.89959252e-01, 5.43780437e+00, 2.12608541e+01, 5.42283757e+01,
       1.09451746e+02, 1.90512345e+02, 2.99401323e+02, 4.36624812e+02,
       6.01393944e+02, 7.91851800e+02, 1.00530822e+03, 1.23846500e+03,
       1.48762138e+03, 1.74885470e+03, 2.01817413e+03, 2.29164755e+03,
       2.56550300e+03, 2.83620660e+03, 3.10051970e+03, 3.35553769e+03,
       3.59871335e+03, 3.82786707e+03, 4.04118646e+03, 4.23721744e+03,
       4.41484862e+03, 4.57329088e+03, 4.71205324e+03, 4.83091661e+03,
       4.92990614e+03, 5.00926314e+03, 5.06941727e+03, 5.11095947e+03,
       5.13461602e+03, 5.14122414e+03, 5.13170917e+03, 5.10706369e+03,
       5.06832839e+03, 5.01657495e+03, 4.95289074e+03, 4.87836545e+03,
       4.79407932e+03, 4.70109323e+03, 4.60044018e+03, 4.49311833e+03,
       4.38008530e+03, 4.26225371e+03, 4.14048781e+03, 4.01560105e+03,
       3.88835451e+03, 3.75945616e+03, 3.62956066e+03, 3.49926983e+03,
       3.36913348e+03, 3.23965076e+03, 3.11127178e+03, 2.98439943e+03,
      

In [105]:
pfit_new_positive_Italy = bokeh_plot_2_lines(x=time_date_new, y=nuovi_positivi_italy.loc[0:(fit_range_5-1)], yy=ydata_4[0:fit_range_5], 
                  title='Gamma Distribution Fitting New Positive: Italy', 
                  file_name="fit_new_positive_Italy.html", 
                  x_label='Date', y_label='New Positive', 
                  legend_1='total cases', legend_2='Gamma fitting',
                  x_label_hover='date' , y_label_hover='new positive OR fitting' , 
                  color_1='blue', color_2='red', y_minmax=None)

show(pfit_new_positive_Italy)

In [106]:
- cov[0,1] / (np.sqrt(np.diag(cov)[0] * np.diag(cov)[1])) # Correlation coefficient for parameters 'alpha' and 'beta'

0.9699242312400799

In [107]:
cov[0,2] / (np.sqrt(np.diag(cov)[0] * np.diag(cov)[2])) # Correlation coefficient for parameters 'alpha' and 'Kmax'

-0.5243191976049046

In [108]:
- cov[1,2] / (np.sqrt(np.diag(cov)[1] * np.diag(cov)[2])) # Correlation coefficient for parameters 'beta' and 'Kmax'

-0.576697378616807

In [109]:
residuals_4 = nuovi_positivi_italy.loc[0:(fit_range_5-1)] - ydata_4  #  Calculation of R^2
ss_res_4 = np.sum(residuals_4**2)
ss_tot_4 = np.sum((nuovi_positivi_italy.loc[0:(fit_range_5-1)] - np.mean(nuovi_positivi_italy.loc[0:(fit_range_5-1)]))**2)
r_squared_4 = 1 - (ss_res_4 / ss_tot_4)
r_squared_4

0.9407290047726792

----------------

In [110]:
fit_range_6 = time_date_new_extended.shape[0]
xdata_5 = np.linspace(1, fit_range_6, fit_range_6)
ydata_5 = model_Gamma_distribution(xdata_5,fit_alpha,fit_beta,fit_Kmax)
ydata_5

array([4.89959252e-01, 5.43780437e+00, 2.12608541e+01, 5.42283757e+01,
       1.09451746e+02, 1.90512345e+02, 2.99401323e+02, 4.36624812e+02,
       6.01393944e+02, 7.91851800e+02, 1.00530822e+03, 1.23846500e+03,
       1.48762138e+03, 1.74885470e+03, 2.01817413e+03, 2.29164755e+03,
       2.56550300e+03, 2.83620660e+03, 3.10051970e+03, 3.35553769e+03,
       3.59871335e+03, 3.82786707e+03, 4.04118646e+03, 4.23721744e+03,
       4.41484862e+03, 4.57329088e+03, 4.71205324e+03, 4.83091661e+03,
       4.92990614e+03, 5.00926314e+03, 5.06941727e+03, 5.11095947e+03,
       5.13461602e+03, 5.14122414e+03, 5.13170917e+03, 5.10706369e+03,
       5.06832839e+03, 5.01657495e+03, 4.95289074e+03, 4.87836545e+03,
       4.79407932e+03, 4.70109323e+03, 4.60044018e+03, 4.49311833e+03,
       4.38008530e+03, 4.26225371e+03, 4.14048781e+03, 4.01560105e+03,
       3.88835451e+03, 3.75945616e+03, 3.62956066e+03, 3.49926983e+03,
       3.36913348e+03, 3.23965076e+03, 3.11127178e+03, 2.98439943e+03,
      

In [111]:
pfit_2_new_positive_Italy = bokeh_plot_2_lines(x=time_date_new_extended, y=nuovi_positivi_italy.loc[0:(fit_range_5-1)], yy=ydata_5[0:fit_range_6], 
                  title='Gamma Distribution Fitting New Positive Extended: Italy', 
                  file_name="fit_2_new_positive_Italy.html", 
                  x_label='Date', y_label='New Positive', 
                  legend_1='total cases', legend_2='Gamma fitting',
                  x_label_hover='date' , y_label_hover='new positive OR fitting' , 
                  color_1='blue', color_2='red', y_minmax=None)

show(pfit_2_new_positive_Italy)

In [112]:
pfit_3_new_positive_Italy = bokeh_plot_N_lines(x=time_date_new_extended, y_list=[nuovi_positivi_italy.loc[0:(fit_range_5-1)],ydata_5[0:fit_range_6],SMA_new_positive['nuovi_positivi']], 
                  title='Gamma Distribution Fitting New Positive Extended: Italy', 
                  dim=[600, 450],
                  x_label='Date', 
                  y_label='New Positive', legend_list=['new positive','Gamma fitting','SMA 7 days'],
                  x_label_hover='date', y_label_hover='new positive/fitting/SMA 7',
                  color_list=['blue','red','lightblue'],legend_location="top_right", y_minmax=None)

output_file("fit_3_new_positive_Italy.html")

show(pfit_3_new_positive_Italy)

-----------------

------------

In [113]:
fit_range_7 = len(nuovi_deceduti)   
xdata_8 = np.linspace(1, fit_range_7, fit_range_7)
# init_guess = [1,0.15,20000]
fit = curve_fit(model_Gamma_distribution, xdata_8, nuovi_deceduti[0:(fit_range_7)])
ans, cov = fit
fit_alpha, fit_beta, fit_Kmax = ans
fit_alpha, fit_beta, fit_Kmax

/Users/Angelo/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:12: RuntimeWarning: overflow encountered in double_scalars
  if sys.path[0] == '':
/Users/Angelo/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:12: RuntimeWarning: overflow encountered in power
  if sys.path[0] == '':
/Users/Angelo/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:12: RuntimeWarning: invalid value encountered in multiply
  if sys.path[0] == '':
/Users/Angelo/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:12: RuntimeWarning: invalid value encountered in true_divide
  if sys.path[0] == '':


(4.30575678214018, -0.11238217555943728, 34033.93197926726)

In [114]:
cov

array([[ 4.89139768e-02, -1.14401833e-03, -8.21584385e+01],
       [-1.14401833e-03,  2.81950693e-05,  2.13938237e+00],
       [-8.21584385e+01,  2.13938237e+00,  4.87862226e+05]])

In [115]:
np.sqrt(np.diag(cov))

array([2.21165044e-01, 5.30990294e-03, 6.98471349e+02])

In [116]:
ydata_8 = model_Gamma_distribution(xdata_8,fit_alpha,fit_beta,fit_Kmax)
ydata_8

array([7.27335938e-03, 1.28555314e-01, 6.58399068e-01, 2.03066396e+00,
       4.74353434e+00, 9.29459086e+00, 1.61316916e+01, 2.56195898e+01,
       3.80202995e+01, 5.34846552e+01, 7.20525037e+01, 9.36592057e+01,
       1.18146453e+02, 1.45275757e+02, 1.74743303e+02, 2.06195151e+02,
       2.39242039e+02, 2.73473249e+02, 3.08469181e+02, 3.43812418e+02,
       3.79097193e+02, 4.13937218e+02, 4.47971949e+02, 4.80871359e+02,
       5.12339348e+02, 5.42115929e+02, 5.69978344e+02, 5.95741247e+02,
       6.19256110e+02, 6.40410000e+02, 6.59123830e+02, 6.75350233e+02,
       6.89071144e+02, 7.00295189e+02, 7.09054969e+02, 7.15404289e+02,
       7.19415420e+02, 7.21176406e+02, 7.20788482e+02, 7.18363620e+02,
       7.14022221e+02, 7.07890984e+02, 7.00100942e+02, 6.90785686e+02,
       6.80079771e+02, 6.68117297e+02, 6.55030675e+02, 6.40949551e+02,
       6.25999899e+02, 6.10303259e+02, 5.93976110e+02, 5.77129385e+02,
       5.59868088e+02, 5.42291024e+02, 5.24490625e+02, 5.06552860e+02,
      

In [117]:
pfit_new_deaths_Italy = bokeh_plot_2_lines(x=time_date_new, y=nuovi_deceduti[0:(fit_range_7)], yy=ydata_8[0:fit_range_7], 
                  title='Gamma Distribution Fitting New Deaths: Italy', 
                  file_name="fit_new_deaths_Italy.html", 
                  x_label='Date', y_label='New Deaths', 
                  legend_1='new deaths', legend_2='Gamma fitting',
                  x_label_hover='date' , y_label_hover='new deaths OR fitting' , 
                  color_1='darkviolet', color_2='red', y_minmax=None)

show(pfit_new_deaths_Italy)

In [118]:
- cov[0,1] / (np.sqrt(np.diag(cov)[0] * np.diag(cov)[1])) # Correlation coefficient for parameters 'alpha' and 'beta'

0.9741591514767097

In [119]:
cov[0,2] / (np.sqrt(np.diag(cov)[0] * np.diag(cov)[2])) # Correlation coefficient for parameters 'alpha' and 'Kmax'

-0.5318474649402244

In [120]:
- cov[1,2] / (np.sqrt(np.diag(cov)[1] * np.diag(cov)[2])) # Correlation coefficient for parameters 'beta' and 'Kmax'

-0.5768371652310784

In [121]:
residuals_8 = nuovi_deceduti[0:(fit_range_7)] - ydata_8  #  Calculation of R^2
ss_res_8 = np.sum(residuals_8**2)
ss_tot_8 = np.sum((nuovi_deceduti[0:(fit_range_7)] - np.mean(nuovi_deceduti[0:(fit_range_7)]))**2)
r_squared_8 = 1 - (ss_res_8 / ss_tot_8)
r_squared_8

0.929458456841223

-----------

In [122]:
fit_range_8 = time_date_new_extended.shape[0]
xdata_9 = np.linspace(1, fit_range_8, fit_range_8)
ydata_9 = model_Gamma_distribution(xdata_9,fit_alpha,fit_beta,fit_Kmax)
ydata_9

array([7.27335938e-03, 1.28555314e-01, 6.58399068e-01, 2.03066396e+00,
       4.74353434e+00, 9.29459086e+00, 1.61316916e+01, 2.56195898e+01,
       3.80202995e+01, 5.34846552e+01, 7.20525037e+01, 9.36592057e+01,
       1.18146453e+02, 1.45275757e+02, 1.74743303e+02, 2.06195151e+02,
       2.39242039e+02, 2.73473249e+02, 3.08469181e+02, 3.43812418e+02,
       3.79097193e+02, 4.13937218e+02, 4.47971949e+02, 4.80871359e+02,
       5.12339348e+02, 5.42115929e+02, 5.69978344e+02, 5.95741247e+02,
       6.19256110e+02, 6.40410000e+02, 6.59123830e+02, 6.75350233e+02,
       6.89071144e+02, 7.00295189e+02, 7.09054969e+02, 7.15404289e+02,
       7.19415420e+02, 7.21176406e+02, 7.20788482e+02, 7.18363620e+02,
       7.14022221e+02, 7.07890984e+02, 7.00100942e+02, 6.90785686e+02,
       6.80079771e+02, 6.68117297e+02, 6.55030675e+02, 6.40949551e+02,
       6.25999899e+02, 6.10303259e+02, 5.93976110e+02, 5.77129385e+02,
       5.59868088e+02, 5.42291024e+02, 5.24490625e+02, 5.06552860e+02,
      

In [123]:
pfit_2_new_deaths_Italy = bokeh_plot_2_lines(x=time_date_new_extended, y=nuovi_deceduti[0:(fit_range_7)], yy=ydata_9[0:fit_range_8], 
                  title='Gamma Distribution Fitting New Deaths Extended: Italy', 
                  file_name="fit_2_new_deaths_Italy.html", 
                  x_label='Date', y_label='New Deaths', 
                  legend_1='new deaths', legend_2='Gamma fitting',
                  x_label_hover='date' , y_label_hover='new deaths OR fitting' , 
                  color_1='darkviolet', color_2='red', y_minmax=None)

show(pfit_2_new_deaths_Italy)

-----------------
-----------------
-----------------

In [124]:
s1_grid = bokeh_plot_N_lines(x=time_date_new, y_list=[total_cases_italy,total_positive_italy], 
                  title='Total Cases & Total Positive: Italy', 
                  dim=[470, 350], 
                  x_label='Date', 
                  y_label='Total Cases & Total Positive', legend_list=['total cases','total positive'],
                  x_label_hover='date', y_label_hover='total cases OR total positive',
                  color_list=['blue','red'],legend_location="top_left", y_minmax=None)

s2_grid = bokeh_plot_N_lines(x=time_date_new, y_list=[deceduti_italy,guariti_italy], 
                  title='Deaths & Recovered: Italy', 
                  dim=[470, 350], 
                  x_label='Date', 
                  y_label='Deaths & Recovered', legend_list=['deaths','recovered'],
                  x_label_hover='date', y_label_hover='deaths OR recovered',
                  color_list=['darkviolet','green'],legend_location="top_left", y_minmax=None)


s3_grid = bokeh_plot_N_lines(x=time_date_new + 6, y_list=[R_2_cases, R_2_deaths, R_2_guariti], 
                  title='Total Cases/Deaths/Guariti - Exponential Validity: Italy', 
                  dim=[470, 350], 
                  x_label='Date', 
                  y_label='R_squared', legend_list=['R_squared_cases', 'R_squared_deaths', 'R_squared_guariti'],
                  x_label_hover='date', y_label_hover='R_squared_cases/deaths/guariti',
                  color_list=['blue', 'darkviolet', 'green'], legend_location="bottom_left", y_minmax=None)

s4_grid = bokeh_plot_N_lines(x=time_date_new + 14, y_list=[max_population_up,max_population_down,max_population], 
                  title='Max Total Cases - Logistic Fitting: Italy', 
                  dim=[470, 350], 
                  x_label='Date', 
                  y_label='Total Cases MAX', legend_list=['total cases max UP','total cases max DOWN','total cases max'],
                  x_label_hover='date', y_label_hover='total cases max/UP/DOWN',
                  color_list=['lightcoral','lightblue','blue'],legend_location="bottom_right", y_minmax=(0,300000))

s5_grid = bokeh_plot_N_lines(x=time_date_new + 14, y_list=[max_deaths_up,max_deaths_down,max_deaths], 
                  title='Max Total Deaths - Logistic Fitting: Italy', 
                  dim=[470, 350], 
                  x_label='Date', 
                  y_label='Total Deaths MAX', legend_list=['total deaths max UP','total deaths max DOWN','total deaths max'],
                  x_label_hover='date', y_label_hover='total deaths max/UP/DOWN',
                  color_list=['lightcoral','lightblue','darkviolet'],legend_location="bottom_right", y_minmax=(0,45000))

s6_grid = bokeh_plot_N_lines(x=time_date_new_extended, y_list=[nuovi_positivi_italy.loc[0:(fit_range_5-1)],ydata_5[0:fit_range_6]], 
                  title='New Positive - Gamma Distribution Fitting: Italy', 
                  dim=[470, 350],
                  x_label='Date', 
                  y_label='New Positive', legend_list=['new positive','Gamma fitting'],
                  x_label_hover='date', y_label_hover='new positive/fitting',
                  color_list=['blue','lightcoral'],legend_location="top_right", y_minmax=None)

s7_grid = bokeh_plot_N_lines(x=time_date_new_extended, y_list=[nuovi_deceduti[0:(fit_range_7)],ydata_9[0:fit_range_8]], 
                  title='New Deaths - Gamma Distribution Fitting: Italy', 
                  dim=[470, 350],
                  x_label='Date', 
                  y_label='New Deaths', legend_list=['new deaths','Gamma fitting'],
                  x_label_hover='date', y_label_hover='new deaths/fitting',
                  color_list=['darkviolet','lightcoral'],legend_location="top_right", y_minmax=None)

In [125]:
p_grid = gridplot([[s1_grid, s2_grid, s3_grid], [s4_grid, s5_grid], [s6_grid, s7_grid]])

output_file("grid_1.html")

show(p_grid)