<h1 align=center><font size = 7>Italian Trends Covid-19</font></h1>

------------

<font size = 5> **Author**: Angelo Di Marco

------------

In this Notebook, we analyze the spreading of the new coronavirus in Italy.

## Libraries and Functions

First we import the required libraries and define the bokeh plot functions:

In [1]:
import numpy as np

import pandas as pd

from math import pi

from bokeh.plotting import figure, output_file, show, output_notebook, gridplot
from bokeh.models import DatetimeTickFormatter, BasicTickFormatter, NumeralTickFormatter
from bokeh.models import HoverTool
from bokeh.layouts import row

output_notebook()

Loading BokehJS ...

In [2]:
def datetime(x):
    return np.array(x, dtype=np.datetime64)

---------------------

### ----- Plot function 1 line -----

In [3]:
def bokeh_plot_1_line(x, y, title, file_name, x_label, y_label, legend, x_label_hover, y_label_hover, color, y_minmax):
    
    output_file(file_name)
    
    p = figure(title=title, x_axis_type='datetime', x_axis_label=x_label, y_axis_label=y_label, width=600, height=450, y_range=y_minmax)
    
    p.line(x.squeeze(), y, color=color, line_width=4, legend_label=legend)
    p.circle(x.squeeze(), y, fill_color="white", line_color=color, size=6)
    
    p.xaxis.formatter = DatetimeTickFormatter(
#         hours=["%d %B %Y"],
#         days=["%Y %m %d"],
        days=["%d %B"],
#         months=["%d %B %Y"],
#         years=["%d %B %Y"],
    )
    p.xaxis.major_label_orientation = pi/4
  
    p.yaxis.formatter = BasicTickFormatter(use_scientific = False)
#     p.left[0].formatter.use_scientific = False
    p.yaxis.formatter = NumeralTickFormatter(format = '0,0')
    
    p.axis.minor_tick_in = -5
    p.axis.minor_tick_out = -3
    
    p.legend.location = "top_left"
    
    p.add_tools(HoverTool(
    tooltips=[
        ( x_label_hover,   '@x{%d %B}'    ),
        ( y_label_hover, '@y{0.}'      ),
    ],

    formatters={
           '@x'  : 'datetime', # use 'datetime' formatter for 'date' field
#            '@y'  : 'printf',   # use 'printf' formatter for 'adj close' field
                                  # use default 'numeral' formatter for other fields
    },

    # display a tooltip whenever the cursor is vertically in line with a glyph
    mode='vline'
    ))

    return p
#     show(p)

### ----- Plot function 2 lines -----

In [4]:
def bokeh_plot_2_lines(x, y, yy, title, file_name, x_label, y_label, legend_1, legend_2, x_label_hover, y_label_hover, color_1, color_2, y_minmax):
    
    output_file(file_name)
    
    p = figure(title=title, x_axis_type='datetime', x_axis_label=x_label, y_axis_label=y_label, width=600, height=450, y_range=y_minmax)
    
    p.line(x, y, color=color_1, line_width=4, legend_label=legend_1)
    p.circle(x, y, fill_color="white", line_color=color_1, size=6)
    
    p.line(x, yy, color=color_2, line_width=4, legend_label=legend_2)
    p.circle(x, yy, fill_color="white", line_color=color_2, size=6)
    
    p.xaxis.formatter=DatetimeTickFormatter(
#         hours=["%d %B %Y"],
#         days=["%Y %m %d"],
    days=["%d %B"],
#         months=["%d %B %Y"],
#         years=["%d %B %Y"],
    )
    p.xaxis.major_label_orientation = pi/4
  
    p.yaxis.formatter = BasicTickFormatter(use_scientific=False)
#     p.left[0].formatter.use_scientific = False
    p.yaxis.formatter = NumeralTickFormatter(format = '0,0')
    
    p.axis.minor_tick_in = -5
    p.axis.minor_tick_out = -3
    
    p.legend.location = "top_left"
    
    p.add_tools(HoverTool(
    tooltips=[
        ( x_label_hover,   '@x{%d %B}' ),
        ( y_label_hover, '@y{0.}' ),
#         ( 'label yy', '@yy' ),
    ],

    formatters={
           '@x'  : 'datetime', # use 'datetime' formatter for 'date' field
#            '@y'  : 'printf',   # use 'printf' formatter for 'adj close' field
                                  # use default 'numeral' formatter for other fields
    },

    # display a tooltip whenever the cursor is vertically in line with a glyph
    mode='vline'
    ))
    
    return p  
#     show(p)

### ----- Plot function N lines -----

In [5]:
def bokeh_plot_N_lines(x, y_list, title, dim, x_label, y_label, legend_list, x_label_hover, y_label_hover, color_list, legend_location, y_minmax):
    
#     output_file(file_name)
    
    p = figure(title=title, x_axis_type='datetime', x_axis_label=x_label, y_axis_label=y_label, width=dim[0], height=dim[1], y_range=y_minmax)
    
    for iii in range(0,len(y_list)):
        p.line(x, y_list[iii], color=color_list[iii], line_width=4, legend_label=legend_list[iii])
        p.circle(x, y_list[iii], fill_color="white", line_color=color_list[iii], size=5)
        
    
    p.xaxis.formatter=DatetimeTickFormatter(
#         hours=["%d %B %Y"],
#         days=["%Y %m %d"],
    days=["%d %B"],
#         months=["%d %B %Y"],
#         years=["%d %B %Y"],
    )
    p.xaxis.major_label_orientation = pi/4
  
    p.yaxis.formatter = BasicTickFormatter(use_scientific=False)
#     p.left[0].formatter.use_scientific = False
#     p.yaxis.formatter = NumeralTickFormatter(format = '0,0')
    p.yaxis.formatter.use_scientific = False
    
    p.axis.minor_tick_in = -5
    p.axis.minor_tick_out = -3
    
    p.legend.location = legend_location
    
    p.add_tools(HoverTool(
    tooltips=[
        ( x_label_hover,   '@x{%d %B}' ),
        ( y_label_hover, '@y{0[.]000}' ),
#         ( 'label yy', '@yy' ),
    ],

    formatters={
           '@x'  : 'datetime', # use 'datetime' formatter for 'date' field
#            '@y'  : 'printf',   # use 'printf' formatter for 'adj close' field
#            '@y'  : 'numeral',   # use 'printf' formatter for 'adj close' field
                                  # use default 'numeral' formatter for other fields
    },

    # display a tooltip whenever the cursor is vertically in line with a glyph
    mode='vline'
    ))
    
    return p  
#     show(p)

-----------------

## Data Sources

We importe the CSV files directly from the official GitHub source of the Protezione Civile:

In [6]:
data_links = {'nazionale':'https://raw.githubusercontent.com/pcm-dpc/COVID-19/master/dati-andamento-nazionale/dpc-covid19-ita-andamento-nazionale.csv',\
              'regioni':'https://raw.githubusercontent.com/pcm-dpc/COVID-19/master/dati-regioni/dpc-covid19-ita-regioni.csv',\
              'province':'https://raw.githubusercontent.com/pcm-dpc/COVID-19/master/dati-province/dpc-covid19-ita-province.csv'}

-----------------

## National Trends

In [7]:
path_nazionale = data_links['nazionale']
print('The path to the Raw CSV file for the national data is : \n', path_nazionale)
df_nazionale = pd.read_csv(path_nazionale)
df_nazionale.head()

The path to the Raw CSV file for the national data is : 
 https://raw.githubusercontent.com/pcm-dpc/COVID-19/master/dati-andamento-nazionale/dpc-covid19-ita-andamento-nazionale.csv


data stato  ricoverati_con_sintomi  terapia_intensiva  \
0  2020-02-24T18:00:00   ITA                     101                 26   
1  2020-02-25T18:00:00   ITA                     114                 35   
2  2020-02-26T18:00:00   ITA                     128                 36   
3  2020-02-27T18:00:00   ITA                     248                 56   
4  2020-02-28T18:00:00   ITA                     345                 64   

   totale_ospedalizzati  isolamento_domiciliare  totale_positivi  \
0                   127                      94              221   
1                   150                     162              311   
2                   164                     221              385   
3                   304                     284              588   
4                   409                     412              821   

   variazione_totale_positivi  nuovi_positivi  dimessi_guariti  deceduti  \
0                           0             221                1         7   
1                          90              93                1        10   
2                          74              78                3        12   
3                         203             250               45        17   
4                         233             238               46        21   

   casi_da_sospetto_diagnostico  casi_da_screening  totale_casi  tamponi  \
0                           NaN                NaN          229     4324   
1                           NaN                NaN          322     8623   
2                           NaN                NaN          400     9587   
3                           NaN                NaN          650    12014   
4                           NaN                NaN          888    15695   

   casi_testati note  
0           NaN  NaN  
1           NaN  NaN  
2           NaN  NaN  
3           NaN  NaN  
4           NaN  NaN

In [8]:
df_nazionale.shape

(193, 17)

------------

### Date Formatting

In [9]:
time_date = df_nazionale['data']
time_date.head()

0    2020-02-24T18:00:00
1    2020-02-25T18:00:00
2    2020-02-26T18:00:00
3    2020-02-27T18:00:00
4    2020-02-28T18:00:00
Name: data, dtype: object

In [10]:
time_date_new = pd.to_datetime(time_date).dt.date
time_date_new.head()

0    2020-02-24
1    2020-02-25
2    2020-02-26
3    2020-02-27
4    2020-02-28
Name: data, dtype: object

In [11]:
time_date_new = datetime(time_date_new)
time_date_new

array(['2020-02-24', '2020-02-25', '2020-02-26', '2020-02-27',
       '2020-02-28', '2020-02-29', '2020-03-01', '2020-03-02',
       '2020-03-03', '2020-03-04', '2020-03-05', '2020-03-06',
       '2020-03-07', '2020-03-08', '2020-03-09', '2020-03-10',
       '2020-03-11', '2020-03-12', '2020-03-13', '2020-03-14',
       '2020-03-15', '2020-03-16', '2020-03-17', '2020-03-18',
       '2020-03-19', '2020-03-20', '2020-03-21', '2020-03-22',
       '2020-03-23', '2020-03-24', '2020-03-25', '2020-03-26',
       '2020-03-27', '2020-03-28', '2020-03-29', '2020-03-30',
       '2020-03-31', '2020-04-01', '2020-04-02', '2020-04-03',
       '2020-04-04', '2020-04-05', '2020-04-06', '2020-04-07',
       '2020-04-08', '2020-04-09', '2020-04-10', '2020-04-11',
       '2020-04-12', '2020-04-13', '2020-04-14', '2020-04-15',
       '2020-04-16', '2020-04-17', '2020-04-18', '2020-04-19',
       '2020-04-20', '2020-04-21', '2020-04-22', '2020-04-23',
       '2020-04-24', '2020-04-25', '2020-04-26', '2020-

-----------

In [12]:
time_date_new_extended = pd.date_range(start=time_date_new[0], periods=2*time_date.shape[0])
time_date_new_extended

DatetimeIndex(['2020-02-24', '2020-02-25', '2020-02-26', '2020-02-27',
               '2020-02-28', '2020-02-29', '2020-03-01', '2020-03-02',
               '2020-03-03', '2020-03-04',
               ...
               '2021-03-06', '2021-03-07', '2021-03-08', '2021-03-09',
               '2021-03-10', '2021-03-11', '2021-03-12', '2021-03-13',
               '2021-03-14', '2021-03-15'],
              dtype='datetime64[ns]', length=386, freq='D')

In [13]:
time_date_new_extended[0:4]

DatetimeIndex(['2020-02-24', '2020-02-25', '2020-02-26', '2020-02-27'], dtype='datetime64[ns]', freq='D')

------------------

### Total Cases

In [14]:
total_cases_italy = df_nazionale['totale_casi']
total_cases_italy.head()

0    229
1    322
2    400
3    650
4    888
Name: totale_casi, dtype: int64

### Total Positive

In [15]:
total_positive_italy = df_nazionale['totale_positivi']
total_positive_italy.head()

0    221
1    311
2    385
3    588
4    821
Name: totale_positivi, dtype: int64

-------------------------

In [16]:
p_total_cases_Italy = bokeh_plot_1_line(x=time_date_new, y=total_cases_italy, 
                  title='Total Cases: Italy', 
                  file_name="total_cases_Italy.html", 
                  x_label='Date', 
                  y_label='Total Cases', legend='total cases',
                  x_label_hover='date', y_label_hover='total cases',
                  color='blue', y_minmax=None)

show(p_total_cases_Italy)

In [17]:
p_total_cases_positive_Italy = bokeh_plot_2_lines(x=time_date_new, y=total_cases_italy, yy=total_positive_italy, 
                  title='Total Cases vs Total Positive: Italy', 
                  file_name="total_cases_positive_Italy.html", 
                  x_label='Date', y_label='Total Cases & Total Positive', 
                  legend_1='total cases', legend_2='total positive',
                  x_label_hover='date' , y_label_hover='total cases OR positive' , 
                  color_1='blue', color_2='firebrick', y_minmax=None)

show(p_total_cases_positive_Italy)

In [18]:
p_total_cases_positive_2_Italy = bokeh_plot_N_lines(x=time_date_new, y_list=[total_cases_italy,total_positive_italy], 
                  title='Total Cases & Total Positive: Italy', 
                  dim=[600, 450], 
                  x_label='Date', 
                  y_label='Total Cases & Total Positive', legend_list=['total cases','total positive'],
                  x_label_hover='date', y_label_hover='total cases OR total positive',
                  color_list=['blue','red'],legend_location="top_left", y_minmax=None)

output_file("total_cases_positive_2_Italy.html")

show(p_total_cases_positive_2_Italy)

------------------

### Deaths

In [19]:
deceduti_italy = df_nazionale['deceduti']
deceduti_italy.head()

0     7
1    10
2    12
3    17
4    21
Name: deceduti, dtype: int64

------------------

### Recovered

In [20]:
guariti_italy = df_nazionale['dimessi_guariti']
guariti_italy.head()

0     1
1     1
2     3
3    45
4    46
Name: dimessi_guariti, dtype: int64

In [21]:
p_deaths_recovered_Italy = bokeh_plot_2_lines(x=time_date_new, y=deceduti_italy, yy=guariti_italy, 
                  title='Deaths vs Recovered: Italy', 
                  file_name="deaths_recovered_Italy.html", 
                  x_label='Date', y_label='Deaths & Recovered', 
                  legend_1='deaths', legend_2='recovered',
                  x_label_hover='date' , y_label_hover='deaths OR recovered' , 
                  color_1='darkviolet', color_2='green', y_minmax=None)

show(p_deaths_recovered_Italy)

------------------

### New Deaths

In [22]:
len(deceduti_italy)
    

193

In [23]:
nuovi_deceduti = [0]
i = 0
while (i < len(deceduti_italy)-1):
#     print(deceduti_italy.iloc[i + 1] - deceduti_italy.iloc[i])
    temp = deceduti_italy.iloc[i + 1] - deceduti_italy.iloc[i]
    nuovi_deceduti.append(temp)
    i = i + 1

In [24]:
p_new_deaths_Italy = bokeh_plot_1_line(x=time_date_new, y=nuovi_deceduti, 
                  title='New Deaths: Italy', 
                  file_name="new_deaths_Italy.html", 
                  x_label='Date', 
                  y_label='New Deaths', legend='new deaths',
                  x_label_hover='date', y_label_hover='new deaths',
                  color='darkviolet', y_minmax=None)

show(p_new_deaths_Italy)

In [25]:
nuovi_deceduti_df = pd.DataFrame(nuovi_deceduti)

SMA_new_deaths = nuovi_deceduti_df[:].rolling(window=7).mean()
SMA_new_deaths_2 = nuovi_deceduti_df[:].rolling(window=10).mean()

In [26]:
SMA_new_deaths.head()

0
0 NaN
1 NaN
2 NaN
3 NaN
4 NaN

In [27]:
p_new_deaths_SMA_Italy = bokeh_plot_2_lines(x=time_date_new, y=nuovi_deceduti, yy=SMA_new_deaths[0], 
                  title='New Deaths: Italy', 
                  file_name="new_deaths_SMA_Italy.html", 
                  x_label='Date', y_label='New Deaths', 
                  legend_1='new deaths', legend_2='SMA 7 days',
                  x_label_hover='date' , y_label_hover='new deaths OR SMA 7' , 
                  color_1='darkviolet', color_2='lightblue', y_minmax=None)

show(p_new_deaths_SMA_Italy)

------------------

### New Positive

In [28]:
nuovi_positivi_italy = df_nazionale['nuovi_positivi']
nuovi_positivi_italy.head()

0    221
1     93
2     78
3    250
4    238
Name: nuovi_positivi, dtype: int64

In [29]:
p_new_positive_Italy = bokeh_plot_1_line(x=time_date_new, y=nuovi_positivi_italy, 
                  title='New Positive: Italy', 
                  file_name="new_positive_Italy.html", 
                  x_label='Date', 
                  y_label='New Positive', legend='new positive',
                  x_label_hover='date', y_label_hover='new positive',
                  color='blue', y_minmax=None)

show(p_new_positive_Italy)

In [30]:
new_positive_df = pd.DataFrame(nuovi_positivi_italy)

SMA_new_positive = new_positive_df[:].rolling(window=7).mean()
SMA_new_positive_2 = new_positive_df[:].rolling(window=10).mean()

In [31]:
SMA_new_positive.head()

nuovi_positivi
0             NaN
1             NaN
2             NaN
3             NaN
4             NaN

In [32]:
p_new_positive_SMA_Italy = bokeh_plot_2_lines(x=time_date_new, y=nuovi_positivi_italy, yy=SMA_new_positive['nuovi_positivi'], 
                  title='New Positive: Italy', 
                  file_name="new_positive_SMA_Italy.html", 
                  x_label='Date', y_label='New Positive', 
                  legend_1='new positive', legend_2='SMA 7 days',
                  x_label_hover='date' , y_label_hover='new_positive OR SMA 7' , 
                  color_1='blue', color_2='lightcoral', y_minmax=None)

show(p_new_positive_SMA_Italy)

------------------------

In [33]:
# show(row(p_new_positive_Italy,p_new_deaths_Italy))

In [34]:
p_new_deaths_positive_Italy = bokeh_plot_2_lines(x=time_date_new, y=nuovi_deceduti, yy=nuovi_positivi_italy, 
                  title='New Deaths vs New Positive: Italy', 
                  file_name="new_deaths_positive_Italy.html", 
                  x_label='Date', y_label='New Deaths & New Positive', 
                  legend_1='new deaths', legend_2='new positive',
                  x_label_hover='date' , y_label_hover='new deaths OR new positive' , 
                  color_1='darkviolet', color_2='blue', y_minmax=None)

show(p_new_deaths_positive_Italy)

---------------------

### Total Hospitalized

In [35]:
total_hospital_italy = df_nazionale['totale_ospedalizzati']
total_hospital_italy.head()

0    127
1    150
2    164
3    304
4    409
Name: totale_ospedalizzati, dtype: int64

---------------------

### Intensive Care

In [36]:
intensive_care_italy = df_nazionale['terapia_intensiva']
intensive_care_italy.head()

0    26
1    35
2    36
3    56
4    64
Name: terapia_intensiva, dtype: int64

In [37]:
p_total_hospitalized_Italy = bokeh_plot_1_line(x=time_date_new, y=total_hospital_italy, 
                  title='Total Hospitalized: Italy', 
                  file_name="total_hospitalized_Italy.html", 
                  x_label='Date', 
                  y_label='Total Hospitalized', legend='total hospitalized',
                  x_label_hover='date', y_label_hover='total hospitalized',
                  color='orange', y_minmax=None)
# output_file("total_cases_Italy.html")
show(p_total_hospitalized_Italy)

In [38]:
p_intensive_care_Italy = bokeh_plot_1_line(x=time_date_new, y=intensive_care_italy, 
                  title='Intensive Care: Italy', 
                  file_name="intensive_care_Italy.html", 
                  x_label='Date', 
                  y_label='Intensive Care', legend='intensive care',
                  x_label_hover='date', y_label_hover='intensive care',
                  color='GoldenRod', y_minmax=None)
# output_file("total_cases_Italy.html")
show(p_intensive_care_Italy)

In [39]:
p_hospitalized_intensivecare_Italy = bokeh_plot_2_lines(x=time_date_new, y=total_hospital_italy, yy=intensive_care_italy, 
                  title='Total Hospitalized vs Intensive Care: Italy', 
                  file_name="hospitalized_intensivecare_Italy.html", 
                  x_label='Date', y_label='Total Hospitalized & Intensive Care', 
                  legend_1='total hospitalized', legend_2='intensive care',
                  x_label_hover='date' , y_label_hover='hospitalized OR intensive care' , 
                  color_1='orange', color_2='GoldenRod', y_minmax=None)

show(p_hospitalized_intensivecare_Italy)

----------

-------------------------
# Fitting

In [40]:
from scipy.optimize import curve_fit
from scipy.special import gamma

def model_exp(x,a,b):
    return a * np.exp(b * x)

def model_population(x,K,r,P_0):
    den = 1 + ((K - P_0) / P_0) * np.exp(- r * x)
    return K / den

def model_Gamma_distribution(x,alpha,beta,Kmax):
    return Kmax * np.abs(beta)**(np.abs(alpha) + 1) * x**(np.abs(alpha)) * np.exp(- np.abs(beta) * x) / gamma((np.abs(alpha) + 1))

------------------

### ----- Exponential Fitting -----

In [41]:
fit_range = 28   # best fit when fit_range = 28 namely March 22
xdata = np.linspace(0, fit_range, fit_range)
init_guess = [5000, 0.001]
fit = curve_fit(model_exp, xdata, total_cases_italy.loc[0:(fit_range-1)], p0=init_guess)
ans, cov = fit
fit_a, fit_b = ans
fit_a, fit_b

(1268.6044974646502, 0.13890844390214907)

In [42]:
cov

array([[ 9.92195154e+03, -3.07812476e-01],
       [-3.07812476e-01,  9.74343219e-06]])

In [43]:
np.sqrt(np.diag(cov))

array([9.96089933e+01, 3.12144713e-03])

In [44]:
ydata = model_exp(xdata,fit_a,fit_b)
ydata

array([ 1268.60449746,  1465.16912064,  1692.1905577 ,  1954.38795648,
        2257.21167574,  2606.95658312,  3010.89290796,  3477.41736932,
        4016.22772053,  4638.52433861,  5357.24304922,  6187.32402664,
        7146.02235868,  8253.26673226,  9532.07369566, 11009.02610895,
       12714.82572808, 14684.9314095 , 16960.29620175, 19588.21864602,
       22623.32598204, 26128.70969733, 30177.23702472, 34853.06565057,
       40253.3931204 , 46490.47730694, 53693.96994092, 62013.61171197])

In [45]:
pfit_total_cases_Italy = bokeh_plot_2_lines(x=time_date_new[0:(fit_range)], y=total_cases_italy.loc[0:(fit_range-1)], yy=ydata[0:fit_range], 
                  title='Exponential Fitting Total Cases: Italy', 
                  file_name="fit_total_cases_Italy.html", 
                  x_label='Date', y_label='Total Cases', 
                  legend_1='total cases', legend_2='exponential fitting',
                  x_label_hover='date' , y_label_hover='total cases OR fitting' , 
                  color_1='blue', color_2='red', y_minmax=None)

show(pfit_total_cases_Italy)

In [46]:
- cov[0,1] / (np.sqrt(np.diag(cov)[0] * np.diag(cov)[1])) # Correlation coefficient for parameters 'a' and 'b'

0.9899919975413152

In [47]:
residuals = total_cases_italy.loc[0:(fit_range-1)] - ydata  #  Calculation of R^2
ss_res = np.sum(residuals**2)
ss_tot = np.sum((total_cases_italy.loc[0:(fit_range-1)] - np.mean(total_cases_italy.loc[0:(fit_range-1)]))**2)
r_squared = 1 - (ss_res / ss_tot)
r_squared

0.9942027803878379

---------------

In [48]:
fit_range = 49   # best fit when fit_range = 28 namely March 22
xdata = np.linspace(0, fit_range, fit_range)
init_guess = [5000, 0.001]
fit = curve_fit(model_exp, xdata, total_cases_italy.loc[0:(fit_range-1)], p0=init_guess)
ans, cov = fit
fit_a, fit_b = ans
fit_a, fit_b

(10273.505399700898, 0.058660707522345125)

In [49]:
cov

array([[ 1.70490033e+06, -3.88568817e+00],
       [-3.88568817e+00,  9.19880384e-06]])

In [50]:
np.sqrt(np.diag(cov))

array([1.30571832e+03, 3.03295299e-03])

In [51]:
ydata = model_exp(xdata,fit_a,fit_b)
ydata

array([ 10273.5053997 ,  10907.50512106,  11580.63030457,  12295.29546516,
        13054.06412256,  13859.65799674,  14714.96677074,  15623.05845605,
        16587.19039764,  17610.82095811,  18697.62192291,  19851.49167117,
        21076.56915918,  22377.24876699,  23758.19606113,  25224.3645301 ,
        26781.01335261,  28433.72626244,  30188.43157735,  32051.42346413,
        34029.38451587,  36129.40972262,  38359.03192126,  40726.24881594,
        43239.55166602,  45907.95574442,  48741.03267559,  51748.94476916,
        54942.48147235,  58333.09807195,  61932.95678471,  65754.97038346,
        69812.84851553,  74121.14687954,  78695.31943703,  83551.77384615,
        88707.93031628,  94182.28409475,  99994.47180965, 106165.34190689,
       112717.02943402, 119673.03543912, 127058.3112696 , 134899.34807324,
       143224.27182249, 152062.94420302, 161447.06972815, 171410.30946374,
       181988.4017711 ])

In [52]:
- cov[0,1] / (np.sqrt(np.diag(cov)[0] * np.diag(cov)[1])) # Correlation coefficient for parameters 'a' and 'b'

0.9811892216342538

In [53]:
residuals = total_cases_italy.loc[0:(fit_range-1)] - ydata  #  Calculation of R^2
ss_res = np.sum(residuals**2)
ss_tot = np.sum((total_cases_italy.loc[0:(fit_range-1)] - np.mean(total_cases_italy.loc[0:(fit_range-1)]))**2)
r_squared = 1 - (ss_res / ss_tot)
r_squared

0.940258800232746

In [54]:
pfit_total_cases_Italy = bokeh_plot_2_lines(x=time_date_new[0:(fit_range)], y=total_cases_italy.loc[0:(fit_range-1)], yy=ydata[0:fit_range], 
                  title='Exponential Fitting Total Cases: Italy', 
                  file_name="fit_total_cases_Italy.html", 
                  x_label='Date', y_label='Total Cases', 
                  legend_1='total cases', legend_2='exponential fitting',
                  x_label_hover='date' , y_label_hover='total cases OR fitting' , 
                  color_1='blue', color_2='red', y_minmax=None)

show(pfit_total_cases_Italy)

------------------------

------------------------

In [55]:
R_2_cases = []
Correlation_A_B = []
iii = 7

while(iii <= len(total_cases_italy)):
    fit_range = iii   # best fit when fit_range = 28 namely March 22
    xdata = np.linspace(0, fit_range, fit_range)
    init_guess = [5000, 0.001]
    fit = curve_fit(model_exp, xdata, total_cases_italy.loc[0:(fit_range-1)], p0=init_guess)
    ans, cov = fit
    fit_a, fit_b = ans
    fit_a, fit_b
    ydata = model_exp(xdata,fit_a,fit_b)
    residuals = total_cases_italy.loc[0:(fit_range-1)] - ydata  #  Calculation of R^2
    ss_res = np.sum(residuals**2)
    ss_tot = np.sum((total_cases_italy.loc[0:(fit_range-1)] - np.mean(total_cases_italy.loc[0:(fit_range-1)]))**2)
    r_squared = 1 - (ss_res / ss_tot)
    R_2_cases.append(r_squared)
    correlation_ab = - cov[0,1] / (np.sqrt(np.diag(cov)[0] * np.diag(cov)[1]))
    Correlation_A_B.append(correlation_ab)
    iii = iii + 1

In [56]:
p_total_cases_exp_val_Italy = bokeh_plot_N_lines(x=time_date_new + 6, y_list=[R_2_cases, Correlation_A_B], 
                  title='Total Cases Exponential Validity: Italy', 
                  dim=[600, 450], 
                  x_label='Date', 
                  y_label='R_squared', legend_list=['R_squared', 'Corr_A_B'],
                  x_label_hover='date', y_label_hover='R_squared/Corr_A_B',
                  color_list=['blue', 'lightblue'],legend_location="top_right", y_minmax=None)

output_file("total_cases_exponential_validity_Italy.html")

show(p_total_cases_exp_val_Italy)

--------------------

In [57]:
R_2_deaths = []
Correlation_A_B = []
iii = 7

while(iii <= len(deceduti_italy)):
    fit_range = iii   # best fit when fit_range = 28 namely March 22
    xdata = np.linspace(0, fit_range, fit_range)
    init_guess = [5000, 0.001]
    fit = curve_fit(model_exp, xdata, deceduti_italy.loc[0:(fit_range-1)], p0=init_guess)
    ans, cov = fit
    fit_a, fit_b = ans
    fit_a, fit_b
    ydata = model_exp(xdata,fit_a,fit_b)
    residuals = deceduti_italy.loc[0:(fit_range-1)] - ydata  #  Calculation of R^2
    ss_res = np.sum(residuals**2)
    ss_tot = np.sum((deceduti_italy.loc[0:(fit_range-1)] - np.mean(deceduti_italy.loc[0:(fit_range-1)]))**2)
    r_squared = 1 - (ss_res / ss_tot)
    R_2_deaths.append(r_squared)
    correlation_ab = - cov[0,1] / (np.sqrt(np.diag(cov)[0] * np.diag(cov)[1]))
    Correlation_A_B.append(correlation_ab)
    iii = iii + 1

In [58]:
p_total_deaths_exp_val_Italy = bokeh_plot_N_lines(x=time_date_new + 6, y_list=[R_2_deaths, Correlation_A_B], 
                  title='Total Deaths Exponential Validity: Italy', 
                  dim=[600, 450], 
                  x_label='Date', 
                  y_label='R_squared', legend_list=['R_squared', 'Corr_A_B'],
                  x_label_hover='date', y_label_hover='R_squared/Corr_A_B',
                  color_list=['darkviolet', 'violet'],legend_location="top_right", y_minmax=None)

output_file("total_deaths_exponential_validity_Italy.html")

show(p_total_deaths_exp_val_Italy)

-----------------

In [59]:
p_total_cases_deaths_exp_val_Italy = bokeh_plot_N_lines(x=time_date_new + 6, y_list=[R_2_cases, R_2_deaths], 
                  title='Total Cases/Deaths Exponential Validity: Italy', 
                  dim=[600, 450], 
                  x_label='Date', 
                  y_label='R_squared', legend_list=['R_squared_cases', 'R_squared_deaths'],
                  x_label_hover='date', y_label_hover='R_squared_cases/deaths',
                  color_list=['blue', 'darkviolet'],legend_location="top_right", y_minmax=None)

output_file("total_cases_deaths_exponential_validity_Italy.html")

show(p_total_cases_deaths_exp_val_Italy)

--------------------

In [60]:
R_2_guariti = []
Correlation_A_B = []
iii = 7

while(iii <= len(guariti_italy)):
    fit_range = iii   # best fit when fit_range = 28 namely March 22
    xdata = np.linspace(0, fit_range, fit_range)
    init_guess = [5000, 0.001]
    fit = curve_fit(model_exp, xdata, guariti_italy.loc[0:(fit_range-1)], p0=init_guess)
    ans, cov = fit
    fit_a, fit_b = ans
    fit_a, fit_b
    ydata = model_exp(xdata,fit_a,fit_b)
    residuals = guariti_italy.loc[0:(fit_range-1)] - ydata  #  Calculation of R^2
    ss_res = np.sum(residuals**2)
    ss_tot = np.sum((guariti_italy.loc[0:(fit_range-1)] - np.mean(guariti_italy.loc[0:(fit_range-1)]))**2)
    r_squared = 1 - (ss_res / ss_tot)
    R_2_guariti.append(r_squared)
    correlation_ab = - cov[0,1] / (np.sqrt(np.diag(cov)[0] * np.diag(cov)[1]))
    Correlation_A_B.append(correlation_ab)
    iii = iii + 1

In [61]:
p_guariti_exp_val_Italy = bokeh_plot_N_lines(x=time_date_new + 6, y_list=[R_2_guariti, Correlation_A_B], 
                  title='Guariti Exponential Validity: Italy', 
                  dim=[600, 450], 
                  x_label='Date', 
                  y_label='R_squared', legend_list=['R_squared', 'Corr_A_B'],
                  x_label_hover='date', y_label_hover='R_squared/Corr_A_B',
                  color_list=['green', 'lightgreen'],legend_location="bottom_right", y_minmax=None)

output_file("guariti_exponential_validity_Italy.html")

show(p_guariti_exp_val_Italy)

----------------------

In [62]:
p_total_cases_deaths_guariti_exp_val_Italy = bokeh_plot_N_lines(x=time_date_new + 6, y_list=[R_2_cases, R_2_deaths, R_2_guariti], 
                  title='Total Cases/Deaths/Guariti Exponential Validity: Italy', 
                  dim=[600, 450], 
                  x_label='Date', 
                  y_label='R_squared', legend_list=['R_squared_cases', 'R_squared_deaths', 'R_squared_guariti'],
                  x_label_hover='date', y_label_hover='R_squared_cases/deaths/guariti',
                  color_list=['blue', 'darkviolet', 'green'],legend_location="bottom_right", y_minmax=None)

output_file("total_cases_deaths_guariti_exponential_validity_Italy.html")

show(p_total_cases_deaths_guariti_exp_val_Italy)

--------------------------

----------------------

--------------------------

### -----  Logistic Fitting -----

In [63]:
fit_range_1 = len(total_cases_italy)
xdata_1 = np.linspace(0, fit_range_1, fit_range_1)
init_guess = [500000, 0.10, 100]
fit = curve_fit(model_population, xdata_1, total_cases_italy.loc[0:(fit_range_1-1)], p0 = init_guess)
ans, cov = fit
fit_K, fit_r, fit_P_0 = ans
fit_K, fit_r, fit_P_0

(244433.17140012363, 0.07743184214385831, 8936.93316131286)

In [64]:
cov

array([[ 8.83665152e+05, -6.73280345e-01,  1.84689788e+05],
       [-6.73280345e-01,  3.96546428e-06, -1.40211852e+00],
       [ 1.84689788e+05, -1.40211852e+00,  5.52414407e+05]])

In [65]:
np.sqrt(np.diag(cov))

array([9.40034655e+02, 1.99134735e-03, 7.43245859e+02])

In [66]:
ydata_1 = model_population(xdata_1, fit_K, fit_r, fit_P_0)
ydata_1

array([  8936.93316131,   9631.8229557 ,  10378.36263575,  11180.00972044,
        12040.39237695,  12963.30786137,  13952.71894177,  15012.74797372,
        16147.66827324,  17361.8924107 ,  18659.95703252,  20046.50380743,
        21526.25609339,  23103.99093178,  24784.50600055,  26572.58120052,
        28472.93461107,  30490.17263783,  32628.73428592,  34892.82963173,
        37286.37273471,  39812.90942746,  42475.54064718,  45276.84221988,
        48218.78227499,  51302.63774389,  54528.91167054,  57897.25332152,
        61406.38331154,  65054.02614012,  68836.85264797,  72750.43492917,
        76789.21616138,  80946.49762845,  85214.44489997,  89584.1147001 ,
        94045.50345019,  98587.61782235, 103198.56691842, 107865.6749235 ,
       112575.61231296, 117314.5429602 , 122068.28384061, 126822.47349631,
       131562.74504961, 136274.899355  , 140945.0738737 , 145559.9030408 ,
       150106.66626128, 154573.42019343, 158949.11262331, 163223.67596219,
       167388.09916776, 1

In [67]:
pfit_1_total_cases_Italy = bokeh_plot_2_lines(x=time_date_new[0:(fit_range_1)], y=total_cases_italy.loc[0:(fit_range_1-1)], yy=ydata_1[0:fit_range_1], 
                  title='Logistic Fitting Total Cases: Italy', 
                  file_name="fit_1_total_cases_Italy.html", 
                  x_label='Date', y_label='Total Cases', 
                  legend_1='total cases', legend_2='logistic fitting',
                  x_label_hover='date' , y_label_hover='total cases OR fitting' , 
                  color_1='blue', color_2='red', y_minmax=None)

show(pfit_1_total_cases_Italy)

In [68]:
- cov[0,1] / (np.sqrt(np.diag(cov)[0] * np.diag(cov)[1])) # Correlation coefficient for parameters 'K' and 'r'

0.3596706924460884

In [69]:
cov[0,2] / (np.sqrt(np.diag(cov)[0] * np.diag(cov)[2])) # Correlation coefficient for parameters 'K' and 'P_0'

0.26434221261719054

In [70]:
- cov[1,2] / (np.sqrt(np.diag(cov)[1] * np.diag(cov)[2])) # Correlation coefficient for parameters 'r' and 'P_0'

0.9473385407632192

In [71]:
residuals_1 = total_cases_italy.loc[0:(fit_range_1-1)] - ydata_1  #  Calculation of R^2
ss_res_1 = np.sum(residuals_1**2)
ss_tot_1 = np.sum((total_cases_italy.loc[0:(fit_range_1-1)] - np.mean(total_cases_italy.loc[0:(fit_range_1-1)]))**2)
r_squared_1 = 1 - (ss_res_1 / ss_tot_1)
r_squared_1

0.9871789301334498

----------------------

In [72]:
fit_range_2 = len(total_cases_italy) - 15
fit_range_3 = len(total_cases_italy)
xdata_2 = np.linspace(fit_range_2, fit_range_3, fit_range_3 - fit_range_2)
# init_guess = [250000,0.25,1]
init_guess = [500000,0.001,0]
fit = curve_fit(model_population, xdata_2, total_cases_italy.loc[fit_range_2:(fit_range_3-1)], p0=init_guess, maxfev=20000)

/Users/Angelo/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:8: RuntimeWarning: divide by zero encountered in double_scalars
  


In [73]:
ans, cov = fit

In [74]:
fit_K, fit_r, fit_P_0 = ans
fit_K, fit_r, fit_P_0

(8938853250.32943, 0.004316820462258374, 118597.61443125473)

In [75]:
cov

array([[ 4.34750857e+28, -6.24101255e+11,  4.29583739e+18],
       [-6.24101255e+11,  8.96275764e-06, -6.17465135e+01],
       [ 4.29583739e+18, -6.17465135e+01,  4.26200022e+08]])

In [76]:
np.sqrt(np.diag(cov))

array([2.08506800e+14, 2.99378650e-03, 2.06446124e+04])

In [77]:
ydata_2 = fit_K / ( 1 + ((fit_K - fit_P_0) / fit_P_0) * np.exp(- fit_r * xdata_2))
ydata_2

array([255728.17730427, 256913.66769961, 258104.6535664 , 259301.16037802,
       260503.21372593, 261710.8393202 , 262924.06299004, 264142.9106844 ,
       265367.40847249, 266597.58254433, 267833.45921134, 269075.06490689,
       270322.42618684, 271575.56973016, 272834.52233946])

In [78]:
pfit_2_total_cases_Italy = bokeh_plot_2_lines(x=time_date_new[fit_range_2:fit_range_3], y=total_cases_italy.loc[(fit_range_2):(fit_range_3-1)], yy=ydata_2, 
                  title='Logistic Fitting Total Cases: Italy', 
                  file_name="fit_2_total_cases_Italy.html", 
                  x_label='Date', y_label='Total Cases', 
                  legend_1='total cases', legend_2='logistic fitting',
                  x_label_hover='date' , y_label_hover='total cases OR logistic' , 
                  color_1='blue', color_2='red', y_minmax=None)

show(pfit_2_total_cases_Italy)

In [79]:
- cov[0,1] / (np.sqrt(np.diag(cov)[0] * np.diag(cov)[1])) # Correlation coefficient for parameters 'K' and 'r'

0.9998020121927177

In [80]:
cov[0,2] / (np.sqrt(np.diag(cov)[0] * np.diag(cov)[2])) # Correlation coefficient for parameters 'K' and 'P_0'

0.9979777900793706

In [81]:
- cov[1,2] / (np.sqrt(np.diag(cov)[1] * np.diag(cov)[2])) # Correlation coefficient for parameters 'r' and 'P_0'

0.9990446081717433

In [82]:
residuals_2 = total_cases_italy.loc[(fit_range_2):(fit_range_3-1)] - ydata_2  #  Calculation of R^2
ss_res_2 = np.sum(residuals_2**2)
ss_tot_2 = np.sum((total_cases_italy.loc[(fit_range_2):(fit_range_3-1)] - np.mean(total_cases_italy.loc[(fit_range_2):(fit_range_3-1)]))**2)
r_squared_2 = 1 - (ss_res_2 / ss_tot_2)
r_squared_2

0.997720326783196

---------------

In [83]:
max_population = []
max_population_up = []
max_population_down = []

# iii = len(total_cases_italy)
iii = 15

while (iii <= len(total_cases_italy)):
    fit_range_2 = iii - 15
    fit_range_3 = iii
    xdata_2 = np.linspace(fit_range_2, fit_range_3, fit_range_3 - fit_range_2)
    init_guess = [500000,0.001,0]
    fit = curve_fit(model_population, xdata_2, total_cases_italy.loc[fit_range_2:(fit_range_3-1)], p0=init_guess, maxfev=10000)
    ans, cov = fit
    fit_K, fit_r, fit_P_0 = ans
    max_population.append(fit_K)
    max_population_up.append(fit_K + np.sqrt(np.diag(cov))[0])
    max_population_down.append(fit_K - np.sqrt(np.diag(cov))[0])
    iii = iii + 1

/Users/Angelo/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:8: RuntimeWarning: divide by zero encountered in double_scalars
  


In [84]:
len(max_population)

179

In [85]:
p_new_positive_MAX_Italy = bokeh_plot_1_line(x=time_date_new + 14, y=max_population, 
                  title='Total Cases MAX: Italy', 
                  file_name="total_cases_MAX_Italy.html", 
                  x_label='Date', 
                  y_label='Total Cases MAX', legend='total cases max',
                  x_label_hover='date', y_label_hover='total cases max',
                  color='blue', y_minmax=(0,300000))

show(p_new_positive_MAX_Italy)

In [86]:
p_new_positive_MAX_2_Italy = bokeh_plot_N_lines(x=time_date_new + 14, y_list=[max_population,max_population_up,max_population_down], 
                  title='Total Cases MAX: Italy', 
                  dim=[600, 450], 
                  x_label='Date', 
                  y_label='Total Cases MAX', legend_list=['total cases max','total cases max UP','total cases max DOWN'],
                  x_label_hover='date', y_label_hover='total cases max/UP/DOWN',
                  color_list=['blue','lightcoral','lightblue'],legend_location="top_left", y_minmax=(0,300000))

output_file("total_cases_MAX_2_Italy.html")

show(p_new_positive_MAX_2_Italy)

---------------

---------------

---------------

In [135]:
fit_range_3 = len(deceduti_italy) - 15
fit_range_4 = len(deceduti_italy)
xdata_3 = np.linspace(fit_range_3, fit_range_4, fit_range_4 - fit_range_3)
# init_guess = [80000,0.001,0.001]
init_guess = [80000,0.0001111,100.111]
fit = curve_fit(model_population, xdata_3, deceduti_italy.loc[fit_range_3:(fit_range_4-1)], p0=init_guess)

In [136]:
ans, cov = fit
fit_K, fit_r, fit_P_0 = ans
fit_K, fit_r, fit_P_0

(2154084633472.4065, 0.00016073944187205253, 34419.51080818975)

In [137]:
cov

array([[ 3.72393948e+31,  3.94743406e+09, -2.13805671e+16],
       [ 3.94743406e+09,  1.76695153e-11, -1.12415496e-04],
       [-2.13805671e+16, -1.12415496e-04,  7.16021688e+02]])

In [138]:
np.sqrt(np.diag(cov))

array([6.10240894e+15, 4.20351225e-06, 2.67585816e+01])

In [139]:
ydata_3 = fit_K / ( 1 + ((fit_K - fit_P_0) / fit_P_0) * np.exp(- fit_r * xdata_3))
ydata_3

array([35418.53244124, 35424.6327755 , 35430.73416046, 35436.83659629,
       35442.94008318, 35449.04462131, 35455.15021086, 35461.25685201,
       35467.36454493, 35473.47328983, 35479.58308686, 35485.69393622,
       35491.80583809, 35497.91879264, 35504.03280006])

In [140]:
pfit_total_deaths_Italy = bokeh_plot_2_lines(x=time_date_new[fit_range_3:fit_range_4], y=deceduti_italy.loc[(fit_range_3):(fit_range_4-1)], yy=ydata_3, 
                  title='Logistic Fitting Total Deaths: Italy', 
                  file_name="fit_total_deaths_Italy.html", 
                  x_label='Date', y_label='Total Deaths', 
                  legend_1='total deaths', legend_2='logistic fitting',
                  x_label_hover='date' , y_label_hover='total deaths OR logistic' , 
                  color_1='darkviolet', color_2='violet', y_minmax=None)

show(pfit_total_deaths_Italy)

In [141]:
- cov[0,1] / (np.sqrt(np.diag(cov)[0] * np.diag(cov)[1])) # Correlation coefficient for parameters 'K' and 'r'

-0.15388676115447186

In [142]:
cov[0,2] / (np.sqrt(np.diag(cov)[0] * np.diag(cov)[2])) # Correlation coefficient for parameters 'K' and 'P_0'

-0.13093471992055675

In [143]:
- cov[1,2] / (np.sqrt(np.diag(cov)[1] * np.diag(cov)[2])) # Correlation coefficient for parameters 'r' and 'P_0'

0.9994263001530143

In [144]:
residuals_3 = deceduti_italy.loc[(fit_range_3):(fit_range_4-1)] - ydata_3  #  Calculation of R^2
ss_res_3 = np.sum(residuals_3**2)
ss_tot_3 = np.sum((deceduti_italy.loc[(fit_range_3):(fit_range_4-1)] - np.mean(deceduti_italy.loc[(fit_range_3):(fit_range_4-1)]))**2)
r_squared_3 = 1 - (ss_res_3 / ss_tot_3)
r_squared_3

0.9920513800165277

---------------

In [145]:
max_deaths = []
max_deaths_up = []
max_deaths_down = []

# iii = len(deceduti_italy)
iii = 15

while (iii <= len(deceduti_italy)):
    fit_range_3 = iii - 15
    fit_range_4 = iii
    xdata_3 = np.linspace(fit_range_3, fit_range_4, fit_range_4 - fit_range_3)
    init_guess = [80000,0.001,0]
    fit = curve_fit(model_population, xdata_3, deceduti_italy.loc[fit_range_3:(fit_range_4-1)], p0=init_guess,  maxfev=10000)
    ans, cov = fit
    fit_K, fit_r, fit_P_0 = ans
    max_deaths.append(fit_K)
    max_deaths_up.append(fit_K + np.sqrt(np.diag(cov))[0])
    max_deaths_down.append(fit_K - np.sqrt(np.diag(cov))[0])
    iii = iii + 1

/Users/Angelo/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:8: RuntimeWarning: divide by zero encountered in double_scalars
  


In [146]:
len(max_deaths)

179

In [147]:
p_total_deaths_MAX_Italy = bokeh_plot_1_line(x=time_date_new + 14, y=max_deaths, 
                  title='Total Deaths MAX: Italy', 
                  file_name="total_deaths_MAX_Italy.html", 
                  x_label='Date', 
                  y_label='Total Deaths MAX', legend='total deaths max',
                  x_label_hover='date', y_label_hover='total deaths max',
                  color='darkviolet', y_minmax=(0,45000))

show(p_total_deaths_MAX_Italy)

In [148]:
p_total_deaths_MAX_2_Italy = bokeh_plot_N_lines(x=time_date_new + 14, y_list=[max_deaths,max_deaths_up,max_deaths_down], 
                  title='Total Deaths MAX: Italy', 
                  dim=[600, 450], 
                  x_label='Date', 
                  y_label='Total Deaths MAX', legend_list=['total deaths max','total deaths max UP','total deaths max DOWN'],
                  x_label_hover='date', y_label_hover='total deaths max/UP/DOWN',
                  color_list=['darkviolet','lightcoral','lightblue'],legend_location="bottom_right", y_minmax=(0,45000))

output_file("total_deaths_MAX_2_Italy.html")

show(p_total_deaths_MAX_2_Italy)

------------------

------------------

------------------

### ----- Gamma Distribution Fitting -----

In [149]:
fit_range_5 = len(nuovi_positivi_italy)   
xdata_4 = np.linspace(1, fit_range_5, fit_range_5)
# init_guess = [1,0.15,20000]
# init_guess = [6,1,500000]
fit = curve_fit(model_Gamma_distribution, xdata_4, nuovi_positivi_italy.loc[0:(fit_range_5-1)])
ans, cov = fit
fit_alpha, fit_beta, fit_Kmax = ans
fit_alpha, fit_beta, fit_Kmax

/Users/Angelo/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:12: RuntimeWarning: overflow encountered in multiply
  if sys.path[0] == '':
/Users/Angelo/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:12: RuntimeWarning: invalid value encountered in multiply
  if sys.path[0] == '':


(3.612289852136429, -0.10655080737691594, 235002.11186574475)

In [150]:
cov

array([[ 4.18022009e-02, -1.08310154e-03, -5.61181827e+02],
       [-1.08310154e-03,  2.98383807e-05,  1.64978594e+01],
       [-5.61181827e+02,  1.64978594e+01,  2.74474267e+07]])

In [151]:
np.sqrt(np.diag(cov))

array([2.04455865e-01, 5.46245189e-03, 5.23902917e+03])

In [152]:
ydata_4 = model_Gamma_distribution(xdata_4,fit_alpha,fit_beta,fit_Kmax)
ydata_4

array([5.07641664e-01, 5.58072253e+00, 2.17024453e+01, 5.51504643e+01,
       1.11004811e+02, 1.92793766e+02, 3.02447339e+02, 4.40411916e+02,
       6.05846176e+02, 7.96851257e+02, 1.01070685e+03, 1.24409636e+03,
       1.49331145e+03, 1.75443132e+03, 2.02347476e+03, 2.29652532e+03,
       2.56983103e+03, 2.83988086e+03, 3.10346046e+03, 3.35768990e+03,
       3.60004597e+03, 3.82837177e+03, 4.04087572e+03, 4.23612225e+03,
       4.41301600e+03, 4.57078121e+03, 4.70893764e+03, 4.82727436e+03,
       4.92582220e+03, 5.00482591e+03, 5.06471651e+03, 5.10608445e+03,
       5.12965396e+03, 5.13625878e+03, 5.12681971e+03, 5.10232385e+03,
       5.06380574e+03, 5.01233039e+03, 4.94897821e+03, 4.87483172e+03,
       4.79096404e+03, 4.69842895e+03, 4.59825257e+03, 4.49142647e+03,
       4.37890202e+03, 4.26158598e+03, 4.14033717e+03, 4.01596407e+03,
       3.88922330e+03, 3.76081879e+03, 3.63140171e+03, 3.50157080e+03,
       3.37187329e+03, 3.24280617e+03, 3.11481779e+03, 2.98830971e+03,
      

In [153]:
pfit_new_positive_Italy = bokeh_plot_2_lines(x=time_date_new, y=nuovi_positivi_italy.loc[0:(fit_range_5-1)], yy=ydata_4[0:fit_range_5], 
                  title='Gamma Distribution Fitting New Positive: Italy', 
                  file_name="fit_new_positive_Italy.html", 
                  x_label='Date', y_label='New Positive', 
                  legend_1='total cases', legend_2='Gamma fitting',
                  x_label_hover='date' , y_label_hover='new positive OR fitting' , 
                  color_1='blue', color_2='red', y_minmax=None)

show(pfit_new_positive_Italy)

In [154]:
- cov[0,1] / (np.sqrt(np.diag(cov)[0] * np.diag(cov)[1])) # Correlation coefficient for parameters 'alpha' and 'beta'

0.9697995435268663

In [155]:
cov[0,2] / (np.sqrt(np.diag(cov)[0] * np.diag(cov)[2])) # Correlation coefficient for parameters 'alpha' and 'Kmax'

-0.5239058021032174

In [156]:
- cov[1,2] / (np.sqrt(np.diag(cov)[1] * np.diag(cov)[2])) # Correlation coefficient for parameters 'beta' and 'Kmax'

-0.5764865181803216

In [157]:
residuals_4 = nuovi_positivi_italy.loc[0:(fit_range_5-1)] - ydata_4  #  Calculation of R^2
ss_res_4 = np.sum(residuals_4**2)
ss_tot_4 = np.sum((nuovi_positivi_italy.loc[0:(fit_range_5-1)] - np.mean(nuovi_positivi_italy.loc[0:(fit_range_5-1)]))**2)
r_squared_4 = 1 - (ss_res_4 / ss_tot_4)
r_squared_4

0.8987697176977775

----------------

In [158]:
fit_range_6 = time_date_new_extended.shape[0]
xdata_5 = np.linspace(1, fit_range_6, fit_range_6)
ydata_5 = model_Gamma_distribution(xdata_5,fit_alpha,fit_beta,fit_Kmax)
ydata_5

array([5.07641664e-01, 5.58072253e+00, 2.17024453e+01, 5.51504643e+01,
       1.11004811e+02, 1.92793766e+02, 3.02447339e+02, 4.40411916e+02,
       6.05846176e+02, 7.96851257e+02, 1.01070685e+03, 1.24409636e+03,
       1.49331145e+03, 1.75443132e+03, 2.02347476e+03, 2.29652532e+03,
       2.56983103e+03, 2.83988086e+03, 3.10346046e+03, 3.35768990e+03,
       3.60004597e+03, 3.82837177e+03, 4.04087572e+03, 4.23612225e+03,
       4.41301600e+03, 4.57078121e+03, 4.70893764e+03, 4.82727436e+03,
       4.92582220e+03, 5.00482591e+03, 5.06471651e+03, 5.10608445e+03,
       5.12965396e+03, 5.13625878e+03, 5.12681971e+03, 5.10232385e+03,
       5.06380574e+03, 5.01233039e+03, 4.94897821e+03, 4.87483172e+03,
       4.79096404e+03, 4.69842895e+03, 4.59825257e+03, 4.49142647e+03,
       4.37890202e+03, 4.26158598e+03, 4.14033717e+03, 4.01596407e+03,
       3.88922330e+03, 3.76081879e+03, 3.63140171e+03, 3.50157080e+03,
       3.37187329e+03, 3.24280617e+03, 3.11481779e+03, 2.98830971e+03,
      

In [159]:
pfit_2_new_positive_Italy = bokeh_plot_2_lines(x=time_date_new_extended, y=nuovi_positivi_italy.loc[0:(fit_range_5-1)], yy=ydata_5[0:fit_range_6], 
                  title='Gamma Distribution Fitting New Positive Extended: Italy', 
                  file_name="fit_2_new_positive_Italy.html", 
                  x_label='Date', y_label='New Positive', 
                  legend_1='total cases', legend_2='Gamma fitting',
                  x_label_hover='date' , y_label_hover='new positive OR fitting' , 
                  color_1='blue', color_2='red', y_minmax=None)

show(pfit_2_new_positive_Italy)

In [160]:
pfit_3_new_positive_Italy = bokeh_plot_N_lines(x=time_date_new_extended, y_list=[nuovi_positivi_italy.loc[0:(fit_range_5-1)],ydata_5[0:fit_range_6],SMA_new_positive['nuovi_positivi']], 
                  title='Gamma Distribution Fitting New Positive Extended: Italy', 
                  dim=[600, 450],
                  x_label='Date', 
                  y_label='New Positive', legend_list=['new positive','Gamma fitting','SMA 7 days'],
                  x_label_hover='date', y_label_hover='new positive/fitting/SMA 7',
                  color_list=['blue','red','lightblue'],legend_location="top_right", y_minmax=None)

output_file("fit_3_new_positive_Italy.html")

show(pfit_3_new_positive_Italy)

-----------------

------------

In [161]:
fit_range_7 = len(nuovi_deceduti)   
xdata_8 = np.linspace(1, fit_range_7, fit_range_7)
# init_guess = [1,0.15,20000]
fit = curve_fit(model_Gamma_distribution, xdata_8, nuovi_deceduti[0:(fit_range_7)])
ans, cov = fit
fit_alpha, fit_beta, fit_Kmax = ans
fit_alpha, fit_beta, fit_Kmax

/Users/Angelo/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:12: RuntimeWarning: overflow encountered in double_scalars
  if sys.path[0] == '':
/Users/Angelo/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:12: RuntimeWarning: overflow encountered in power
  if sys.path[0] == '':
/Users/Angelo/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:12: RuntimeWarning: invalid value encountered in multiply
  if sys.path[0] == '':
/Users/Angelo/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:12: RuntimeWarning: invalid value encountered in true_divide
  if sys.path[0] == '':


(4.298869561369421, -0.11219644021765426, 34050.38798605018)

In [162]:
cov

array([[ 3.41867870e-02, -7.99277278e-04, -5.75013735e+01],
       [-7.99277278e-04,  1.96941247e-05,  1.49721278e+00],
       [-5.75013735e+01,  1.49721278e+00,  3.42518503e+05]])

In [163]:
np.sqrt(np.diag(cov))

array([1.84896693e-01, 4.43780630e-03, 5.85250803e+02])

In [164]:
ydata_8 = model_Gamma_distribution(xdata_8,fit_alpha,fit_beta,fit_Kmax)
ydata_8

array([7.40382060e-03, 1.30262161e-01, 6.65403891e-01, 2.04858681e+00,
       4.77894006e+00, 9.35395199e+00, 1.62205045e+01, 2.57417388e+01,
       3.81776864e+01, 5.36770691e+01, 7.22776883e+01, 9.39130733e+01,
       1.18423398e+02, 1.45569027e+02, 1.75045388e+02, 2.06498169e+02,
       2.39538091e+02, 2.73754733e+02, 3.08729060e+02, 3.44044430e+02,
       3.79296005e+02, 4.14098536e+02, 4.48092572e+02, 4.80949192e+02,
       5.12373384e+02, 5.42106195e+02, 5.69925825e+02, 5.95647792e+02,
       6.19124329e+02, 6.40243143e+02, 6.58925676e+02, 6.75124973e+02,
       6.88823262e+02, 7.00029362e+02, 7.08775958e+02, 7.15116856e+02,
       7.19124241e+02, 7.20886003e+02, 7.20503161e+02, 7.18087420e+02,
       7.13758877e+02, 7.07643891e+02, 6.99873138e+02, 6.90579836e+02,
       6.79898160e+02, 6.67961833e+02, 6.54902891e+02, 6.40850619e+02,
       6.25930644e+02, 6.10264174e+02, 5.93967383e+02, 5.77150916e+02,
       5.59919515e+02, 5.42371750e+02, 5.24599841e+02, 5.06689571e+02,
      

In [165]:
pfit_new_deaths_Italy = bokeh_plot_2_lines(x=time_date_new, y=nuovi_deceduti[0:(fit_range_7)], yy=ydata_8[0:fit_range_7], 
                  title='Gamma Distribution Fitting New Deaths: Italy', 
                  file_name="fit_new_deaths_Italy.html", 
                  x_label='Date', y_label='New Deaths', 
                  legend_1='new deaths', legend_2='Gamma fitting',
                  x_label_hover='date' , y_label_hover='new deaths OR fitting' , 
                  color_1='darkviolet', color_2='red', y_minmax=None)

show(pfit_new_deaths_Italy)

In [166]:
- cov[0,1] / (np.sqrt(np.diag(cov)[0] * np.diag(cov)[1])) # Correlation coefficient for parameters 'alpha' and 'beta'

0.9740920113337481

In [167]:
cov[0,2] / (np.sqrt(np.diag(cov)[0] * np.diag(cov)[2])) # Correlation coefficient for parameters 'alpha' and 'Kmax'

-0.5313822666236354

In [168]:
- cov[1,2] / (np.sqrt(np.diag(cov)[1] * np.diag(cov)[2])) # Correlation coefficient for parameters 'beta' and 'Kmax'

-0.5764652928645523

In [169]:
residuals_8 = nuovi_deceduti[0:(fit_range_7)] - ydata_8  #  Calculation of R^2
ss_res_8 = np.sum(residuals_8**2)
ss_tot_8 = np.sum((nuovi_deceduti[0:(fit_range_7)] - np.mean(nuovi_deceduti[0:(fit_range_7)]))**2)
r_squared_8 = 1 - (ss_res_8 / ss_tot_8)
r_squared_8

0.9444483717176981

-----------

In [170]:
fit_range_8 = time_date_new_extended.shape[0]
xdata_9 = np.linspace(1, fit_range_8, fit_range_8)
ydata_9 = model_Gamma_distribution(xdata_9,fit_alpha,fit_beta,fit_Kmax)
ydata_9

array([7.40382060e-03, 1.30262161e-01, 6.65403891e-01, 2.04858681e+00,
       4.77894006e+00, 9.35395199e+00, 1.62205045e+01, 2.57417388e+01,
       3.81776864e+01, 5.36770691e+01, 7.22776883e+01, 9.39130733e+01,
       1.18423398e+02, 1.45569027e+02, 1.75045388e+02, 2.06498169e+02,
       2.39538091e+02, 2.73754733e+02, 3.08729060e+02, 3.44044430e+02,
       3.79296005e+02, 4.14098536e+02, 4.48092572e+02, 4.80949192e+02,
       5.12373384e+02, 5.42106195e+02, 5.69925825e+02, 5.95647792e+02,
       6.19124329e+02, 6.40243143e+02, 6.58925676e+02, 6.75124973e+02,
       6.88823262e+02, 7.00029362e+02, 7.08775958e+02, 7.15116856e+02,
       7.19124241e+02, 7.20886003e+02, 7.20503161e+02, 7.18087420e+02,
       7.13758877e+02, 7.07643891e+02, 6.99873138e+02, 6.90579836e+02,
       6.79898160e+02, 6.67961833e+02, 6.54902891e+02, 6.40850619e+02,
       6.25930644e+02, 6.10264174e+02, 5.93967383e+02, 5.77150916e+02,
       5.59919515e+02, 5.42371750e+02, 5.24599841e+02, 5.06689571e+02,
      

In [171]:
pfit_2_new_deaths_Italy = bokeh_plot_2_lines(x=time_date_new_extended, y=nuovi_deceduti[0:(fit_range_7)], yy=ydata_9[0:fit_range_8], 
                  title='Gamma Distribution Fitting New Deaths Extended: Italy', 
                  file_name="fit_2_new_deaths_Italy.html", 
                  x_label='Date', y_label='New Deaths', 
                  legend_1='new deaths', legend_2='Gamma fitting',
                  x_label_hover='date' , y_label_hover='new deaths OR fitting' , 
                  color_1='darkviolet', color_2='red', y_minmax=None)

show(pfit_2_new_deaths_Italy)

-----------------
-----------------
-----------------

In [172]:
s1_grid = bokeh_plot_N_lines(x=time_date_new, y_list=[total_cases_italy,total_positive_italy], 
                  title='Total Cases & Total Positive: Italy', 
                  dim=[470, 350], 
                  x_label='Date', 
                  y_label='Total Cases & Total Positive', legend_list=['total cases','total positive'],
                  x_label_hover='date', y_label_hover='total cases OR total positive',
                  color_list=['blue','red'],legend_location="top_left", y_minmax=None)

s2_grid = bokeh_plot_N_lines(x=time_date_new, y_list=[deceduti_italy,guariti_italy], 
                  title='Deaths & Recovered: Italy', 
                  dim=[470, 350], 
                  x_label='Date', 
                  y_label='Deaths & Recovered', legend_list=['deaths','recovered'],
                  x_label_hover='date', y_label_hover='deaths OR recovered',
                  color_list=['darkviolet','green'],legend_location="top_left", y_minmax=None)


s3_grid = bokeh_plot_N_lines(x=time_date_new + 6, y_list=[R_2_cases, R_2_deaths, R_2_guariti], 
                  title='Total Cases/Deaths/Guariti - Exponential Validity: Italy', 
                  dim=[470, 350], 
                  x_label='Date', 
                  y_label='R_squared', legend_list=['R_squared_cases', 'R_squared_deaths', 'R_squared_guariti'],
                  x_label_hover='date', y_label_hover='R_squared_cases/deaths/guariti',
                  color_list=['blue', 'darkviolet', 'green'], legend_location="bottom_left", y_minmax=None)

s4_grid = bokeh_plot_N_lines(x=time_date_new + 14, y_list=[max_population_up,max_population_down,max_population], 
                  title='Max Total Cases - Logistic Fitting: Italy', 
                  dim=[470, 350], 
                  x_label='Date', 
                  y_label='Total Cases MAX', legend_list=['total cases max UP','total cases max DOWN','total cases max'],
                  x_label_hover='date', y_label_hover='total cases max/UP/DOWN',
                  color_list=['lightcoral','lightblue','blue'],legend_location="bottom_right", y_minmax=(0,300000))

s5_grid = bokeh_plot_N_lines(x=time_date_new + 14, y_list=[max_deaths_up,max_deaths_down,max_deaths], 
                  title='Max Total Deaths - Logistic Fitting: Italy', 
                  dim=[470, 350], 
                  x_label='Date', 
                  y_label='Total Deaths MAX', legend_list=['total deaths max UP','total deaths max DOWN','total deaths max'],
                  x_label_hover='date', y_label_hover='total deaths max/UP/DOWN',
                  color_list=['lightcoral','lightblue','darkviolet'],legend_location="bottom_right", y_minmax=(0,45000))

s6_grid = bokeh_plot_N_lines(x=time_date_new_extended, y_list=[nuovi_positivi_italy.loc[0:(fit_range_5-1)],ydata_5[0:fit_range_6]], 
                  title='New Positive - Gamma Distribution Fitting: Italy', 
                  dim=[470, 350],
                  x_label='Date', 
                  y_label='New Positive', legend_list=['new positive','Gamma fitting'],
                  x_label_hover='date', y_label_hover='new positive/fitting',
                  color_list=['blue','lightcoral'],legend_location="top_right", y_minmax=None)

s7_grid = bokeh_plot_N_lines(x=time_date_new_extended, y_list=[nuovi_deceduti[0:(fit_range_7)],ydata_9[0:fit_range_8]], 
                  title='New Deaths - Gamma Distribution Fitting: Italy', 
                  dim=[470, 350],
                  x_label='Date', 
                  y_label='New Deaths', legend_list=['new deaths','Gamma fitting'],
                  x_label_hover='date', y_label_hover='new deaths/fitting',
                  color_list=['darkviolet','lightcoral'],legend_location="top_right", y_minmax=None)

In [173]:
p_grid = gridplot([[s1_grid, s2_grid, s3_grid], [s4_grid, s5_grid], [s6_grid, s7_grid]])

output_file("grid_1.html")

show(p_grid)