<h1 align=center><font size = 7>Italian Trends Covid-19</font></h1>

------------

<font size = 5> **Author**: Angelo Di Marco

------------

In this Notebook, we analyze the spreading of the new coronavirus in Italy.

## Libraries and Functions

First we import the required libraries and define the bokeh plot functions:

In [1]:
import numpy as np

import pandas as pd

from math import pi

from bokeh.plotting import figure, output_file, show, output_notebook, gridplot
from bokeh.models import DatetimeTickFormatter, BasicTickFormatter, NumeralTickFormatter
from bokeh.models import HoverTool
from bokeh.layouts import row

output_notebook()

Loading BokehJS ...

In [2]:
def datetime(x):
    return np.array(x, dtype=np.datetime64)

---------------------

### ----- Plot function 1 line -----

In [3]:
def bokeh_plot_1_line(x, y, title, file_name, x_label, y_label, legend, x_label_hover, y_label_hover, color, y_minmax):
    
    output_file(file_name)
    
    p = figure(title=title, x_axis_type='datetime', x_axis_label=x_label, y_axis_label=y_label, width=600, height=450, y_range=y_minmax)
    
    p.line(x.squeeze(), y, color=color, line_width=4, legend_label=legend)
    p.circle(x.squeeze(), y, fill_color="white", line_color=color, size=6)
    
    p.xaxis.formatter = DatetimeTickFormatter(
#         hours=["%d %B %Y"],
#         days=["%Y %m %d"],
        days=["%d %B"],
#         months=["%d %B %Y"],
#         years=["%d %B %Y"],
    )
    p.xaxis.major_label_orientation = pi/4
  
    p.yaxis.formatter = BasicTickFormatter(use_scientific = False)
#     p.left[0].formatter.use_scientific = False
    p.yaxis.formatter = NumeralTickFormatter(format = '0,0')
    
    p.axis.minor_tick_in = -5
    p.axis.minor_tick_out = -3
    
    p.legend.location = "top_left"
    
    p.add_tools(HoverTool(
    tooltips=[
        ( x_label_hover,   '@x{%d %B}'    ),
        ( y_label_hover, '@y{0.}'      ),
    ],

    formatters={
           '@x'  : 'datetime', # use 'datetime' formatter for 'date' field
#            '@y'  : 'printf',   # use 'printf' formatter for 'adj close' field
                                  # use default 'numeral' formatter for other fields
    },

    # display a tooltip whenever the cursor is vertically in line with a glyph
    mode='vline'
    ))

    return p
#     show(p)

### ----- Plot function 2 lines -----

In [4]:
def bokeh_plot_2_lines(x, y, yy, title, file_name, x_label, y_label, legend_1, legend_2, x_label_hover, y_label_hover, color_1, color_2, y_minmax):
    
    output_file(file_name)
    
    p = figure(title=title, x_axis_type='datetime', x_axis_label=x_label, y_axis_label=y_label, width=600, height=450, y_range=y_minmax)
    
    p.line(x, y, color=color_1, line_width=4, legend_label=legend_1)
    p.circle(x, y, fill_color="white", line_color=color_1, size=6)
    
    p.line(x, yy, color=color_2, line_width=4, legend_label=legend_2)
    p.circle(x, yy, fill_color="white", line_color=color_2, size=6)
    
    p.xaxis.formatter=DatetimeTickFormatter(
#         hours=["%d %B %Y"],
#         days=["%Y %m %d"],
    days=["%d %B"],
#         months=["%d %B %Y"],
#         years=["%d %B %Y"],
    )
    p.xaxis.major_label_orientation = pi/4
  
    p.yaxis.formatter = BasicTickFormatter(use_scientific=False)
#     p.left[0].formatter.use_scientific = False
    p.yaxis.formatter = NumeralTickFormatter(format = '0,0')
    
    p.axis.minor_tick_in = -5
    p.axis.minor_tick_out = -3
    
    p.legend.location = "top_left"
    
    p.add_tools(HoverTool(
    tooltips=[
        ( x_label_hover,   '@x{%d %B}' ),
        ( y_label_hover, '@y{0.}' ),
#         ( 'label yy', '@yy' ),
    ],

    formatters={
           '@x'  : 'datetime', # use 'datetime' formatter for 'date' field
#            '@y'  : 'printf',   # use 'printf' formatter for 'adj close' field
                                  # use default 'numeral' formatter for other fields
    },

    # display a tooltip whenever the cursor is vertically in line with a glyph
    mode='vline'
    ))
    
    return p  
#     show(p)

### ----- Plot function N lines -----

In [5]:
def bokeh_plot_N_lines(x, y_list, title, dim, x_label, y_label, legend_list, x_label_hover, y_label_hover, color_list, legend_location, y_minmax):
    
#     output_file(file_name)
    
    p = figure(title=title, x_axis_type='datetime', x_axis_label=x_label, y_axis_label=y_label, width=dim[0], height=dim[1], y_range=y_minmax)
    
    for iii in range(0,len(y_list)):
        p.line(x, y_list[iii], color=color_list[iii], line_width=4, legend_label=legend_list[iii])
        p.circle(x, y_list[iii], fill_color="white", line_color=color_list[iii], size=5)
        
    
    p.xaxis.formatter=DatetimeTickFormatter(
#         hours=["%d %B %Y"],
#         days=["%Y %m %d"],
    days=["%d %B"],
#         months=["%d %B %Y"],
#         years=["%d %B %Y"],
    )
    p.xaxis.major_label_orientation = pi/4
  
    p.yaxis.formatter = BasicTickFormatter(use_scientific=False)
#     p.left[0].formatter.use_scientific = False
#     p.yaxis.formatter = NumeralTickFormatter(format = '0,0')
    p.yaxis.formatter.use_scientific = False
    
    p.axis.minor_tick_in = -5
    p.axis.minor_tick_out = -3
    
    p.legend.location = legend_location
    
    p.add_tools(HoverTool(
    tooltips=[
        ( x_label_hover,   '@x{%d %B}' ),
        ( y_label_hover, '@y{0[.]000}' ),
#         ( 'label yy', '@yy' ),
    ],

    formatters={
           '@x'  : 'datetime', # use 'datetime' formatter for 'date' field
#            '@y'  : 'printf',   # use 'printf' formatter for 'adj close' field
#            '@y'  : 'numeral',   # use 'printf' formatter for 'adj close' field
                                  # use default 'numeral' formatter for other fields
    },

    # display a tooltip whenever the cursor is vertically in line with a glyph
    mode='vline'
    ))
    
    return p  
#     show(p)

-----------------

## Data Sources

We importe the CSV files directly from the official GitHub source of the Protezione Civile:

In [6]:
data_links = {'nazionale':'https://raw.githubusercontent.com/pcm-dpc/COVID-19/master/dati-andamento-nazionale/dpc-covid19-ita-andamento-nazionale.csv',\
              'regioni':'https://raw.githubusercontent.com/pcm-dpc/COVID-19/master/dati-regioni/dpc-covid19-ita-regioni.csv',\
              'province':'https://raw.githubusercontent.com/pcm-dpc/COVID-19/master/dati-province/dpc-covid19-ita-province.csv'}

-----------------

## National Trends

In [7]:
path_nazionale = data_links['nazionale']
print('The path to the Raw CSV file for the national data is : \n', path_nazionale)
df_nazionale = pd.read_csv(path_nazionale)
df_nazionale.head()

The path to the Raw CSV file for the national data is : 
 https://raw.githubusercontent.com/pcm-dpc/COVID-19/master/dati-andamento-nazionale/dpc-covid19-ita-andamento-nazionale.csv


data stato  ricoverati_con_sintomi  terapia_intensiva  \
0  2020-02-24T18:00:00   ITA                     101                 26   
1  2020-02-25T18:00:00   ITA                     114                 35   
2  2020-02-26T18:00:00   ITA                     128                 36   
3  2020-02-27T18:00:00   ITA                     248                 56   
4  2020-02-28T18:00:00   ITA                     345                 64   

   totale_ospedalizzati  isolamento_domiciliare  totale_positivi  \
0                   127                      94              221   
1                   150                     162              311   
2                   164                     221              385   
3                   304                     284              588   
4                   409                     412              821   

   variazione_totale_positivi  nuovi_positivi  dimessi_guariti  deceduti  \
0                           0             221                1         7   
1                          90              93                1        10   
2                          74              78                3        12   
3                         203             250               45        17   
4                         233             238               46        21   

   casi_da_sospetto_diagnostico  casi_da_screening  totale_casi  tamponi  \
0                           NaN                NaN          229     4324   
1                           NaN                NaN          322     8623   
2                           NaN                NaN          400     9587   
3                           NaN                NaN          650    12014   
4                           NaN                NaN          888    15695   

   casi_testati note  
0           NaN  NaN  
1           NaN  NaN  
2           NaN  NaN  
3           NaN  NaN  
4           NaN  NaN

In [8]:
df_nazionale.shape

(143, 17)

------------

### Date Formatting

In [9]:
time_date = df_nazionale['data']
time_date.head()

0    2020-02-24T18:00:00
1    2020-02-25T18:00:00
2    2020-02-26T18:00:00
3    2020-02-27T18:00:00
4    2020-02-28T18:00:00
Name: data, dtype: object

In [10]:
time_date_new = pd.to_datetime(time_date).dt.date
time_date_new.head()

0    2020-02-24
1    2020-02-25
2    2020-02-26
3    2020-02-27
4    2020-02-28
Name: data, dtype: object

In [11]:
time_date_new = datetime(time_date_new)
time_date_new

array(['2020-02-24', '2020-02-25', '2020-02-26', '2020-02-27',
       '2020-02-28', '2020-02-29', '2020-03-01', '2020-03-02',
       '2020-03-03', '2020-03-04', '2020-03-05', '2020-03-06',
       '2020-03-07', '2020-03-08', '2020-03-09', '2020-03-10',
       '2020-03-11', '2020-03-12', '2020-03-13', '2020-03-14',
       '2020-03-15', '2020-03-16', '2020-03-17', '2020-03-18',
       '2020-03-19', '2020-03-20', '2020-03-21', '2020-03-22',
       '2020-03-23', '2020-03-24', '2020-03-25', '2020-03-26',
       '2020-03-27', '2020-03-28', '2020-03-29', '2020-03-30',
       '2020-03-31', '2020-04-01', '2020-04-02', '2020-04-03',
       '2020-04-04', '2020-04-05', '2020-04-06', '2020-04-07',
       '2020-04-08', '2020-04-09', '2020-04-10', '2020-04-11',
       '2020-04-12', '2020-04-13', '2020-04-14', '2020-04-15',
       '2020-04-16', '2020-04-17', '2020-04-18', '2020-04-19',
       '2020-04-20', '2020-04-21', '2020-04-22', '2020-04-23',
       '2020-04-24', '2020-04-25', '2020-04-26', '2020-

-----------

In [12]:
time_date_new_extended = pd.date_range(start=time_date_new[0], periods=2*time_date.shape[0])
time_date_new_extended

DatetimeIndex(['2020-02-24', '2020-02-25', '2020-02-26', '2020-02-27',
               '2020-02-28', '2020-02-29', '2020-03-01', '2020-03-02',
               '2020-03-03', '2020-03-04',
               ...
               '2020-11-26', '2020-11-27', '2020-11-28', '2020-11-29',
               '2020-11-30', '2020-12-01', '2020-12-02', '2020-12-03',
               '2020-12-04', '2020-12-05'],
              dtype='datetime64[ns]', length=286, freq='D')

In [13]:
time_date_new_extended[0:4]

DatetimeIndex(['2020-02-24', '2020-02-25', '2020-02-26', '2020-02-27'], dtype='datetime64[ns]', freq='D')

------------------

### Total Cases

In [14]:
total_cases_italy = df_nazionale['totale_casi']
total_cases_italy.head()

0    229
1    322
2    400
3    650
4    888
Name: totale_casi, dtype: int64

### Total Positive

In [15]:
total_positive_italy = df_nazionale['totale_positivi']
total_positive_italy.head()

0    221
1    311
2    385
3    588
4    821
Name: totale_positivi, dtype: int64

-------------------------

In [16]:
p_total_cases_Italy = bokeh_plot_1_line(x=time_date_new, y=total_cases_italy, 
                  title='Total Cases: Italy', 
                  file_name="total_cases_Italy.html", 
                  x_label='Date', 
                  y_label='Total Cases', legend='total cases',
                  x_label_hover='date', y_label_hover='total cases',
                  color='blue', y_minmax=None)

show(p_total_cases_Italy)

In [17]:
p_total_cases_positive_Italy = bokeh_plot_2_lines(x=time_date_new, y=total_cases_italy, yy=total_positive_italy, 
                  title='Total Cases vs Total Positive: Italy', 
                  file_name="total_cases_positive_Italy.html", 
                  x_label='Date', y_label='Total Cases & Total Positive', 
                  legend_1='total cases', legend_2='total positive',
                  x_label_hover='date' , y_label_hover='total cases OR positive' , 
                  color_1='blue', color_2='firebrick', y_minmax=None)

show(p_total_cases_positive_Italy)

In [18]:
p_total_cases_positive_2_Italy = bokeh_plot_N_lines(x=time_date_new, y_list=[total_cases_italy,total_positive_italy], 
                  title='Total Cases & Total Positive: Italy', 
                  dim=[600, 450], 
                  x_label='Date', 
                  y_label='Total Cases & Total Positive', legend_list=['total cases','total positive'],
                  x_label_hover='date', y_label_hover='total cases OR total positive',
                  color_list=['blue','red'],legend_location="top_left", y_minmax=None)

output_file("total_cases_positive_2_Italy.html")

show(p_total_cases_positive_2_Italy)

------------------

### Deaths

In [19]:
deceduti_italy = df_nazionale['deceduti']
deceduti_italy.head()

0     7
1    10
2    12
3    17
4    21
Name: deceduti, dtype: int64

------------------

### Recovered

In [20]:
guariti_italy = df_nazionale['dimessi_guariti']
guariti_italy.head()

0     1
1     1
2     3
3    45
4    46
Name: dimessi_guariti, dtype: int64

In [21]:
p_deaths_recovered_Italy = bokeh_plot_2_lines(x=time_date_new, y=deceduti_italy, yy=guariti_italy, 
                  title='Deaths vs Recovered: Italy', 
                  file_name="deaths_recovered_Italy.html", 
                  x_label='Date', y_label='Deaths & Recovered', 
                  legend_1='deaths', legend_2='recovered',
                  x_label_hover='date' , y_label_hover='deaths OR recovered' , 
                  color_1='darkviolet', color_2='green', y_minmax=None)

show(p_deaths_recovered_Italy)

------------------

### New Deaths

In [22]:
len(deceduti_italy)
    

143

In [23]:
nuovi_deceduti = [0]
i = 0
while (i < len(deceduti_italy)-1):
#     print(deceduti_italy.iloc[i + 1] - deceduti_italy.iloc[i])
    temp = deceduti_italy.iloc[i + 1] - deceduti_italy.iloc[i]
    nuovi_deceduti.append(temp)
    i = i + 1

In [24]:
p_new_deaths_Italy = bokeh_plot_1_line(x=time_date_new, y=nuovi_deceduti, 
                  title='New Deaths: Italy', 
                  file_name="new_deaths_Italy.html", 
                  x_label='Date', 
                  y_label='New Deaths', legend='new deaths',
                  x_label_hover='date', y_label_hover='new deaths',
                  color='darkviolet', y_minmax=None)

show(p_new_deaths_Italy)

In [25]:
nuovi_deceduti_df = pd.DataFrame(nuovi_deceduti)

SMA_new_deaths = nuovi_deceduti_df[:].rolling(window=7).mean()
SMA_new_deaths_2 = nuovi_deceduti_df[:].rolling(window=10).mean()

In [26]:
SMA_new_deaths.head()

0
0 NaN
1 NaN
2 NaN
3 NaN
4 NaN

In [27]:
p_new_deaths_SMA_Italy = bokeh_plot_2_lines(x=time_date_new, y=nuovi_deceduti, yy=SMA_new_deaths[0], 
                  title='New Deaths: Italy', 
                  file_name="new_deaths_SMA_Italy.html", 
                  x_label='Date', y_label='New Deaths', 
                  legend_1='new deaths', legend_2='SMA 7 days',
                  x_label_hover='date' , y_label_hover='new deaths OR SMA 7' , 
                  color_1='darkviolet', color_2='lightblue', y_minmax=None)

show(p_new_deaths_SMA_Italy)

------------------

### New Positive

In [28]:
nuovi_positivi_italy = df_nazionale['nuovi_positivi']
nuovi_positivi_italy.head()

0    221
1     93
2     78
3    250
4    238
Name: nuovi_positivi, dtype: int64

In [29]:
p_new_positive_Italy = bokeh_plot_1_line(x=time_date_new, y=nuovi_positivi_italy, 
                  title='New Positive: Italy', 
                  file_name="new_positive_Italy.html", 
                  x_label='Date', 
                  y_label='New Positive', legend='new positive',
                  x_label_hover='date', y_label_hover='new positive',
                  color='blue', y_minmax=None)

show(p_new_positive_Italy)

In [30]:
new_positive_df = pd.DataFrame(nuovi_positivi_italy)

SMA_new_positive = new_positive_df[:].rolling(window=7).mean()
SMA_new_positive_2 = new_positive_df[:].rolling(window=10).mean()

In [31]:
SMA_new_positive.head()

nuovi_positivi
0             NaN
1             NaN
2             NaN
3             NaN
4             NaN

In [32]:
p_new_positive_SMA_Italy = bokeh_plot_2_lines(x=time_date_new, y=nuovi_positivi_italy, yy=SMA_new_positive['nuovi_positivi'], 
                  title='New Positive: Italy', 
                  file_name="new_positive_SMA_Italy.html", 
                  x_label='Date', y_label='New Positive', 
                  legend_1='new positive', legend_2='SMA 7 days',
                  x_label_hover='date' , y_label_hover='new_positive OR SMA 7' , 
                  color_1='blue', color_2='lightcoral', y_minmax=None)

show(p_new_positive_SMA_Italy)

------------------------

In [33]:
# show(row(p_new_positive_Italy,p_new_deaths_Italy))

In [34]:
p_new_deaths_positive_Italy = bokeh_plot_2_lines(x=time_date_new, y=nuovi_deceduti, yy=nuovi_positivi_italy, 
                  title='New Deaths vs New Positive: Italy', 
                  file_name="new_deaths_positive_Italy.html", 
                  x_label='Date', y_label='New Deaths & New Positive', 
                  legend_1='new deaths', legend_2='new positive',
                  x_label_hover='date' , y_label_hover='new deaths OR new positive' , 
                  color_1='darkviolet', color_2='blue', y_minmax=None)

show(p_new_deaths_positive_Italy)

---------------------

### Total Hospitalized

In [35]:
total_hospital_italy = df_nazionale['totale_ospedalizzati']
total_hospital_italy.head()

0    127
1    150
2    164
3    304
4    409
Name: totale_ospedalizzati, dtype: int64

---------------------

### Intensive Care

In [36]:
intensive_care_italy = df_nazionale['terapia_intensiva']
intensive_care_italy.head()

0    26
1    35
2    36
3    56
4    64
Name: terapia_intensiva, dtype: int64

In [37]:
p_total_hospitalized_Italy = bokeh_plot_1_line(x=time_date_new, y=total_hospital_italy, 
                  title='Total Hospitalized: Italy', 
                  file_name="total_hospitalized_Italy.html", 
                  x_label='Date', 
                  y_label='Total Hospitalized', legend='total hospitalized',
                  x_label_hover='date', y_label_hover='total hospitalized',
                  color='orange', y_minmax=None)
# output_file("total_cases_Italy.html")
show(p_total_hospitalized_Italy)

In [38]:
p_intensive_care_Italy = bokeh_plot_1_line(x=time_date_new, y=intensive_care_italy, 
                  title='Intensive Care: Italy', 
                  file_name="intensive_care_Italy.html", 
                  x_label='Date', 
                  y_label='Intensive Care', legend='intensive care',
                  x_label_hover='date', y_label_hover='intensive care',
                  color='GoldenRod', y_minmax=None)
# output_file("total_cases_Italy.html")
show(p_intensive_care_Italy)

In [39]:
p_hospitalized_intensivecare_Italy = bokeh_plot_2_lines(x=time_date_new, y=total_hospital_italy, yy=intensive_care_italy, 
                  title='Total Hospitalized vs Intensive Care: Italy', 
                  file_name="hospitalized_intensivecare_Italy.html", 
                  x_label='Date', y_label='Total Hospitalized & Intensive Care', 
                  legend_1='total hospitalized', legend_2='intensive care',
                  x_label_hover='date' , y_label_hover='hospitalized OR intensive care' , 
                  color_1='orange', color_2='GoldenRod', y_minmax=None)

show(p_hospitalized_intensivecare_Italy)

----------

-------------------------
# Fitting

In [40]:
from scipy.optimize import curve_fit
from scipy.special import gamma

def model_exp(x,a,b):
    return a * np.exp(b * x)

def model_population(x,K,r,P_0):
    den = 1 + ((K - P_0) / P_0) * np.exp(- r * x)
    return K / den

def model_Gamma_distribution(x,alpha,beta,Kmax):
    return Kmax * np.abs(beta)**(np.abs(alpha) + 1) * x**(np.abs(alpha)) * np.exp(- np.abs(beta) * x) / gamma((np.abs(alpha) + 1))

------------------

### ----- Exponential Fitting -----

In [41]:
fit_range = 28   # best fit when fit_range = 28 namely March 22
xdata = np.linspace(0, fit_range, fit_range)
init_guess = [5000, 0.001]
fit = curve_fit(model_exp, xdata, total_cases_italy.loc[0:(fit_range-1)], p0=init_guess)
ans, cov = fit
fit_a, fit_b = ans
fit_a, fit_b

(1268.6044974646502, 0.13890844390214907)

In [42]:
cov

array([[ 9.92195154e+03, -3.07812476e-01],
       [-3.07812476e-01,  9.74343219e-06]])

In [43]:
np.sqrt(np.diag(cov))

array([9.96089933e+01, 3.12144713e-03])

In [44]:
ydata = model_exp(xdata,fit_a,fit_b)
ydata

array([ 1268.60449746,  1465.16912064,  1692.1905577 ,  1954.38795648,
        2257.21167574,  2606.95658312,  3010.89290796,  3477.41736932,
        4016.22772053,  4638.52433861,  5357.24304922,  6187.32402664,
        7146.02235868,  8253.26673226,  9532.07369566, 11009.02610895,
       12714.82572808, 14684.9314095 , 16960.29620175, 19588.21864602,
       22623.32598204, 26128.70969733, 30177.23702472, 34853.06565057,
       40253.3931204 , 46490.47730694, 53693.96994092, 62013.61171197])

In [45]:
pfit_total_cases_Italy = bokeh_plot_2_lines(x=time_date_new[0:(fit_range)], y=total_cases_italy.loc[0:(fit_range-1)], yy=ydata[0:fit_range], 
                  title='Exponential Fitting Total Cases: Italy', 
                  file_name="fit_total_cases_Italy.html", 
                  x_label='Date', y_label='Total Cases', 
                  legend_1='total cases', legend_2='exponential fitting',
                  x_label_hover='date' , y_label_hover='total cases OR fitting' , 
                  color_1='blue', color_2='red', y_minmax=None)

show(pfit_total_cases_Italy)

In [46]:
- cov[0,1] / (np.sqrt(np.diag(cov)[0] * np.diag(cov)[1])) # Correlation coefficient for parameters 'a' and 'b'

0.9899919975413152

In [47]:
residuals = total_cases_italy.loc[0:(fit_range-1)] - ydata  #  Calculation of R^2
ss_res = np.sum(residuals**2)
ss_tot = np.sum((total_cases_italy.loc[0:(fit_range-1)] - np.mean(total_cases_italy.loc[0:(fit_range-1)]))**2)
r_squared = 1 - (ss_res / ss_tot)
r_squared

0.9942027803878379

---------------

In [48]:
fit_range = 49   # best fit when fit_range = 28 namely March 22
xdata = np.linspace(0, fit_range, fit_range)
init_guess = [5000, 0.001]
fit = curve_fit(model_exp, xdata, total_cases_italy.loc[0:(fit_range-1)], p0=init_guess)
ans, cov = fit
fit_a, fit_b = ans
fit_a, fit_b

(10273.505399700898, 0.058660707522345125)

In [49]:
cov

array([[ 1.70490033e+06, -3.88568817e+00],
       [-3.88568817e+00,  9.19880384e-06]])

In [50]:
np.sqrt(np.diag(cov))

array([1.30571832e+03, 3.03295299e-03])

In [51]:
ydata = model_exp(xdata,fit_a,fit_b)
ydata

array([ 10273.5053997 ,  10907.50512106,  11580.63030457,  12295.29546516,
        13054.06412256,  13859.65799674,  14714.96677074,  15623.05845605,
        16587.19039764,  17610.82095811,  18697.62192291,  19851.49167117,
        21076.56915918,  22377.24876699,  23758.19606113,  25224.3645301 ,
        26781.01335261,  28433.72626244,  30188.43157735,  32051.42346413,
        34029.38451587,  36129.40972262,  38359.03192126,  40726.24881594,
        43239.55166602,  45907.95574442,  48741.03267559,  51748.94476916,
        54942.48147235,  58333.09807195,  61932.95678471,  65754.97038346,
        69812.84851553,  74121.14687954,  78695.31943703,  83551.77384615,
        88707.93031628,  94182.28409475,  99994.47180965, 106165.34190689,
       112717.02943402, 119673.03543912, 127058.3112696 , 134899.34807324,
       143224.27182249, 152062.94420302, 161447.06972815, 171410.30946374,
       181988.4017711 ])

In [52]:
- cov[0,1] / (np.sqrt(np.diag(cov)[0] * np.diag(cov)[1])) # Correlation coefficient for parameters 'a' and 'b'

0.9811892216342538

In [53]:
residuals = total_cases_italy.loc[0:(fit_range-1)] - ydata  #  Calculation of R^2
ss_res = np.sum(residuals**2)
ss_tot = np.sum((total_cases_italy.loc[0:(fit_range-1)] - np.mean(total_cases_italy.loc[0:(fit_range-1)]))**2)
r_squared = 1 - (ss_res / ss_tot)
r_squared

0.940258800232746

In [54]:
pfit_total_cases_Italy = bokeh_plot_2_lines(x=time_date_new[0:(fit_range)], y=total_cases_italy.loc[0:(fit_range-1)], yy=ydata[0:fit_range], 
                  title='Exponential Fitting Total Cases: Italy', 
                  file_name="fit_total_cases_Italy.html", 
                  x_label='Date', y_label='Total Cases', 
                  legend_1='total cases', legend_2='exponential fitting',
                  x_label_hover='date' , y_label_hover='total cases OR fitting' , 
                  color_1='blue', color_2='red', y_minmax=None)

show(pfit_total_cases_Italy)

------------------------

------------------------

In [55]:
R_2_cases = []
Correlation_A_B = []
iii = 7

while(iii <= len(total_cases_italy)):
    fit_range = iii   # best fit when fit_range = 28 namely March 22
    xdata = np.linspace(0, fit_range, fit_range)
    init_guess = [5000, 0.001]
    fit = curve_fit(model_exp, xdata, total_cases_italy.loc[0:(fit_range-1)], p0=init_guess)
    ans, cov = fit
    fit_a, fit_b = ans
    fit_a, fit_b
    ydata = model_exp(xdata,fit_a,fit_b)
    residuals = total_cases_italy.loc[0:(fit_range-1)] - ydata  #  Calculation of R^2
    ss_res = np.sum(residuals**2)
    ss_tot = np.sum((total_cases_italy.loc[0:(fit_range-1)] - np.mean(total_cases_italy.loc[0:(fit_range-1)]))**2)
    r_squared = 1 - (ss_res / ss_tot)
    R_2_cases.append(r_squared)
    correlation_ab = - cov[0,1] / (np.sqrt(np.diag(cov)[0] * np.diag(cov)[1]))
    Correlation_A_B.append(correlation_ab)
    iii = iii + 1

In [56]:
p_total_cases_exp_val_Italy = bokeh_plot_N_lines(x=time_date_new + 6, y_list=[R_2_cases, Correlation_A_B], 
                  title='Total Cases Exponential Validity: Italy', 
                  dim=[600, 450], 
                  x_label='Date', 
                  y_label='R_squared', legend_list=['R_squared', 'Corr_A_B'],
                  x_label_hover='date', y_label_hover='R_squared/Corr_A_B',
                  color_list=['blue', 'lightblue'],legend_location="top_right", y_minmax=None)

output_file("total_cases_exponential_validity_Italy.html")

show(p_total_cases_exp_val_Italy)

--------------------

In [57]:
R_2_deaths = []
Correlation_A_B = []
iii = 7

while(iii <= len(deceduti_italy)):
    fit_range = iii   # best fit when fit_range = 28 namely March 22
    xdata = np.linspace(0, fit_range, fit_range)
    init_guess = [5000, 0.001]
    fit = curve_fit(model_exp, xdata, deceduti_italy.loc[0:(fit_range-1)], p0=init_guess)
    ans, cov = fit
    fit_a, fit_b = ans
    fit_a, fit_b
    ydata = model_exp(xdata,fit_a,fit_b)
    residuals = deceduti_italy.loc[0:(fit_range-1)] - ydata  #  Calculation of R^2
    ss_res = np.sum(residuals**2)
    ss_tot = np.sum((deceduti_italy.loc[0:(fit_range-1)] - np.mean(deceduti_italy.loc[0:(fit_range-1)]))**2)
    r_squared = 1 - (ss_res / ss_tot)
    R_2_deaths.append(r_squared)
    correlation_ab = - cov[0,1] / (np.sqrt(np.diag(cov)[0] * np.diag(cov)[1]))
    Correlation_A_B.append(correlation_ab)
    iii = iii + 1

In [58]:
p_total_deaths_exp_val_Italy = bokeh_plot_N_lines(x=time_date_new + 6, y_list=[R_2_deaths, Correlation_A_B], 
                  title='Total Deaths Exponential Validity: Italy', 
                  dim=[600, 450], 
                  x_label='Date', 
                  y_label='R_squared', legend_list=['R_squared', 'Corr_A_B'],
                  x_label_hover='date', y_label_hover='R_squared/Corr_A_B',
                  color_list=['darkviolet', 'violet'],legend_location="top_right", y_minmax=None)

output_file("total_deaths_exponential_validity_Italy.html")

show(p_total_deaths_exp_val_Italy)

-----------------

In [59]:
p_total_cases_deaths_exp_val_Italy = bokeh_plot_N_lines(x=time_date_new + 6, y_list=[R_2_cases, R_2_deaths], 
                  title='Total Cases/Deaths Exponential Validity: Italy', 
                  dim=[600, 450], 
                  x_label='Date', 
                  y_label='R_squared', legend_list=['R_squared_cases', 'R_squared_deaths'],
                  x_label_hover='date', y_label_hover='R_squared_cases/deaths',
                  color_list=['blue', 'darkviolet'],legend_location="top_right", y_minmax=None)

output_file("total_cases_deaths_exponential_validity_Italy.html")

show(p_total_cases_deaths_exp_val_Italy)

--------------------

In [60]:
R_2_guariti = []
Correlation_A_B = []
iii = 7

while(iii <= len(guariti_italy)):
    fit_range = iii   # best fit when fit_range = 28 namely March 22
    xdata = np.linspace(0, fit_range, fit_range)
    init_guess = [5000, 0.001]
    fit = curve_fit(model_exp, xdata, guariti_italy.loc[0:(fit_range-1)], p0=init_guess)
    ans, cov = fit
    fit_a, fit_b = ans
    fit_a, fit_b
    ydata = model_exp(xdata,fit_a,fit_b)
    residuals = guariti_italy.loc[0:(fit_range-1)] - ydata  #  Calculation of R^2
    ss_res = np.sum(residuals**2)
    ss_tot = np.sum((guariti_italy.loc[0:(fit_range-1)] - np.mean(guariti_italy.loc[0:(fit_range-1)]))**2)
    r_squared = 1 - (ss_res / ss_tot)
    R_2_guariti.append(r_squared)
    correlation_ab = - cov[0,1] / (np.sqrt(np.diag(cov)[0] * np.diag(cov)[1]))
    Correlation_A_B.append(correlation_ab)
    iii = iii + 1

In [61]:
p_guariti_exp_val_Italy = bokeh_plot_N_lines(x=time_date_new + 6, y_list=[R_2_guariti, Correlation_A_B], 
                  title='Guariti Exponential Validity: Italy', 
                  dim=[600, 450], 
                  x_label='Date', 
                  y_label='R_squared', legend_list=['R_squared', 'Corr_A_B'],
                  x_label_hover='date', y_label_hover='R_squared/Corr_A_B',
                  color_list=['green', 'lightgreen'],legend_location="bottom_right", y_minmax=None)

output_file("guariti_exponential_validity_Italy.html")

show(p_guariti_exp_val_Italy)

----------------------

In [62]:
p_total_cases_deaths_guariti_exp_val_Italy = bokeh_plot_N_lines(x=time_date_new + 6, y_list=[R_2_cases, R_2_deaths, R_2_guariti], 
                  title='Total Cases/Deaths/Guariti Exponential Validity: Italy', 
                  dim=[600, 450], 
                  x_label='Date', 
                  y_label='R_squared', legend_list=['R_squared_cases', 'R_squared_deaths', 'R_squared_guariti'],
                  x_label_hover='date', y_label_hover='R_squared_cases/deaths/guariti',
                  color_list=['blue', 'darkviolet', 'green'],legend_location="bottom_right", y_minmax=None)

output_file("total_cases_deaths_guariti_exponential_validity_Italy.html")

show(p_total_cases_deaths_guariti_exp_val_Italy)

--------------------------

----------------------

--------------------------

### -----  Logistic Fitting -----

In [63]:
fit_range_1 = len(total_cases_italy)
xdata_1 = np.linspace(0, fit_range_1, fit_range_1)
init_guess = [500000, 0.10, 100]
fit = curve_fit(model_population, xdata_1, total_cases_italy.loc[0:(fit_range_1-1)], p0 = init_guess)
ans, cov = fit
fit_K, fit_r, fit_P_0 = ans
fit_K, fit_r, fit_P_0

(235876.11868554226, 0.08524149006460312, 7034.898564310088)

In [64]:
cov

array([[ 7.41395748e+05, -6.36952730e-01,  1.35759454e+05],
       [-6.36952730e-01,  2.90487457e-06, -7.75816451e-01],
       [ 1.35759454e+05, -7.75816451e-01,  2.28099767e+05]])

In [65]:
np.sqrt(np.diag(cov))

array([8.61043407e+02, 1.70436926e-03, 4.77597914e+02])

In [66]:
ydata_1 = model_population(xdata_1, fit_K, fit_r, fit_P_0)
ydata_1

array([  7034.89856431,   7645.02668501,   8306.14981228,   9022.18516971,
         9797.28925545,  10635.86122135,  11542.54392897,  12522.22217258,
        13580.01750099,  14721.27901329,  15951.56945108,  17276.64586409,
        18702.43409309,  20234.99629658,  21880.49075416,  23645.12321408,
        25535.08912467,  27556.50620518,  29715.33697954,  32017.30112294,
        34467.77776203,  37071.69822746,  39833.43018221,  42756.65453645,
        45844.23709784,  49098.09747923,  52519.07836778,  56106.81881975,
        59859.63574381,  63774.41812865,  67846.53881141,  72069.78862476,
        76436.33756274,  80936.72713708,  85559.89734333,  90293.25062371,
        95122.75393175, 100033.07852481, 105007.77551223, 110029.48356404,
       115080.16364506, 120141.35429114, 125194.43988847, 130220.92373548,
       135202.69741361, 140122.29818891, 144963.14679462, 149709.75895645,
       154347.92533796, 158864.8561047 , 163249.28792408, 167491.55282513,
       171583.60984155, 1

In [67]:
pfit_1_total_cases_Italy = bokeh_plot_2_lines(x=time_date_new[0:(fit_range_1)], y=total_cases_italy.loc[0:(fit_range_1-1)], yy=ydata_1[0:fit_range_1], 
                  title='Logistic Fitting Total Cases: Italy', 
                  file_name="fit_1_total_cases_Italy.html", 
                  x_label='Date', y_label='Total Cases', 
                  legend_1='total cases', legend_2='logistic fitting',
                  x_label_hover='date' , y_label_hover='total cases OR fitting' , 
                  color_1='blue', color_2='red', y_minmax=None)

show(pfit_1_total_cases_Italy)

In [68]:
- cov[0,1] / (np.sqrt(np.diag(cov)[0] * np.diag(cov)[1])) # Correlation coefficient for parameters 'K' and 'r'

0.4340287175574379

In [69]:
cov[0,2] / (np.sqrt(np.diag(cov)[0] * np.diag(cov)[2])) # Correlation coefficient for parameters 'K' and 'P_0'

0.3301281931795736

In [70]:
- cov[1,2] / (np.sqrt(np.diag(cov)[1] * np.diag(cov)[2])) # Correlation coefficient for parameters 'r' and 'P_0'

0.9530877133370936

In [71]:
residuals_1 = total_cases_italy.loc[0:(fit_range_1-1)] - ydata_1  #  Calculation of R^2
ss_res_1 = np.sum(residuals_1**2)
ss_tot_1 = np.sum((total_cases_italy.loc[0:(fit_range_1-1)] - np.mean(total_cases_italy.loc[0:(fit_range_1-1)]))**2)
r_squared_1 = 1 - (ss_res_1 / ss_tot_1)
r_squared_1

0.9942496802411641

----------------------

In [72]:
fit_range_2 = len(total_cases_italy) - 15
fit_range_3 = len(total_cases_italy)
xdata_2 = np.linspace(fit_range_2, fit_range_3, fit_range_3 - fit_range_2)
# init_guess = [250000,0.25,1]
init_guess = [500000,0.001,0]
fit = curve_fit(model_population, xdata_2, total_cases_italy.loc[fit_range_2:(fit_range_3-1)], p0=init_guess, maxfev=20000)

/Users/Angelo/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:8: RuntimeWarning: divide by zero encountered in double_scalars
  


In [73]:
ans, cov = fit

In [74]:
fit_K, fit_r, fit_P_0 = ans
fit_K, fit_r, fit_P_0

(258974.52988822546, 0.011900823753385718, 192235.66122586664)

In [75]:
cov

array([[ 8.73952368e+07, -5.79390358e+01,  1.95216454e+08],
       [-5.79390358e+01,  3.84339724e-05, -1.29573762e+02],
       [ 1.95216454e+08, -1.29573762e+02,  4.37091728e+08]])

In [76]:
np.sqrt(np.diag(cov))

array([9.34854196e+03, 6.19951389e-03, 2.09067388e+04])

In [77]:
ydata_2 = fit_K / ( 1 + ((fit_K - fit_P_0) / fit_P_0) * np.exp(- fit_r * xdata_2))
ydata_2

array([240754.22442121, 240969.02437799, 241181.47919868, 241391.61009068,
       241599.4381737 , 241804.98447737, 242008.26993902, 242209.31540142,
       242408.14161077, 242604.76921457, 242799.21875976, 242991.51069076,
       243181.66534773, 243369.70296484, 243555.64366855])

In [78]:
pfit_2_total_cases_Italy = bokeh_plot_2_lines(x=time_date_new[fit_range_2:fit_range_3], y=total_cases_italy.loc[(fit_range_2):(fit_range_3-1)], yy=ydata_2, 
                  title='Logistic Fitting Total Cases: Italy', 
                  file_name="fit_2_total_cases_Italy.html", 
                  x_label='Date', y_label='Total Cases', 
                  legend_1='total cases', legend_2='logistic fitting',
                  x_label_hover='date' , y_label_hover='total cases OR logistic' , 
                  color_1='blue', color_2='red', y_minmax=None)

show(pfit_2_total_cases_Italy)

In [79]:
- cov[0,1] / (np.sqrt(np.diag(cov)[0] * np.diag(cov)[1])) # Correlation coefficient for parameters 'K' and 'r'

0.999700120374718

In [80]:
cov[0,2] / (np.sqrt(np.diag(cov)[0] * np.diag(cov)[2])) # Correlation coefficient for parameters 'K' and 'P_0'

0.9988177338337623

In [81]:
- cov[1,2] / (np.sqrt(np.diag(cov)[1] * np.diag(cov)[2])) # Correlation coefficient for parameters 'r' and 'P_0'

0.9997079339908986

In [82]:
residuals_2 = total_cases_italy.loc[(fit_range_2):(fit_range_3-1)] - ydata_2  #  Calculation of R^2
ss_res_2 = np.sum(residuals_2**2)
ss_tot_2 = np.sum((total_cases_italy.loc[(fit_range_2):(fit_range_3-1)] - np.mean(total_cases_italy.loc[(fit_range_2):(fit_range_3-1)]))**2)
r_squared_2 = 1 - (ss_res_2 / ss_tot_2)
r_squared_2

0.9980568433382947

---------------

In [83]:
max_population = []
max_population_up = []
max_population_down = []

# iii = len(total_cases_italy)
iii = 15

while (iii <= len(total_cases_italy)):
    fit_range_2 = iii - 15
    fit_range_3 = iii
    xdata_2 = np.linspace(fit_range_2, fit_range_3, fit_range_3 - fit_range_2)
    init_guess = [500000,0.001,0]
    fit = curve_fit(model_population, xdata_2, total_cases_italy.loc[fit_range_2:(fit_range_3-1)], p0=init_guess, maxfev=10000)
    ans, cov = fit
    fit_K, fit_r, fit_P_0 = ans
    max_population.append(fit_K)
    max_population_up.append(fit_K + np.sqrt(np.diag(cov))[0])
    max_population_down.append(fit_K - np.sqrt(np.diag(cov))[0])
    iii = iii + 1

/Users/Angelo/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:8: RuntimeWarning: divide by zero encountered in double_scalars
  


In [84]:
len(max_population)

129

In [85]:
p_new_positive_MAX_Italy = bokeh_plot_1_line(x=time_date_new + 14, y=max_population, 
                  title='Total Cases MAX: Italy', 
                  file_name="total_cases_MAX_Italy.html", 
                  x_label='Date', 
                  y_label='Total Cases MAX', legend='total cases max',
                  x_label_hover='date', y_label_hover='total cases max',
                  color='blue', y_minmax=(0,300000))

show(p_new_positive_MAX_Italy)

In [86]:
p_new_positive_MAX_2_Italy = bokeh_plot_N_lines(x=time_date_new + 14, y_list=[max_population,max_population_up,max_population_down], 
                  title='Total Cases MAX: Italy', 
                  dim=[600, 450], 
                  x_label='Date', 
                  y_label='Total Cases MAX', legend_list=['total cases max','total cases max UP','total cases max DOWN'],
                  x_label_hover='date', y_label_hover='total cases max/UP/DOWN',
                  color_list=['blue','lightcoral','lightblue'],legend_location="top_left", y_minmax=(0,300000))

output_file("total_cases_MAX_2_Italy.html")

show(p_new_positive_MAX_2_Italy)

---------------

---------------

---------------

In [87]:
fit_range_3 = len(deceduti_italy) - 15
fit_range_4 = len(deceduti_italy)
xdata_3 = np.linspace(fit_range_3, fit_range_4, fit_range_4 - fit_range_3)
init_guess = [80000,0.001,0.001]
fit = curve_fit(model_population, xdata_3, deceduti_italy.loc[fit_range_3:(fit_range_4-1)], p0=init_guess)

/Users/Angelo/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:8: RuntimeWarning: overflow encountered in exp
  


In [88]:
ans, cov = fit
fit_K, fit_r, fit_P_0 = ans
fit_K, fit_r, fit_P_0

(35205.429373456, 0.044249371487988416, 7985.441548691321)

In [89]:
cov

array([[ 6.45856386e+03, -9.37622107e-01,  6.48485669e+05],
       [-9.37622107e-01,  1.37283853e-04, -9.51050235e+01],
       [ 6.48485669e+05, -9.51050235e+01,  6.59066341e+07]])

In [90]:
np.sqrt(np.diag(cov))

array([8.03651906e+01, 1.17168192e-02, 8.11829010e+03])

In [91]:
ydata_3 = fit_K / ( 1 + ((fit_K - fit_P_0) / fit_P_0) * np.exp(- fit_r * xdata_3))
ydata_3

array([34794.01025253, 34812.84806306, 34830.83262543, 34848.00175509,
       34864.39166615, 34880.03703243, 34894.97104686, 34909.22547908,
       34922.83073141, 34935.81589301, 34948.20879234, 34960.036048  ,
       34971.32311772, 34982.09434583, 34992.37300903])

In [92]:
pfit_total_deaths_Italy = bokeh_plot_2_lines(x=time_date_new[fit_range_3:fit_range_4], y=deceduti_italy.loc[(fit_range_3):(fit_range_4-1)], yy=ydata_3, 
                  title='Logistic Fitting Total Deaths: Italy', 
                  file_name="fit_total_deaths_Italy.html", 
                  x_label='Date', y_label='Total Deaths', 
                  legend_1='total deaths', legend_2='logistic fitting',
                  x_label_hover='date' , y_label_hover='total deaths OR logistic' , 
                  color_1='darkviolet', color_2='violet', y_minmax=None)

show(pfit_total_deaths_Italy)

In [93]:
- cov[0,1] / (np.sqrt(np.diag(cov)[0] * np.diag(cov)[1])) # Correlation coefficient for parameters 'K' and 'r'

0.9957495743922073

In [94]:
cov[0,2] / (np.sqrt(np.diag(cov)[0] * np.diag(cov)[2])) # Correlation coefficient for parameters 'K' and 'P_0'

0.9939575518643494

In [95]:
- cov[1,2] / (np.sqrt(np.diag(cov)[1] * np.diag(cov)[2])) # Correlation coefficient for parameters 'r' and 'P_0'

0.9998369005981866

In [96]:
residuals_3 = deceduti_italy.loc[(fit_range_3):(fit_range_4-1)] - ydata_3  #  Calculation of R^2
ss_res_3 = np.sum(residuals_3**2)
ss_tot_3 = np.sum((deceduti_italy.loc[(fit_range_3):(fit_range_4-1)] - np.mean(deceduti_italy.loc[(fit_range_3):(fit_range_4-1)]))**2)
r_squared_3 = 1 - (ss_res_3 / ss_tot_3)
r_squared_3

0.9932476681464746

---------------

In [97]:
max_deaths = []
max_deaths_up = []
max_deaths_down = []

# iii = len(deceduti_italy)
iii = 15

while (iii <= len(deceduti_italy)):
    fit_range_3 = iii - 15
    fit_range_4 = iii
    xdata_3 = np.linspace(fit_range_3, fit_range_4, fit_range_4 - fit_range_3)
    init_guess = [80000,0.001,0]
    fit = curve_fit(model_population, xdata_3, deceduti_italy.loc[fit_range_3:(fit_range_4-1)], p0=init_guess,  maxfev=10000)
    ans, cov = fit
    fit_K, fit_r, fit_P_0 = ans
    max_deaths.append(fit_K)
    max_deaths_up.append(fit_K + np.sqrt(np.diag(cov))[0])
    max_deaths_down.append(fit_K - np.sqrt(np.diag(cov))[0])
    iii = iii + 1

/Users/Angelo/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:8: RuntimeWarning: divide by zero encountered in double_scalars
  


In [98]:
len(max_deaths)

129

In [99]:
p_total_deaths_MAX_Italy = bokeh_plot_1_line(x=time_date_new + 14, y=max_deaths, 
                  title='Total Deaths MAX: Italy', 
                  file_name="total_deaths_MAX_Italy.html", 
                  x_label='Date', 
                  y_label='Total Deaths MAX', legend='total deaths max',
                  x_label_hover='date', y_label_hover='total deaths max',
                  color='darkviolet', y_minmax=(0,45000))

show(p_total_deaths_MAX_Italy)

In [100]:
p_total_deaths_MAX_2_Italy = bokeh_plot_N_lines(x=time_date_new + 14, y_list=[max_deaths,max_deaths_up,max_deaths_down], 
                  title='Total Deaths MAX: Italy', 
                  dim=[600, 450], 
                  x_label='Date', 
                  y_label='Total Deaths MAX', legend_list=['total deaths max','total deaths max UP','total deaths max DOWN'],
                  x_label_hover='date', y_label_hover='total deaths max/UP/DOWN',
                  color_list=['darkviolet','lightcoral','lightblue'],legend_location="bottom_right", y_minmax=(0,45000))

output_file("total_deaths_MAX_2_Italy.html")

show(p_total_deaths_MAX_2_Italy)

------------------

------------------

------------------

### ----- Gamma Distribution Fitting -----

In [101]:
fit_range_5 = len(nuovi_positivi_italy)   
xdata_4 = np.linspace(1, fit_range_5, fit_range_5)
# init_guess = [1,0.15,20000]
# init_guess = [6,1,500000]
fit = curve_fit(model_Gamma_distribution, xdata_4, nuovi_positivi_italy.loc[0:(fit_range_5-1)])
ans, cov = fit
fit_alpha, fit_beta, fit_Kmax = ans
fit_alpha, fit_beta, fit_Kmax

/Users/Angelo/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:12: RuntimeWarning: overflow encountered in multiply
  if sys.path[0] == '':
/Users/Angelo/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:12: RuntimeWarning: invalid value encountered in multiply
  if sys.path[0] == '':


(3.6199787888986106, -0.10677953556069886, 234858.76278356672)

In [102]:
cov

array([[ 2.81450422e-02, -7.29457240e-04, -3.76959751e+02],
       [-7.29457240e-04,  2.00992682e-05,  1.10823779e+01],
       [-3.76959751e+02,  1.10823779e+01,  1.83846100e+07]])

In [103]:
np.sqrt(np.diag(cov))

array([1.67764842e-01, 4.48322074e-03, 4.28772783e+03])

In [104]:
ydata_4 = model_Gamma_distribution(xdata_4,fit_alpha,fit_beta,fit_Kmax)
ydata_4

array([4.98064374e-01, 5.50343593e+00, 2.14638080e+01, 5.46523181e+01,
       1.10165857e+02, 1.91561260e+02, 3.00801418e+02, 4.38364861e+02,
       6.03438503e+02, 7.94146086e+02, 1.00778358e+03, 1.24104436e+03,
       1.49022426e+03, 1.75140158e+03, 2.02059004e+03, 2.29386486e+03,
       2.56746342e+03, 2.83786250e+03, 3.10183473e+03, 3.35648699e+03,
       3.59928319e+03, 3.82805425e+03, 4.04099742e+03, 4.23666717e+03,
       4.41395950e+03, 4.57209145e+03, 4.71057696e+03, 4.82920068e+03,
       4.92799032e+03, 5.00718872e+03, 5.06722612e+03, 5.10869316e+03,
       5.13231511e+03, 5.13892752e+03, 5.12945357e+03, 5.10488323e+03,
       5.06625430e+03, 5.01463532e+03, 4.95111041e+03, 4.87676587e+03,
       4.79267862e+03, 4.69990623e+03, 4.59947848e+03, 4.49239045e+03,
       4.37959687e+03, 4.26200762e+03, 4.14048443e+03, 4.01583844e+03,
       3.88882867e+03, 3.76016122e+03, 3.63048915e+03, 3.50041283e+03,
       3.37048092e+03, 3.24119157e+03, 3.11299407e+03, 2.98629073e+03,
      

In [105]:
pfit_new_positive_Italy = bokeh_plot_2_lines(x=time_date_new, y=nuovi_positivi_italy.loc[0:(fit_range_5-1)], yy=ydata_4[0:fit_range_5], 
                  title='Gamma Distribution Fitting New Positive: Italy', 
                  file_name="fit_new_positive_Italy.html", 
                  x_label='Date', y_label='New Positive', 
                  legend_1='total cases', legend_2='Gamma fitting',
                  x_label_hover='date' , y_label_hover='new positive OR fitting' , 
                  color_1='blue', color_2='red', y_minmax=None)

show(pfit_new_positive_Italy)

In [106]:
- cov[0,1] / (np.sqrt(np.diag(cov)[0] * np.diag(cov)[1])) # Correlation coefficient for parameters 'alpha' and 'beta'

0.9698593660262984

In [107]:
cov[0,2] / (np.sqrt(np.diag(cov)[0] * np.diag(cov)[2])) # Correlation coefficient for parameters 'alpha' and 'Kmax'

-0.5240428730600548

In [108]:
- cov[1,2] / (np.sqrt(np.diag(cov)[1] * np.diag(cov)[2])) # Correlation coefficient for parameters 'beta' and 'Kmax'

-0.5765216541181714

In [109]:
residuals_4 = nuovi_positivi_italy.loc[0:(fit_range_5-1)] - ydata_4  #  Calculation of R^2
ss_res_4 = np.sum(residuals_4**2)
ss_tot_4 = np.sum((nuovi_positivi_italy.loc[0:(fit_range_5-1)] - np.mean(nuovi_positivi_italy.loc[0:(fit_range_5-1)]))**2)
r_squared_4 = 1 - (ss_res_4 / ss_tot_4)
r_squared_4

0.9439542061810303

----------------

In [110]:
fit_range_6 = time_date_new_extended.shape[0]
xdata_5 = np.linspace(1, fit_range_6, fit_range_6)
ydata_5 = model_Gamma_distribution(xdata_5,fit_alpha,fit_beta,fit_Kmax)
ydata_5

array([4.98064374e-01, 5.50343593e+00, 2.14638080e+01, 5.46523181e+01,
       1.10165857e+02, 1.91561260e+02, 3.00801418e+02, 4.38364861e+02,
       6.03438503e+02, 7.94146086e+02, 1.00778358e+03, 1.24104436e+03,
       1.49022426e+03, 1.75140158e+03, 2.02059004e+03, 2.29386486e+03,
       2.56746342e+03, 2.83786250e+03, 3.10183473e+03, 3.35648699e+03,
       3.59928319e+03, 3.82805425e+03, 4.04099742e+03, 4.23666717e+03,
       4.41395950e+03, 4.57209145e+03, 4.71057696e+03, 4.82920068e+03,
       4.92799032e+03, 5.00718872e+03, 5.06722612e+03, 5.10869316e+03,
       5.13231511e+03, 5.13892752e+03, 5.12945357e+03, 5.10488323e+03,
       5.06625430e+03, 5.01463532e+03, 4.95111041e+03, 4.87676587e+03,
       4.79267862e+03, 4.69990623e+03, 4.59947848e+03, 4.49239045e+03,
       4.37959687e+03, 4.26200762e+03, 4.14048443e+03, 4.01583844e+03,
       3.88882867e+03, 3.76016122e+03, 3.63048915e+03, 3.50041283e+03,
       3.37048092e+03, 3.24119157e+03, 3.11299407e+03, 2.98629073e+03,
      

In [111]:
pfit_2_new_positive_Italy = bokeh_plot_2_lines(x=time_date_new_extended, y=nuovi_positivi_italy.loc[0:(fit_range_5-1)], yy=ydata_5[0:fit_range_6], 
                  title='Gamma Distribution Fitting New Positive Extended: Italy', 
                  file_name="fit_2_new_positive_Italy.html", 
                  x_label='Date', y_label='New Positive', 
                  legend_1='total cases', legend_2='Gamma fitting',
                  x_label_hover='date' , y_label_hover='new positive OR fitting' , 
                  color_1='blue', color_2='red', y_minmax=None)

show(pfit_2_new_positive_Italy)

In [112]:
pfit_3_new_positive_Italy = bokeh_plot_N_lines(x=time_date_new_extended, y_list=[nuovi_positivi_italy.loc[0:(fit_range_5-1)],ydata_5[0:fit_range_6],SMA_new_positive['nuovi_positivi']], 
                  title='Gamma Distribution Fitting New Positive Extended: Italy', 
                  dim=[600, 450],
                  x_label='Date', 
                  y_label='New Positive', legend_list=['new positive','Gamma fitting','SMA 7 days'],
                  x_label_hover='date', y_label_hover='new positive/fitting/SMA 7',
                  color_list=['blue','red','lightblue'],legend_location="top_right", y_minmax=None)

output_file("fit_3_new_positive_Italy.html")

show(pfit_3_new_positive_Italy)

-----------------

------------

In [113]:
fit_range_7 = len(nuovi_deceduti)   
xdata_8 = np.linspace(1, fit_range_7, fit_range_7)
# init_guess = [1,0.15,20000]
fit = curve_fit(model_Gamma_distribution, xdata_8, nuovi_deceduti[0:(fit_range_7)])
ans, cov = fit
fit_alpha, fit_beta, fit_Kmax = ans
fit_alpha, fit_beta, fit_Kmax

/Users/Angelo/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:12: RuntimeWarning: overflow encountered in double_scalars
  if sys.path[0] == '':
/Users/Angelo/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:12: RuntimeWarning: overflow encountered in power
  if sys.path[0] == '':
/Users/Angelo/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:12: RuntimeWarning: invalid value encountered in multiply
  if sys.path[0] == '':
/Users/Angelo/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:12: RuntimeWarning: invalid value encountered in true_divide
  if sys.path[0] == '':


(4.301365901863082, -0.11226339776513365, 34044.54317635012)

In [114]:
cov

array([[ 4.43926965e-02, -1.03799385e-03, -7.46232911e+01],
       [-1.03799385e-03,  2.55776894e-05,  1.94306736e+00],
       [-7.46232911e+01,  1.94306736e+00,  4.44093359e+05]])

In [115]:
np.sqrt(np.diag(cov))

array([2.10695744e-01, 5.05743901e-03, 6.66403301e+02])

In [116]:
ydata_8 = model_Gamma_distribution(xdata_8,fit_alpha,fit_beta,fit_Kmax)
ydata_8

array([7.35616910e-03, 1.29639244e-01, 6.62848155e-01, 2.04204778e+00,
       4.76602099e+00, 9.33228703e+00, 1.61880804e+01, 2.56971264e+01,
       3.81201765e+01, 5.36067204e+01, 7.21953038e+01, 9.38201238e+01,
       1.18321908e+02, 1.45461443e+02, 1.74934434e+02, 2.06386709e+02,
       2.39429000e+02, 2.73650782e+02, 3.08632818e+02, 3.43958190e+02,
       3.79221725e+02, 4.14037799e+02, 4.48046567e+02, 4.80918707e+02,
       5.12358812e+02, 5.42107556e+02, 5.69942790e+02, 5.95679716e+02,
       6.19170292e+02, 6.40301989e+02, 6.58996057e+02, 6.75205387e+02,
       6.88912100e+02, 7.00124942e+02, 7.08876564e+02, 7.15220770e+02,
       7.19229773e+02, 7.20991516e+02, 7.20607095e+02, 7.18188308e+02,
       7.13855361e+02, 7.07734735e+02, 6.99957232e+02, 6.90656206e+02,
       6.79965966e+02, 6.68020371e+02, 6.54951593e+02, 6.40889047e+02,
       6.25958484e+02, 6.10281232e+02, 5.93973577e+02, 5.77146267e+02,
       5.59904139e+02, 5.42345848e+02, 5.24563693e+02, 5.06643522e+02,
      

In [117]:
pfit_new_deaths_Italy = bokeh_plot_2_lines(x=time_date_new, y=nuovi_deceduti[0:(fit_range_7)], yy=ydata_8[0:fit_range_7], 
                  title='Gamma Distribution Fitting New Deaths: Italy', 
                  file_name="fit_new_deaths_Italy.html", 
                  x_label='Date', y_label='New Deaths', 
                  legend_1='new deaths', legend_2='Gamma fitting',
                  x_label_hover='date' , y_label_hover='new deaths OR fitting' , 
                  color_1='darkviolet', color_2='red', y_minmax=None)

show(pfit_new_deaths_Italy)

In [118]:
- cov[0,1] / (np.sqrt(np.diag(cov)[0] * np.diag(cov)[1])) # Correlation coefficient for parameters 'alpha' and 'beta'

0.9741108075129652

In [119]:
cov[0,2] / (np.sqrt(np.diag(cov)[0] * np.diag(cov)[2])) # Correlation coefficient for parameters 'alpha' and 'Kmax'

-0.5314733555453739

In [120]:
- cov[1,2] / (np.sqrt(np.diag(cov)[1] * np.diag(cov)[2])) # Correlation coefficient for parameters 'beta' and 'Kmax'

-0.5765275473398974

In [121]:
residuals_8 = nuovi_deceduti[0:(fit_range_7)] - ydata_8  #  Calculation of R^2
ss_res_8 = np.sum(residuals_8**2)
ss_tot_8 = np.sum((nuovi_deceduti[0:(fit_range_7)] - np.mean(nuovi_deceduti[0:(fit_range_7)]))**2)
r_squared_8 = 1 - (ss_res_8 / ss_tot_8)
r_squared_8

0.9350690201304053

-----------

In [122]:
fit_range_8 = time_date_new_extended.shape[0]
xdata_9 = np.linspace(1, fit_range_8, fit_range_8)
ydata_9 = model_Gamma_distribution(xdata_9,fit_alpha,fit_beta,fit_Kmax)
ydata_9

array([7.35616910e-03, 1.29639244e-01, 6.62848155e-01, 2.04204778e+00,
       4.76602099e+00, 9.33228703e+00, 1.61880804e+01, 2.56971264e+01,
       3.81201765e+01, 5.36067204e+01, 7.21953038e+01, 9.38201238e+01,
       1.18321908e+02, 1.45461443e+02, 1.74934434e+02, 2.06386709e+02,
       2.39429000e+02, 2.73650782e+02, 3.08632818e+02, 3.43958190e+02,
       3.79221725e+02, 4.14037799e+02, 4.48046567e+02, 4.80918707e+02,
       5.12358812e+02, 5.42107556e+02, 5.69942790e+02, 5.95679716e+02,
       6.19170292e+02, 6.40301989e+02, 6.58996057e+02, 6.75205387e+02,
       6.88912100e+02, 7.00124942e+02, 7.08876564e+02, 7.15220770e+02,
       7.19229773e+02, 7.20991516e+02, 7.20607095e+02, 7.18188308e+02,
       7.13855361e+02, 7.07734735e+02, 6.99957232e+02, 6.90656206e+02,
       6.79965966e+02, 6.68020371e+02, 6.54951593e+02, 6.40889047e+02,
       6.25958484e+02, 6.10281232e+02, 5.93973577e+02, 5.77146267e+02,
       5.59904139e+02, 5.42345848e+02, 5.24563693e+02, 5.06643522e+02,
      

In [123]:
pfit_2_new_deaths_Italy = bokeh_plot_2_lines(x=time_date_new_extended, y=nuovi_deceduti[0:(fit_range_7)], yy=ydata_9[0:fit_range_8], 
                  title='Gamma Distribution Fitting New Deaths Extended: Italy', 
                  file_name="fit_2_new_deaths_Italy.html", 
                  x_label='Date', y_label='New Deaths', 
                  legend_1='new deaths', legend_2='Gamma fitting',
                  x_label_hover='date' , y_label_hover='new deaths OR fitting' , 
                  color_1='darkviolet', color_2='red', y_minmax=None)

show(pfit_2_new_deaths_Italy)

-----------------
-----------------
-----------------

In [124]:
s1_grid = bokeh_plot_N_lines(x=time_date_new, y_list=[total_cases_italy,total_positive_italy], 
                  title='Total Cases & Total Positive: Italy', 
                  dim=[470, 350], 
                  x_label='Date', 
                  y_label='Total Cases & Total Positive', legend_list=['total cases','total positive'],
                  x_label_hover='date', y_label_hover='total cases OR total positive',
                  color_list=['blue','red'],legend_location="top_left", y_minmax=None)

s2_grid = bokeh_plot_N_lines(x=time_date_new, y_list=[deceduti_italy,guariti_italy], 
                  title='Deaths & Recovered: Italy', 
                  dim=[470, 350], 
                  x_label='Date', 
                  y_label='Deaths & Recovered', legend_list=['deaths','recovered'],
                  x_label_hover='date', y_label_hover='deaths OR recovered',
                  color_list=['darkviolet','green'],legend_location="top_left", y_minmax=None)


s3_grid = bokeh_plot_N_lines(x=time_date_new + 6, y_list=[R_2_cases, R_2_deaths, R_2_guariti], 
                  title='Total Cases/Deaths/Guariti - Exponential Validity: Italy', 
                  dim=[470, 350], 
                  x_label='Date', 
                  y_label='R_squared', legend_list=['R_squared_cases', 'R_squared_deaths', 'R_squared_guariti'],
                  x_label_hover='date', y_label_hover='R_squared_cases/deaths/guariti',
                  color_list=['blue', 'darkviolet', 'green'], legend_location="bottom_left", y_minmax=None)

s4_grid = bokeh_plot_N_lines(x=time_date_new + 14, y_list=[max_population_up,max_population_down,max_population], 
                  title='Max Total Cases - Logistic Fitting: Italy', 
                  dim=[470, 350], 
                  x_label='Date', 
                  y_label='Total Cases MAX', legend_list=['total cases max UP','total cases max DOWN','total cases max'],
                  x_label_hover='date', y_label_hover='total cases max/UP/DOWN',
                  color_list=['lightcoral','lightblue','blue'],legend_location="bottom_right", y_minmax=(0,300000))

s5_grid = bokeh_plot_N_lines(x=time_date_new + 14, y_list=[max_deaths_up,max_deaths_down,max_deaths], 
                  title='Max Total Deaths - Logistic Fitting: Italy', 
                  dim=[470, 350], 
                  x_label='Date', 
                  y_label='Total Deaths MAX', legend_list=['total deaths max UP','total deaths max DOWN','total deaths max'],
                  x_label_hover='date', y_label_hover='total deaths max/UP/DOWN',
                  color_list=['lightcoral','lightblue','darkviolet'],legend_location="bottom_right", y_minmax=(0,45000))

s6_grid = bokeh_plot_N_lines(x=time_date_new_extended, y_list=[nuovi_positivi_italy.loc[0:(fit_range_5-1)],ydata_5[0:fit_range_6]], 
                  title='New Positive - Gamma Distribution Fitting: Italy', 
                  dim=[470, 350],
                  x_label='Date', 
                  y_label='New Positive', legend_list=['new positive','Gamma fitting'],
                  x_label_hover='date', y_label_hover='new positive/fitting',
                  color_list=['blue','lightcoral'],legend_location="top_right", y_minmax=None)

s7_grid = bokeh_plot_N_lines(x=time_date_new_extended, y_list=[nuovi_deceduti[0:(fit_range_7)],ydata_9[0:fit_range_8]], 
                  title='New Deaths - Gamma Distribution Fitting: Italy', 
                  dim=[470, 350],
                  x_label='Date', 
                  y_label='New Deaths', legend_list=['new deaths','Gamma fitting'],
                  x_label_hover='date', y_label_hover='new deaths/fitting',
                  color_list=['darkviolet','lightcoral'],legend_location="top_right", y_minmax=None)

In [125]:
p_grid = gridplot([[s1_grid, s2_grid, s3_grid], [s4_grid, s5_grid], [s6_grid, s7_grid]])

output_file("grid_1.html")

show(p_grid)